'use strict';

const PizZip = require('pizzip');
const Docxtemplater = require('docxtemplater');
const { storage, BUCKET_NAME } = require('../../../../../utils/storage');

const getCheckmark = (status) => (status === true ? '√' : '');
const getOppositeCheckmark = (status) => (status === false ? '√' : '');
const getCheckmarkForValue = (value) => (value ? '√' : '');

const formatResultText = (status) => {
    if (status === true) return 'Memenuhi Syarat';
    if (status === false) return 'Tidak Memenuhi Syarat';
    return ''; // Jika nilainya null atau undefined
};

const createLaporanOverheadCrane = async (data) => {
    const templatePath = 'paa/overHeadCrane/laporanOverheadCrane.docx';

    let content;
    try {
        [content] = await storage.bucket(BUCKET_NAME).file(templatePath).download();
    } catch (error) {
        console.error('Gagal mengunduh template Laporan Overhead Crane:', error);
        throw new Error('Template dokumen Laporan Overhead Crane tidak dapat diakses.');
    }

    const zip = new PizZip(content);
    const doc = new Docxtemplater(zip, {
        paragraphLoop: true,
        linebreaks: true,
        nullGetter: () => "" 
    });

    const general = data.generalData || {};
    const tech = data.technicalData || {};
    const vi = data.visualInspection || {};
    const ndt = data.nonDestructiveExamination || {};
    const test = data.testing || {};

    const renderData = {
        // --- DATA UTAMA & UMUM ---
        examinationType: data.examinationType?.toUpperCase(),
        inspectionType: data.inspectionType?.toUpperCase(),
        subInspectionType: data.subInspectionType,
        ownerName: general.ownerName,
        ownerAddress: general.ownerAddress,
        userInCharge: general.userInCharge,
        subcontractorPersonInCharge: general.subcontractorPersonInCharge,
        unitLocation: general.unitLocation,
        equipmentType: general.equipmentType,
        manufacturer: general.manufacturer,
        brandType: general.brandType,
        locationAndYearOfManufacture: general.yearOfManufacture,
        serialNumberUnitNumber: general.serialNumberUnitNumber,
        capacityWorkingLoad: general.capacityWorkingLoadKg,
        intendedUse: general.intendedUse,
        usagePermitNumber: general.usagePermitNumber,
        operatorCertificate: general.operatorCertificate,
        technicalOrManualData: general.technicalOrManualData,

        // --- DATA TEKNIS ---
        specificationHoistingLiftingHeight: tech.specifications?.liftingHeight?.hoisting,
        specificationTravelingLiftingHeight: tech.specifications?.liftingHeight?.traveling,
        specificationTraversingLiftingHeight: tech.specifications?.liftingHeight?.traversing,
        specificationHoistingGirderLength: tech.specifications?.girderLength?.hoisting,
        specificationTravelingGirderLength: tech.specifications?.girderLength?.traveling,
        specificationTraversingGirderLength: tech.specifications?.girderLength?.traversing,
        specificationHoistingSpeed: tech.specifications?.speed_m_per_min?.hoisting,
        specificationTravelingSpeed: tech.specifications?.speed_m_per_min?.traveling,
        specificationTraversingSpeed: tech.specifications?.speed_m_per_min?.traversing,
        driveMotorHoistingCapacity: tech.driveMotor?.capacity_ton?.hoisting,
        driveMotorTravelingCapacity: tech.driveMotor?.capacity_ton?.traveling,
        driveMotorTraversingCapacity: tech.driveMotor?.capacity_ton?.traversing,
        driveMotorHoistingPower: tech.driveMotor?.power_kw?.hoisting,
        driveMotorTravelingPower: tech.driveMotor?.power_kw?.traveling,
        driveMotorTraversingPower: tech.driveMotor?.power_kw?.traversing,
        driveMotorHoistingType: tech.driveMotor?.type?.hoisting,
        driveMotorTravelingType: tech.driveMotor?.type?.traveling,
        driveMotorTraversingType: tech.driveMotor?.type?.traversing,
        driveMotorHoistingRevolution: tech.driveMotor?.revolution_rpm?.hoisting,
        driveMotorTravelingRevolution: tech.driveMotor?.revolution_rpm?.traveling,
        driveMotorTraversingRevolution: tech.driveMotor?.revolution_rpm?.traversing,
        driveMotorHoistingVoltage: tech.driveMotor?.voltage_v?.hoisting,
        driveMotorTravelingVoltage: tech.driveMotor?.voltage_v?.traveling,
        driveMotorTraversingVoltage: tech.driveMotor?.voltage_v?.traversing,
        driveMotorHoistingCurrent: tech.driveMotor?.current_a?.hoisting,
        driveMotorTravelingCurrent: tech.driveMotor?.current_a?.traveling,
        driveMotorTraversingCurrent: tech.driveMotor?.current_a?.traversing,
        driveMotorHoistingFrequency: tech.driveMotor?.frequency_hz?.hoisting,
        driveMotorTravelingFrequency: tech.driveMotor?.frequency_hz?.traveling,
        driveMotorTraversingFrequency: tech.driveMotor?.frequency_hz?.traversing,
        resistorHoistingType: tech.startingResistor?.type?.hoisting,
        resistorTravelingType: tech.startingResistor?.type?.traveling,
        resistorTraversingType: tech.startingResistor?.type?.traversing,
        resistorHoistingVoltage: tech.startingResistor?.voltage_v?.hoisting,
        resistorTravelingVoltage: tech.startingResistor?.voltage_v?.traveling,
        resistorTraversingVoltage: tech.startingResistor?.voltage_v?.traversing,
        resistorHoistingCurrent: tech.startingResistor?.current_a?.hoisting,
        resistorTravelingCurrent: tech.startingResistor?.current_a?.traveling,
        resistorTraversingCurrent: tech.startingResistor?.current_a?.traversing,
        brakeHoistingKind: tech.brake?.kind?.hoisting,
        brakeTravelingKind: tech.brake?.kind?.traveling,
        brakeTraversingKind: tech.brake?.kind?.traversing,
        brakeHoistingType: tech.brake?.type?.hoisting,
        brakeTravelingType: tech.brake?.type?.traveling,
        brakeTraversingType: tech.brake?.type?.traversing,
        controllerBrakeHoistingKind: tech.controllerBrake?.kind?.hoisting,
        controllerBrakeTravelingKind: tech.controllerBrake?.kind?.traveling,
        controllerBrakeTraversingKind: tech.controllerBrake?.kind?.traversing,
        controllerBrakeHoistingType: tech.controllerBrake?.type?.hoisting,
        controllerBrakeTravelingType: tech.controllerBrake?.type?.traveling,
        controllerBrakeTraversingType: tech.controllerBrake?.type?.traversing,
        hookHoistingType: tech.hook?.type?.hoisting,
        hookTravelingType: tech.hook?.type?.traveling,
        hookTraversingType: tech.hook?.type?.traversing,
        hookHoistingCapacity: tech.hook?.capacity?.hoisting,
        hookTravelingCapacity: tech.hook?.capacity?.traveling,
        hookTraversingCapacity: tech.hook?.capacity?.traversing,
        hookHoistingMaterial: tech.hook?.material?.hoisting,
        hookTravelingMaterial: tech.hook?.material?.traveling,
        hookTraversingMaterial: tech.hook?.material?.traversing,
        chainHoistingType: tech.chain?.type?.hoisting,
        chainTravelingType: tech.chain?.type?.traveling,
        chainTraversingType: tech.chain?.type?.traversing,
        chainHoistingConstruction: tech.chain?.construction?.hoisting,
        chainTravelingConstruction: tech.chain?.construction?.traveling,
        chainTraversingConstruction: tech.chain?.construction?.traversing,
        chainHoistingDiameter: tech.chain?.diameter?.hoisting,
        chainTravelingDiameter: tech.chain?.diameter?.traveling,
        chainTraversingDiameter: tech.chain?.diameter?.traversing,
        chainHoistingLength: tech.chain?.length?.hoisting,
        chainTravelingLength: tech.chain?.length?.traveling,
        chainTraversingLength: tech.chain?.length?.traversing,

        // --- PEMERIKSAAN VISUAL (LENGKAP) ---
        foundationBoltsCorrosionMemenuhi: getCheckmark(vi.foundation?.bolts?.corrosion?.status),
        foundationBoltsCorrosionTidakMemenuhi: getOppositeCheckmark(vi.foundation?.bolts?.corrosion?.status),
        foundationBoltsCorrosionResult: vi.foundation?.bolts?.corrosion?.remarks,
        foundationBoltsCracksMemenuhi: getCheckmark(vi.foundation?.bolts?.cracks?.status),
        foundationBoltsCracksTidakMemenuhi: getOppositeCheckmark(vi.foundation?.bolts?.cracks?.status),
        foundationBoltsCracksResult: vi.foundation?.bolts?.cracks?.remarks,
        foundationBoltsDeformationMemenuhi: getCheckmark(vi.foundation?.bolts?.deformation?.status),
        foundationBoltsDeformationTidakMemenuhi: getOppositeCheckmark(vi.foundation?.bolts?.deformation?.status),
        foundationBoltsDeformationResult: vi.foundation?.bolts?.deformation?.remarks,
        foundationBoltsFasteningMemenuhi: getCheckmark(vi.foundation?.bolts?.fastening?.status),
        foundationBoltsFasteningTidakMemenuhi: getOppositeCheckmark(vi.foundation?.bolts?.fastening?.status),
        foundationBoltsFasteningResult: vi.foundation?.bolts?.fastening?.remarks,
        columnFrameCorrosionMemenuhi: getCheckmark(vi.columnFrame?.corrosion?.status),
        columnFrameCorrosionTidakMemenuhi: getOppositeCheckmark(vi.columnFrame?.corrosion?.status),
        columnFrameCorrosionResult: vi.columnFrame?.corrosion?.remarks,
        columnFrameCracksMemenuhi: getCheckmark(vi.columnFrame?.cracks?.status),
        columnFrameCracksTidakMemenuhi: getOppositeCheckmark(vi.columnFrame?.cracks?.status),
        columnFrameCracksResult: vi.columnFrame?.cracks?.remarks,
        columnFrameDeformationMemenuhi: getCheckmark(vi.columnFrame?.deformation?.status),
        columnFrameDeformationTidakMemenuhi: getOppositeCheckmark(vi.columnFrame?.deformation?.status),
        columnFrameDeformationResult: vi.columnFrame?.deformation?.remarks,
        columnFrameFasteningMemenuhi: getCheckmark(vi.columnFrame?.fastening?.status),
        columnFrameFasteningTidakMemenuhi: getOppositeCheckmark(vi.columnFrame?.fastening?.status),
        columnFrameFasteningResult: vi.columnFrame?.fastening?.remarks,
        columnFrameCrossBracingMemenuhi: getCheckmark(vi.columnFrame?.crossBracing?.status),
        columnFrameCrossBracingTidakMemenuhi: getOppositeCheckmark(vi.columnFrame?.crossBracing?.status),
        columnFrameCrossBracingResult: vi.columnFrame?.crossBracing?.remarks,
        columnFrameDiagonalBracingMemenuhi: getCheckmark(vi.columnFrame?.diagonalBracing?.status),
        columnFrameDiagonalBracingTidakMemenuhi: getOppositeCheckmark(vi.columnFrame?.diagonalBracing?.status),
        columnFrameDiagonalBracingResult: vi.columnFrame?.diagonalBracing?.remarks,
        stairsCorrosionMemenuhi: getCheckmark(vi.stairs?.corrosion?.status),
        stairsCorrosionTidakMemenuhi: getOppositeCheckmark(vi.stairs?.corrosion?.status),
        stairsCorrosionResult: vi.stairs?.corrosion?.remarks,
        stairsCracksMemenuhi: getCheckmark(vi.stairs?.cracks?.status),
        stairsCracksTidakMemenuhi: getOppositeCheckmark(vi.stairs?.cracks?.status),
        stairsCracksResult: vi.stairs?.cracks?.remarks,
        stairsDeformationMemenuhi: getCheckmark(vi.stairs?.deformation?.status),
        stairsDeformationTidakMemenuhi: getOppositeCheckmark(vi.stairs?.deformation?.status),
        stairsDeformationResult: vi.stairs?.deformation?.remarks,
        stairsFasteningMemenuhi: getCheckmark(vi.stairs?.fastening?.status),
        stairsFasteningTidakMemenuhi: getOppositeCheckmark(vi.stairs?.fastening?.status),
        stairsFasteningResult: vi.stairs?.fastening?.remarks,
        platformCorrosionMemenuhi: getCheckmark(vi.platform?.corrosion?.status),
        platformCorrosionTidakMemenuhi: getOppositeCheckmark(vi.platform?.corrosion?.status),
        platformCorrosionResult: vi.platform?.corrosion?.remarks,
        platformCracksMemenuhi: getCheckmark(vi.platform?.cracks?.status),
        platformCracksTidakMemenuhi: getOppositeCheckmark(vi.platform?.cracks?.status),
        platformCracksResult: vi.platform?.cracks?.remarks,
        platformDeformationMemenuhi: getCheckmark(vi.platform?.deformation?.status),
        platformDeformationTidakMemenuhi: getOppositeCheckmark(vi.platform?.deformation?.status),
        platformDeformationResult: vi.platform?.deformation?.remarks,
        platformFasteningMemenuhi: getCheckmark(vi.platform?.fastening?.status),
        platformFasteningTidakMemenuhi: getOppositeCheckmark(vi.platform?.fastening?.status),
        platformFasteningResult: vi.platform?.fastening?.remarks,
        railSupportCorrosionMemenuhi: getCheckmark(vi.railSupportBeam?.corrosion?.status),
        railSupportCorrosionTidakMemenuhi: getOppositeCheckmark(vi.railSupportBeam?.corrosion?.status),
        railSupportCorrosionResult: vi.railSupportBeam?.corrosion?.remarks,
        railSupportCracksMemenuhi: getCheckmark(vi.railSupportBeam?.cracks?.status),
        railSupportCracksTidakMemenuhi: getOppositeCheckmark(vi.railSupportBeam?.cracks?.status),
        railSupportCracksResult: vi.railSupportBeam?.cracks?.remarks,
        railSupportDeformationMemenuhi: getCheckmark(vi.railSupportBeam?.deformation?.status),
        railSupportDeformationTidakMemenuhi: getOppositeCheckmark(vi.railSupportBeam?.deformation?.status),
        railSupportDeformationResult: vi.railSupportBeam?.deformation?.remarks,
        railSupportFasteningMemenuhi: getCheckmark(vi.railSupportBeam?.fastening?.status),
        railSupportFasteningTidakMemenuhi: getOppositeCheckmark(vi.railSupportBeam?.fastening?.status),
        railSupportFasteningResult: vi.railSupportBeam?.fastening?.remarks,
        travelingRailCorrosionMemenuhi: getCheckmark(vi.travelingRail?.corrosion?.status),
        travelingRailCorrosionTidakMemenuhi: getOppositeCheckmark(vi.travelingRail?.corrosion?.status),
        travelingRailCorrosionResult: vi.travelingRail?.corrosion?.remarks,
        travelingRailCracksMemenuhi: getCheckmark(vi.travelingRail?.cracks?.status),
        travelingRailCracksTidakMemenuhi: getOppositeCheckmark(vi.travelingRail?.cracks?.status),
        travelingRailCracksResult: vi.travelingRail?.cracks?.remarks,
        travelingRailJointsMemenuhi: getCheckmark(vi.travelingRail?.joints?.status),
        travelingRailJointsTidakMemenuhi: getOppositeCheckmark(vi.travelingRail?.joints?.status),
        travelingRailJointsResult: vi.travelingRail?.joints?.remarks,
        travelingRailStraightnessMemenuhi: getCheckmark(vi.travelingRail?.straightness?.status),
        travelingRailStraightnessTidakMemenuhi: getOppositeCheckmark(vi.travelingRail?.straightness?.status),
        travelingRailStraightnessResult: vi.travelingRail?.straightness?.remarks,
        travelingInterRailStraightnessMemenuhi: getCheckmark(vi.travelingRail?.interRailStraightness?.status),
        travelingInterRailStraightnessTidakMemenuhi: getOppositeCheckmark(vi.travelingRail?.interRailStraightness?.status),
        travelingInterRailStraightnessResult: vi.travelingRail?.interRailStraightness?.remarks,
        travelingInterRailEvennessMemenuhi: getCheckmark(vi.travelingRail?.interRailEvenness?.status),
        travelingInterRailEvennessTidakMemenuhi: getOppositeCheckmark(vi.travelingRail?.interRailEvenness?.status),
        travelingInterRailEvennessResult: vi.travelingRail?.interRailEvenness?.remarks,
        travelingRailJointGapMemenuhi: getCheckmark(vi.travelingRail?.jointGap?.status),
        travelingRailJointGapTidakMemenuhi: getOppositeCheckmark(vi.travelingRail?.jointGap?.status),
        travelingRailJointGapResult: vi.travelingRail?.jointGap?.remarks,
        travelingRailFastenersMemenuhi: getCheckmark(vi.travelingRail?.fasteners?.status),
        travelingRailFastenersTidakMemenuhi: getOppositeCheckmark(vi.travelingRail?.fasteners?.status),
        travelingRailFastenersResult: vi.travelingRail?.fasteners?.remarks,
        travelingRailStopperMemenuhi: getCheckmark(vi.travelingRail?.stopper?.status),
        travelingRailStopperTidakMemenuhi: getOppositeCheckmark(vi.travelingRail?.stopper?.status),
        travelingRailStopperResult: vi.travelingRail?.stopper?.remarks,
        traversingRailCorrosionMemenuhi: getCheckmark(vi.traversingRail?.corrosion?.status),
        traversingRailCorrosionTidakMemenuhi: getOppositeCheckmark(vi.traversingRail?.corrosion?.status),
        traversingRailCorrosionResult: vi.traversingRail?.corrosion?.remarks,
        traversingRailCracksMemenuhi: getCheckmark(vi.traversingRail?.cracks?.status),
        traversingRailCracksTidakMemenuhi: getOppositeCheckmark(vi.traversingRail?.cracks?.status),
        traversingRailCracksResult: vi.traversingRail?.cracks?.remarks,
        traversingRailJointsMemenuhi: getCheckmark(vi.traversingRail?.joints?.status),
        traversingRailJointsTidakMemenuhi: getOppositeCheckmark(vi.traversingRail?.joints?.status),
        traversingRailJointsResult: vi.traversingRail?.joints?.remarks,
        traversingRailStraightnessMemenuhi: getCheckmark(vi.traversingRail?.straightness?.status),
        traversingRailStraightnessTidakMemenuhi: getOppositeCheckmark(vi.traversingRail?.straightness?.status),
        traversingRailStraightnessResult: vi.traversingRail?.straightness?.remarks,
        traversingInterRailStraightnessMemenuhi: getCheckmark(vi.traversingRail?.interRailStraightness?.status),
        traversingInterRailStraightnessTidakMemenuhi: getOppositeCheckmark(vi.traversingRail?.interRailStraightness?.status),
        traversingInterRailStraightnessResult: vi.traversingRail?.interRailStraightness?.remarks,
        traversingInterRailEvennessMemenuhi: getCheckmark(vi.traversingRail?.interRailEvenness?.status),
        traversingInterRailEvennessTidakMemenuhi: getOppositeCheckmark(vi.traversingRail?.interRailEvenness?.status),
        traversingInterRailEvennessResult: vi.traversingRail?.interRailEvenness?.remarks,
        traversingRailJointGapMemenuhi: getCheckmark(vi.traversingRail?.jointGap?.status),
        traversingRailJointGapTidakMemenuhi: getOppositeCheckmark(vi.traversingRail?.jointGap?.status),
        traversingRailJointGapResult: vi.traversingRail?.jointGap?.remarks,
        traversingRailFastenersMemenuhi: getCheckmark(vi.traversingRail?.fasteners?.status),
        traversingRailFastenersTidakMemenuhi: getOppositeCheckmark(vi.traversingRail?.fasteners?.status),
        traversingRailFastenersResult: vi.traversingRail?.fasteners?.remarks,
        traversingRailStopperMemenuhi: getCheckmark(vi.traversingRail?.stopper?.status),
        traversingRailStopperTidakMemenuhi: getOppositeCheckmark(vi.traversingRail?.stopper?.status),
        traversingRailStopperResult: vi.traversingRail?.stopper?.remarks,
        girderCorrosionMemenuhi: getCheckmark(vi.girder?.corrosion?.status),
        girderCorrosionTidakMemenuhi: getOppositeCheckmark(vi.girder?.corrosion?.status),
        girderCorrosionResult: vi.girder?.corrosion?.remarks,
        girderCracksMemenuhi: getCheckmark(vi.girder?.cracks?.status),
        girderCracksTidakMemenuhi: getOppositeCheckmark(vi.girder?.cracks?.status),
        girderCracksResult: vi.girder?.cracks?.remarks,
        girderCamberMemenuhi: getCheckmark(vi.girder?.camber?.status),
        girderCamberTidakMemenuhi: getOppositeCheckmark(vi.girder?.camber?.status),
        girderCamberResult: vi.girder?.camber?.remarks,
        girderJointsMemenuhi: getCheckmark(vi.girder?.joints?.status),
        girderJointsTidakMemenuhi: getOppositeCheckmark(vi.girder?.joints?.status),
        girderJointsResult: vi.girder?.joints?.remarks,
        girderEndJointsMemenuhi: getCheckmark(vi.girder?.endJoints?.status),
        girderEndJointsTidakMemenuhi: getOppositeCheckmark(vi.girder?.endJoints?.status),
        girderEndJointsResult: vi.girder?.endJoints?.remarks,
        girderTruckMountMemenuhi: getCheckmark(vi.girder?.truckMount?.status),
        girderTruckMountTidakMemenuhi: getOppositeCheckmark(vi.girder?.truckMount?.status),
        girderTruckMountResult: vi.girder?.truckMount?.remarks,
        travelingGearboxCorrosionMemenuhi: getCheckmark(vi.travelingGearbox?.corrosion?.status),
        travelingGearboxCorrosionTidakMemenuhi: getOppositeCheckmark(vi.travelingGearbox?.corrosion?.status),
        travelingGearboxCorrosionResult: vi.travelingGearbox?.corrosion?.remarks,
        travelingGearboxCracksMemenuhi: getCheckmark(vi.travelingGearbox?.cracks?.status),
        travelingGearboxCracksTidakMemenuhi: getOppositeCheckmark(vi.travelingGearbox?.cracks?.status),
        travelingGearboxCracksResult: vi.travelingGearbox?.cracks?.remarks,
        travelingGearboxLubricantMemenuhi: getCheckmark(vi.travelingGearbox?.lubricant?.status),
        travelingGearboxLubricantTidakMemenuhi: getOppositeCheckmark(vi.travelingGearbox?.lubricant?.status),
        travelingGearboxLubricantResult: vi.travelingGearbox?.lubricant?.remarks,
        travelingGearboxOilSealMemenuhi: getCheckmark(vi.travelingGearbox?.oilSeal?.status),
        travelingGearboxOilSealTidakMemenuhi: getOppositeCheckmark(vi.travelingGearbox?.oilSeal?.status),
        travelingGearboxOilSealResult: vi.travelingGearbox?.oilSeal?.remarks,
        driveWheelWearMemenuhi: getCheckmark(vi.driveWheel?.wear?.status),
        driveWheelWearTidakMemenuhi: getOppositeCheckmark(vi.driveWheel?.wear?.status),
        driveWheelWearResult: vi.driveWheel?.wear?.remarks,
        driveWheelCracksMemenuhi: getCheckmark(vi.driveWheel?.cracks?.status),
        driveWheelCracksTidakMemenuhi: getOppositeCheckmark(vi.driveWheel?.cracks?.status),
        driveWheelCracksResult: vi.driveWheel?.cracks?.remarks,
        driveWheelDeformationMemenuhi: getCheckmark(vi.driveWheel?.deformation?.status),
        driveWheelDeformationTidakMemenuhi: getOppositeCheckmark(vi.driveWheel?.deformation?.status),
        driveWheelDeformationResult: vi.driveWheel?.deformation?.remarks,
        driveWheelFlangeMemenuhi: getCheckmark(vi.driveWheel?.flange?.status),
        driveWheelFlangeTidakMemenuhi: getOppositeCheckmark(vi.driveWheel?.flange?.status),
        driveWheelFlangeResult: vi.driveWheel?.flange?.remarks,
        driveWheelChainMemenuhi: getCheckmark(vi.driveWheel?.chain?.status),
        driveWheelChainTidakMemenuhi: getOppositeCheckmark(vi.driveWheel?.chain?.status),
        driveWheelChainResult: vi.driveWheel?.chain?.remarks,
        idleWheelSecurityMemenuhi: getCheckmark(vi.idleWheel?.security?.status),
        idleWheelSecurityTidakMemenuhi: getOppositeCheckmark(vi.idleWheel?.security?.status),
        idleWheelSecurityResult: vi.idleWheel?.security?.remarks,
        idleWheelCracksMemenuhi: getCheckmark(vi.idleWheel?.cracks?.status),
        idleWheelCracksTidakMemenuhi: getOppositeCheckmark(vi.idleWheel?.cracks?.status),
        idleWheelCracksResult: vi.idleWheel?.cracks?.remarks,
        idleWheelDeformationMemenuhi: getCheckmark(vi.idleWheel?.deformation?.status),
        idleWheelDeformationTidakMemenuhi: getOppositeCheckmark(vi.idleWheel?.deformation?.status),
        idleWheelDeformationResult: vi.idleWheel?.deformation?.remarks,
        idleWheelFlangeMemenuhi: getCheckmark(vi.idleWheel?.flange?.status),
        idleWheelFlangeTidakMemenuhi: getOppositeCheckmark(vi.idleWheel?.flange?.status),
        idleWheelFlangeResult: vi.idleWheel?.flange?.remarks,
        wheelConnectorStraightnessMemenuhi: getCheckmark(vi.wheelConnector?.straightness?.status),
        wheelConnectorStraightnessTidakMemenuhi: getOppositeCheckmark(vi.wheelConnector?.straightness?.status),
        wheelConnectorStraightnessResult: vi.wheelConnector?.straightness?.remarks,
        wheelConnectorCrossJointMemenuhi: getCheckmark(vi.wheelConnector?.crossJoint?.status),
        wheelConnectorCrossJointTidakMemenuhi: getOppositeCheckmark(vi.wheelConnector?.crossJoint?.status),
        wheelConnectorCrossJointResult: vi.wheelConnector?.crossJoint?.remarks,
        wheelConnectorLubeMemenuhi: getCheckmark(vi.wheelConnector?.lubrication?.status),
        wheelConnectorLubeTidakMemenuhi: getOppositeCheckmark(vi.wheelConnector?.lubrication?.status),
        wheelConnectorLubeResult: vi.wheelConnector?.lubrication?.remarks,
        girderBumperConditionMemenuhi: getCheckmark(vi.girderBumper?.condition?.status),
        girderBumperConditionTidakMemenuhi: getOppositeCheckmark(vi.girderBumper?.condition?.status),
        girderBumperConditionResult: vi.girderBumper?.condition?.remarks,
        girderBumperReinforcementMemenuhi: getCheckmark(vi.girderBumper?.reinforcement?.status),
        girderBumperReinforcementTidakMemenuhi: getOppositeCheckmark(vi.girderBumper?.reinforcement?.status),
        girderBumperReinforcementResult: vi.girderBumper?.reinforcement?.remarks,
        trolleyGearboxFasteningMemenuhi: getCheckmark(vi.trolleyGearbox?.fastening?.status),
        trolleyGearboxFasteningTidakMemenuhi: getOppositeCheckmark(vi.trolleyGearbox?.fastening?.status),
        trolleyGearboxFasteningResult: vi.trolleyGearbox?.fastening?.remarks,
        trolleyGearboxCorrosionMemenuhi: getCheckmark(vi.trolleyGearbox?.corrosion?.status),
        trolleyGearboxCorrosionTidakMemenuhi: getOppositeCheckmark(vi.trolleyGearbox?.corrosion?.status),
        trolleyGearboxCorrosionResult: vi.trolleyGearbox?.corrosion?.remarks,
        trolleyGearboxCracksMemenuhi: getCheckmark(vi.trolleyGearbox?.cracks?.status),
        trolleyGearboxCracksTidakMemenuhi: getOppositeCheckmark(vi.trolleyGearbox?.cracks?.status),
        trolleyGearboxCracksResult: vi.trolleyGearbox?.cracks?.remarks,
        trolleyGearboxLubricantMemenuhi: getCheckmark(vi.trolleyGearbox?.lubricant?.status),
        trolleyGearboxLubricantTidakMemenuhi: getOppositeCheckmark(vi.trolleyGearbox?.lubricant?.status),
        trolleyGearboxLubricantResult: vi.trolleyGearbox?.lubricant?.remarks,
        trolleyGearboxOilSealMemenuhi: getCheckmark(vi.trolleyGearbox?.oilSeal?.status),
        trolleyGearboxOilSealTidakMemenuhi: getOppositeCheckmark(vi.trolleyGearbox?.oilSeal?.status),
        trolleyGearboxOilSealResult: vi.trolleyGearbox?.oilSeal?.remarks,
        trolleyDriveWheelWearMemenuhi: getCheckmark(vi.trolleyDriveWheel?.wear?.status),
        trolleyDriveWheelWearTidakMemenuhi: getOppositeCheckmark(vi.trolleyDriveWheel?.wear?.status),
        trolleyDriveWheelWearResult: vi.trolleyDriveWheel?.wear?.remarks,
        trolleyDriveWheelCracksMemenuhi: getCheckmark(vi.trolleyDriveWheel?.cracks?.status),
        trolleyDriveWheelCracksTidakMemenuhi: getOppositeCheckmark(vi.trolleyDriveWheel?.cracks?.status),
        trolleyDriveWheelCracksResult: vi.trolleyDriveWheel?.cracks?.remarks,
        trolleyDriveWheelDeformationMemenuhi: getCheckmark(vi.trolleyDriveWheel?.deformation?.status),
        trolleyDriveWheelDeformationTidakMemenuhi: getOppositeCheckmark(vi.trolleyDriveWheel?.deformation?.status),
        trolleyDriveWheelDeformationResult: vi.trolleyDriveWheel?.deformation?.remarks,
        trolleyDriveWheelFlangeMemenuhi: getCheckmark(vi.trolleyDriveWheel?.flange?.status),
        trolleyDriveWheelFlangeTidakMemenuhi: getOppositeCheckmark(vi.trolleyDriveWheel?.flange?.status),
        trolleyDriveWheelFlangeResult: vi.trolleyDriveWheel?.flange?.remarks,
        trolleyDriveWheelChainMemenuhi: getCheckmark(vi.trolleyDriveWheel?.chain?.status),
        trolleyDriveWheelChainTidakMemenuhi: getOppositeCheckmark(vi.trolleyDriveWheel?.chain?.status),
        trolleyDriveWheelChainResult: vi.trolleyDriveWheel?.chain?.remarks,
        trolleyIdleWheelWearMemenuhi: getCheckmark(vi.trolleyIdleWheel?.wear?.status),
        trolleyIdleWheelWearTidakMemenuhi: getOppositeCheckmark(vi.trolleyIdleWheel?.wear?.status),
        trolleyIdleWheelWearResult: vi.trolleyIdleWheel?.wear?.remarks,
        trolleyIdleWheelCracksMemenuhi: getCheckmark(vi.trolleyIdleWheel?.cracks?.status),
        trolleyIdleWheelCracksTidakMemenuhi: getOppositeCheckmark(vi.trolleyIdleWheel?.cracks?.status),
        trolleyIdleWheelCracksResult: vi.trolleyIdleWheel?.cracks?.remarks,
        trolleyIdleWheelDeformationMemenuhi: getCheckmark(vi.trolleyIdleWheel?.deformation?.status),
        trolleyIdleWheelDeformationTidakMemenuhi: getOppositeCheckmark(vi.trolleyIdleWheel?.deformation?.status),
        trolleyIdleWheelDeformationResult: vi.trolleyIdleWheel?.deformation?.remarks,
        trolleyIdleWheelFlangeMemenuhi: getCheckmark(vi.trolleyIdleWheel?.flange?.status),
        trolleyIdleWheelFlangeTidakMemenuhi: getOppositeCheckmark(vi.trolleyIdleWheel?.flange?.status),
        trolleyIdleWheelFlangeResult: vi.trolleyIdleWheel?.flange?.remarks,
        trolleyWheelConnectorStraightnessMemenuhi: getCheckmark(vi.trolleyWheelConnector?.straightness?.status),
        trolleyWheelConnectorStraightnessTidakMemenuhi: getOppositeCheckmark(vi.trolleyWheelConnector?.straightness?.status),
        trolleyWheelConnectorStraightnessResult: vi.trolleyWheelConnector?.straightness?.remarks,
        trolleyWheelConnectorCrossJointMemenuhi: getCheckmark(vi.trolleyWheelConnector?.crossJoint?.status),
        trolleyWheelConnectorCrossJointTidakMemenuhi: getOppositeCheckmark(vi.trolleyWheelConnector?.crossJoint?.status),
        trolleyWheelConnectorCrossJointResult: vi.trolleyWheelConnector?.crossJoint?.remarks,
        trolleyWheelConnectorLubeMemenuhi: getCheckmark(vi.trolleyWheelConnector?.lubrication?.status),
        trolleyWheelConnectorLubeTidakMemenuhi: getOppositeCheckmark(vi.trolleyWheelConnector?.lubrication?.status),
        trolleyWheelConnectorLubeResult: vi.trolleyWheelConnector?.lubrication?.remarks,
        trolleyBumperConditionMemenuhi: getCheckmark(vi.trolleyBumper?.condition?.status),
        trolleyBumperConditionTidakMemenuhi: getOppositeCheckmark(vi.trolleyBumper?.condition?.status),
        trolleyBumperConditionResult: vi.trolleyBumper?.condition?.remarks,
        trolleyBumperReinforcementMemenuhi: getCheckmark(vi.trolleyBumper?.reinforcement?.status),
        trolleyBumperReinforcementTidakMemenuhi: getOppositeCheckmark(vi.trolleyBumper?.reinforcement?.status),
        trolleyBumperReinforcementResult: vi.trolleyBumper?.reinforcement?.remarks,
        drumGrooveMemenuhi: getCheckmark(vi.drum?.groove?.status),
        drumGrooveTidakMemenuhi: getOppositeCheckmark(vi.drum?.groove?.status),
        drumGrooveResult: vi.drum?.groove?.remarks,
        drumGrooveLipMemenuhi: getCheckmark(vi.drum?.grooveLip?.status),
        drumGrooveLipTidakMemenuhi: getOppositeCheckmark(vi.drum?.grooveLip?.status),
        drumGrooveLipResult: vi.drum?.grooveLip?.remarks,
        drumFlangesMemenuhi: getCheckmark(vi.drum?.flanges?.status),
        drumFlangesTidakMemenuhi: getOppositeCheckmark(vi.drum?.flanges?.status),
        drumFlangesResult: vi.drum?.flanges?.remarks,
        brakeWearMemenuhi: getCheckmark(vi.brakeVisual?.wear?.status),
        brakeWearTidakMemenuhi: getOppositeCheckmark(vi.brakeVisual?.wear?.status),
        brakeWearResult: vi.brakeVisual?.wear?.remarks,
        brakeAdjustmentMemenuhi: getCheckmark(vi.brakeVisual?.adjustment?.status),
        brakeAdjustmentTidakMemenuhi: getOppositeCheckmark(vi.brakeVisual?.adjustment?.status),
        brakeAdjustmentResult: vi.brakeVisual?.adjustment?.remarks,
        hoistGearboxLubeMemenuhi: getCheckmark(vi.hoistGearBox?.lubrication?.status),
        hoistGearboxLubeTidakMemenuhi: getOppositeCheckmark(vi.hoistGearBox?.lubrication?.status),
        hoistGearboxLubeResult: vi.hoistGearBox?.lubrication?.remarks,
        hoistGearboxOilSealMemenuhi: getCheckmark(vi.hoistGearBox?.oilSeal?.status),
        hoistGearboxOilSealTidakMemenuhi: getOppositeCheckmark(vi.hoistGearBox?.oilSeal?.status),
        hoistGearboxOilSealResult: vi.hoistGearBox?.oilSeal?.remarks,
        pulleyGrooveMemenuhi: getCheckmark(vi.pulleyChainSprocket?.pulleyGroove?.status),
        pulleyGrooveTidakMemenuhi: getOppositeCheckmark(vi.pulleyChainSprocket?.pulleyGroove?.status),
        pulleyGrooveResult: vi.pulleyChainSprocket?.pulleyGroove?.remarks,
        pulleyLipMemenuhi: getCheckmark(vi.pulleyChainSprocket?.pulleyLip?.status),
        pulleyLipTidakMemenuhi: getOppositeCheckmark(vi.pulleyChainSprocket?.pulleyLip?.status),
        pulleyLipResult: vi.pulleyChainSprocket?.pulleyLip?.remarks,
        pulleyPinMemenuhi: getCheckmark(vi.pulleyChainSprocket?.pulleyPin?.status),
        pulleyPinTidakMemenuhi: getOppositeCheckmark(vi.pulleyChainSprocket?.pulleyPin?.status),
        pulleyPinResult: vi.pulleyChainSprocket?.pulleyPin?.remarks,
        pulleyBearingMemenuhi: getCheckmark(vi.pulleyChainSprocket?.pulleyBearing?.status),
        pulleyBearingTidakMemenuhi: getOppositeCheckmark(vi.pulleyChainSprocket?.pulleyBearing?.status),
        pulleyBearingResult: vi.pulleyChainSprocket?.pulleyBearing?.remarks,
        pulleyGuardMemenuhi: getCheckmark(vi.pulleyChainSprocket?.pulleyGuard?.status),
        pulleyGuardTidakMemenuhi: getOppositeCheckmark(vi.pulleyChainSprocket?.pulleyGuard?.status),
        pulleyGuardResult: vi.pulleyChainSprocket?.pulleyGuard?.remarks,
        ropeChainGuardMemenuhi: getCheckmark(vi.pulleyChainSprocket?.ropeChainGuard?.status),
        ropeChainGuardTidakMemenuhi: getOppositeCheckmark(vi.pulleyChainSprocket?.ropeChainGuard?.status),
        ropeChainGuardResult: vi.pulleyChainSprocket?.ropeChainGuard?.remarks,
        mainHookWearMemenuhi: getCheckmark(vi.mainHook?.wear?.status),
        mainHookWearTidakMemenuhi: getOppositeCheckmark(vi.mainHook?.wear?.status),
        mainHookWearResult: vi.mainHook?.wear?.remarks,
        mainHookThroatOpeningMemenuhi: getCheckmark(vi.mainHook?.throatOpening?.status),
        mainHookThroatOpeningTidakMemenuhi: getOppositeCheckmark(vi.mainHook?.throatOpening?.status),
        mainHookThroatOpeningResult: vi.mainHook?.throatOpening?.remarks,
        mainHookSwivelMemenuhi: getCheckmark(vi.mainHook?.swivel?.status),
        mainHookSwivelTidakMemenuhi: getOppositeCheckmark(vi.mainHook?.swivel?.status),
        mainHookSwivelResult: vi.mainHook?.swivel?.remarks,
        mainHookTrunnionMemenuhi: getCheckmark(vi.mainHook?.trunnion?.status),
        mainHookTrunnionTidakMemenuhi: getOppositeCheckmark(vi.mainHook?.trunnion?.status),
        mainHookTrunnionResult: vi.mainHook?.trunnion?.remarks,
        auxHookWearMemenuhi: getCheckmark(vi.auxHook?.wear?.status),
        auxHookWearTidakMemenuhi: getOppositeCheckmark(vi.auxHook?.wear?.status),
        auxHookWearResult: vi.auxHook?.wear?.remarks,
        auxHookThroatOpeningMemenuhi: getCheckmark(vi.auxHook?.throatOpening?.status),
        auxHookThroatOpeningTidakMemenuhi: getOppositeCheckmark(vi.auxHook?.throatOpening?.status),
        auxHookThroatOpeningResult: vi.auxHook?.throatOpening?.remarks,
        auxHookSwivelMemenuhi: getCheckmark(vi.auxHook?.swivel?.status),
        auxHookSwivelTidakMemenuhi: getOppositeCheckmark(vi.auxHook?.swivel?.status),
        auxHookSwivelResult: vi.auxHook?.swivel?.remarks,
        auxHookTrunnionMemenuhi: getCheckmark(vi.auxHook?.trunnion?.status),
        auxHookTrunnionTidakMemenuhi: getOppositeCheckmark(vi.auxHook?.trunnion?.status),
        auxHookTrunnionResult: vi.auxHook?.trunnion?.remarks,
        mainWireRopeCorrosionMemenuhi: getCheckmark(vi.mainWireRope?.corrosion?.status),
        mainWireRopeCorrosionTidakMemenuhi: getOppositeCheckmark(vi.mainWireRope?.corrosion?.status),
        mainWireRopeCorrosionResult: vi.mainWireRope?.corrosion?.remarks,
        mainWireRopeWearMemenuhi: getCheckmark(vi.mainWireRope?.wear?.status),
        mainWireRopeWearTidakMemenuhi: getOppositeCheckmark(vi.mainWireRope?.wear?.status),
        mainWireRopeWearResult: vi.mainWireRope?.wear?.remarks,
        mainWireRopeBrokenMemenuhi: getCheckmark(vi.mainWireRope?.broken?.status),
        mainWireRopeBrokenTidakMemenuhi: getOppositeCheckmark(vi.mainWireRope?.broken?.status),
        mainWireRopeBrokenResult: vi.mainWireRope?.broken?.remarks,
        mainWireRopeDeformationMemenuhi: getCheckmark(vi.mainWireRope?.deformation?.status),
        mainWireRopeDeformationTidakMemenuhi: getOppositeCheckmark(vi.mainWireRope?.deformation?.status),
        mainWireRopeDeformationResult: vi.mainWireRope?.deformation?.remarks,
        auxWireRopeCorrosionMemenuhi: getCheckmark(vi.auxWireRope?.corrosion?.status),
        auxWireRopeCorrosionTidakMemenuhi: getOppositeCheckmark(vi.auxWireRope?.corrosion?.status),
        auxWireRopeCorrosionResult: vi.auxWireRope?.corrosion?.remarks,
        auxWireRopeWearMemenuhi: getCheckmark(vi.auxWireRope?.wear?.status),
        auxWireRopeWearTidakMemenuhi: getOppositeCheckmark(vi.auxWireRope?.wear?.status),
        auxWireRopeWearResult: vi.auxWireRope?.wear?.remarks,
        auxWireRopeBrokenMemenuhi: getCheckmark(vi.auxWireRope?.broken?.status),
        auxWireRopeBrokenTidakMemenuhi: getOppositeCheckmark(vi.auxWireRope?.broken?.status),
        auxWireRopeBrokenResult: vi.auxWireRope?.broken?.remarks,
        auxWireRopeDeformationMemenuhi: getCheckmark(vi.auxWireRope?.deformation?.status),
        auxWireRopeDeformationTidakMemenuhi: getOppositeCheckmark(vi.auxWireRope?.deformation?.status),
        auxWireRopeDeformationResult: vi.auxWireRope?.deformation?.remarks,
        mainChainCorrosionMemenuhi: getCheckmark(vi.mainChain?.corrosion?.status),
        mainChainCorrosionTidakMemenuhi: getOppositeCheckmark(vi.mainChain?.corrosion?.status),
        mainChainCorrosionResult: vi.mainChain?.corrosion?.remarks,
        mainChainWearMemenuhi: getCheckmark(vi.mainChain?.wear?.status),
        mainChainWearTidakMemenuhi: getOppositeCheckmark(vi.mainChain?.wear?.status),
        mainChainWearResult: vi.mainChain?.wear?.remarks,
        mainChainCracksBrokenMemenuhi: getCheckmark(vi.mainChain?.cracksBroken?.status),
        mainChainCracksBrokenTidakMemenuhi: getOppositeCheckmark(vi.mainChain?.cracksBroken?.status),
        mainChainCracksBrokenResult: vi.mainChain?.cracksBroken?.remarks,
        mainChainDeformationMemenuhi: getCheckmark(vi.mainChain?.deformation?.status),
        mainChainDeformationTidakMemenuhi: getOppositeCheckmark(vi.mainChain?.deformation?.status),
        mainChainDeformationResult: vi.mainChain?.deformation?.remarks,
        auxChainCorrosionMemenuhi: getCheckmark(vi.auxChain?.corrosion?.status),
        auxChainCorrosionTidakMemenuhi: getOppositeCheckmark(vi.auxChain?.corrosion?.status),
        auxChainCorrosionResult: vi.auxChain?.corrosion?.remarks,
        auxChainWearMemenuhi: getCheckmark(vi.auxChain?.wear?.status),
        auxChainWearTidakMemenuhi: getOppositeCheckmark(vi.auxChain?.wear?.status),
        auxChainWearResult: vi.auxChain?.wear?.remarks,
        auxChainCracksBrokenMemenuhi: getCheckmark(vi.auxChain?.cracksBroken?.status),
        auxChainCracksBrokenTidakMemenuhi: getOppositeCheckmark(vi.auxChain?.cracksBroken?.status),
        auxChainCracksBrokenResult: vi.auxChain?.cracksBroken?.remarks,
        auxChainDeformationMemenuhi: getCheckmark(vi.auxChain?.deformation?.status),
        auxChainDeformationTidakMemenuhi: getOppositeCheckmark(vi.auxChain?.deformation?.status),
        auxChainDeformationResult: vi.auxChain?.deformation?.remarks,
        limitSwitchLongTravelingMemenuhi: getCheckmark(vi.limitSwitch?.longTraveling?.status),
        limitSwitchLongTravelingTidakMemenuhi: getOppositeCheckmark(vi.limitSwitch?.longTraveling?.status),
        limitSwitchLongTravelingResult: vi.limitSwitch?.longTraveling?.remarks,
        limitSwitchCrossTravelingMemenuhi: getCheckmark(vi.limitSwitch?.crossTraveling?.status),
        limitSwitchCrossTravelingTidakMemenuhi: getOppositeCheckmark(vi.limitSwitch?.crossTraveling?.status),
        limitSwitchCrossTravelingResult: vi.limitSwitch?.crossTraveling?.remarks,
        limitSwitchLiftingMemenuhi: getCheckmark(vi.limitSwitch?.lifting?.status),
        limitSwitchLiftingTidakMemenuhi: getOppositeCheckmark(vi.limitSwitch?.lifting?.status),
        limitSwitchLiftingResult: vi.limitSwitch?.lifting?.remarks,
        cabinSafetyStairsMemenuhi: getCheckmark(vi.operatorCabin?.safetyStairs?.status),
        cabinSafetyStairsTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.safetyStairs?.status),
        cabinSafetyStairsResult: vi.operatorCabin?.safetyStairs?.remarks,
        cabinDoorMemenuhi: getCheckmark(vi.operatorCabin?.door?.status),
        cabinDoorTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.door?.status),
        cabinDoorResult: vi.operatorCabin?.door?.remarks,
        cabinWindowMemenuhi: getCheckmark(vi.operatorCabin?.window?.status),
        cabinWindowTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.window?.status),
        cabinWindowResult: vi.operatorCabin?.window?.remarks,
        cabinFanAcMemenuhi: getCheckmark(vi.operatorCabin?.fanAc?.status),
        cabinFanAcTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.fanAc?.status),
        cabinFanAcResult: vi.operatorCabin?.fanAc?.remarks,
        cabinControlLeversMemenuhi: getCheckmark(vi.operatorCabin?.controlLevers?.status),
        cabinControlLeversTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.controlLevers?.status),
        cabinControlLeversResult: vi.operatorCabin?.controlLevers?.remarks,
        cabinPendantControlMemenuhi: getCheckmark(vi.operatorCabin?.pendantControl?.status),
        cabinPendantControlTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.pendantControl?.status),
        cabinPendantControlResult: vi.operatorCabin?.pendantControl?.remarks,
        cabinLightingMemenuhi: getCheckmark(vi.operatorCabin?.lighting?.status),
        cabinLightingTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.lighting?.status),
        cabinLightingResult: vi.operatorCabin?.lighting?.remarks,
        cabinHornMemenuhi: getCheckmark(vi.operatorCabin?.horn?.status),
        cabinHornTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.horn?.status),
        cabinHornResult: vi.operatorCabin?.horn?.remarks,
        cabinFuseMemenuhi: getCheckmark(vi.operatorCabin?.fuse?.status),
        cabinFuseTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.fuse?.status),
        cabinFuseResult: vi.operatorCabin?.fuse?.remarks,
        cabinCommToolMemenuhi: getCheckmark(vi.operatorCabin?.commTool?.status),
        cabinCommToolTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.commTool?.status),
        cabinCommToolResult: vi.operatorCabin?.commTool?.remarks,
        cabinFireExtinguisherMemenuhi: getCheckmark(vi.operatorCabin?.fireExtinguisher?.status),
        cabinFireExtinguisherTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.fireExtinguisher?.status),
        cabinFireExtinguisherResult: vi.operatorCabin?.fireExtinguisher?.remarks,
        cabinOperatingSignsMemenuhi: getCheckmark(vi.operatorCabin?.operatingSigns?.status),
        cabinOperatingSignsTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.operatingSigns?.status),
        cabinOperatingSignsResult: vi.operatorCabin?.operatingSigns?.remarks,
        cabinMasterSwitchMemenuhi: getCheckmark(vi.operatorCabin?.masterSwitch?.status),
        cabinMasterSwitchTidakMemenuhi: getOppositeCheckmark(vi.operatorCabin?.masterSwitch?.status),
        cabinMasterSwitchResult: vi.operatorCabin?.masterSwitch?.remarks,
        electricalPanelConnectorMemenuhi: getCheckmark(vi.electricalComponents?.panelConnector?.status),
        electricalPanelConnectorTidakMemenuhi: getOppositeCheckmark(vi.electricalComponents?.panelConnector?.status),
        electricalPanelConnectorResult: vi.electricalComponents?.panelConnector?.remarks,
        electricalConductorGuardMemenuhi: getCheckmark(vi.electricalComponents?.conductorGuard?.status),
        electricalConductorGuardTidakMemenuhi: getOppositeCheckmark(vi.electricalComponents?.conductorGuard?.status),
        electricalConductorGuardResult: vi.electricalComponents?.conductorGuard?.remarks,
        electricalMotorSafetySystemMemenuhi: getCheckmark(vi.electricalComponents?.motorSafetySystem?.status),
        electricalMotorSafetySystemTidakMemenuhi: getOppositeCheckmark(vi.electricalComponents?.motorSafetySystem?.status),
        electricalMotorSafetySystemResult: vi.electricalComponents?.motorSafetySystem?.remarks,
        electricalGroundingSystemMemenuhi: getCheckmark(vi.electricalComponents?.groundingSystem?.status),
        electricalGroundingSystemTidakMemenuhi: getOppositeCheckmark(vi.electricalComponents?.groundingSystem?.status),
        electricalGroundingSystemResult: vi.electricalComponents?.groundingSystem?.remarks,
        electricalInstallationMemenuhi: getCheckmark(vi.electricalComponents?.installation?.status),
        electricalInstallationTidakMemenuhi: getOppositeCheckmark(vi.electricalComponents?.installation?.status),
        electricalInstallationResult: vi.electricalComponents?.installation?.remarks,

        // --- PEMERIKSAAN TIDAK MERUSAK (NDT) ---
        chainMethod: ndt.chain?.method,
        chainItems: (ndt.chain?.items || []).map(item => ({
            chainLocaton: item.chainLocaton,
            specDimension: item.specDimension,
            resultDimension: item.resultDimension,
            extendLengthMax: item.extendLengthMax,
            wearMax: item.wearMax,
            safetyFactor: item.safetyFactor,
            defectAda: getCheckmarkForValue(item.defectAda),
            defectTidakAda: getCheckmarkForValue(item.defectTidakAda),
            chanDesc: item.description
        })),
        mainHookMethod: ndt.mainHook?.method,
        mainHookSpecificationA: ndt.mainHook?.tolerances?.A,
        mainHookSpecificationB: ndt.mainHook?.tolerances?.B,
        mainHookSpecificationC: ndt.mainHook?.tolerances?.C,
        mainHookSpecificationD: ndt.mainHook?.tolerances?.D,
        mainHookSpecificationE: ndt.mainHook?.tolerances?.E,
        mainHookSpecificationF: ndt.mainHook?.tolerances?.F,
        mainHookSpecificationG: ndt.mainHook?.tolerances?.G,
        mainHookSpecificationH: ndt.mainHook?.tolerances?.H,
        mainHookSpecificationTrue: getCheckmark(ndt.mainHook?.result === 'Baik, tidak ditemukan cacat permukaan.'),
        mainHookSpecificationFalse: getOppositeCheckmark(ndt.mainHook?.result === 'Baik, tidak ditemukan cacat permukaan.'),
        mainHookSpecificationResult: ndt.mainHook?.result,
        mainHookMeasurementResultsA: ndt.mainHook?.measurements?.A,
        mainHookMeasurementResultsB: ndt.mainHook?.measurements?.B,
        mainHookMeasurementResultsC: ndt.mainHook?.measurements?.C,
        mainHookMeasurementResultsD: ndt.mainHook?.measurements?.D,
        mainHookMeasurementResultsE: ndt.mainHook?.measurements?.E,
        mainHookMeasurementResultsF: ndt.mainHook?.measurements?.F,
        mainHookMeasurementResultsG: ndt.mainHook?.measurements?.G,
        mainHookMeasurementResultsH: ndt.mainHook?.measurements?.H,
        mainHookMeasurementResultsTrue: getCheckmark(ndt.mainHook?.result === 'Baik, tidak ditemukan cacat permukaan.'),
        mainHookMeasurementResultsFalse: getOppositeCheckmark(ndt.mainHook?.result === 'Baik, tidak ditemukan cacat permukaan.'),
        mainHookMeasurementResultsResult: ndt.mainHook?.result,
        mainHookToleranceMeasureA: ndt.mainHook?.tolerances?.A,
        mainHookToleranceMeasureB: ndt.mainHook?.tolerances?.B,
        mainHookToleranceMeasureC: ndt.mainHook?.tolerances?.C,
        mainHookToleranceMeasureD: ndt.mainHook?.tolerances?.D,
        mainHookToleranceMeasureE: ndt.mainHook?.tolerances?.E,
        mainHookToleranceMeasureF: ndt.mainHook?.tolerances?.F,
        mainHookToleranceMeasureG: ndt.mainHook?.tolerances?.G,
        mainHookToleranceMeasureH: ndt.mainHook?.tolerances?.H,
        mainHookToleranceMeasureTrue: getCheckmark(ndt.mainHook?.result === 'Baik, tidak ditemukan cacat permukaan.'),
        mainHookToleranceMeasureFalse: getOppositeCheckmark(ndt.mainHook?.result === 'Baik, tidak ditemukan cacat permukaan.'),
        mainHookToleranceMeasureResult: ndt.mainHook?.result,
        
        // --- PENGUJIAN ---
        dynamicTestWithoutLoadTravelingShouldBe: test.dynamicTest?.withoutLoad?.[0]?.shouldBe,
        dynamicTestWithoutLoadTravelingTestedOrMeasured: test.dynamicTest?.withoutLoad?.[0]?.testedOrMeasured,
        dynamicTestWithoutLoadTravelingResult: test.dynamicTest?.withoutLoad?.[0]?.remarks,
        dynamicTestWithoutLoadTraversingShouldBe: test.dynamicTest?.withoutLoad?.[1]?.shouldBe,
        dynamicTestWithoutLoadTraversingTestedOrMeasured: test.dynamicTest?.withoutLoad?.[1]?.testedOrMeasured,
        dynamicTestWithoutLoadTraversingResult: test.dynamicTest?.withoutLoad?.[1]?.remarks,
        dynamicTestWithoutLoadHoistingShouldBe: test.dynamicTest?.withoutLoad?.[2]?.shouldBe,
        dynamicTestWithoutLoadHoistingTestedOrMeasured: test.dynamicTest?.withoutLoad?.[2]?.testedOrMeasured,
        dynamicTestWithoutLoadHoistingResult: test.dynamicTest?.withoutLoad?.[2]?.remarks,
        dynamicTestWithoutLoadSafetyLatchShouldBe: test.dynamicTest?.withoutLoad?.[3]?.shouldBe,
        dynamicTestWithoutLoadSafetyLatchTestedOrMeasured: test.dynamicTest?.withoutLoad?.[3]?.testedOrMeasured,
        dynamicTestWithoutLoadSafetyLatchResult: test.dynamicTest?.withoutLoad?.[3]?.remarks,
        dynamicTestWithoutLoadBrakeSwitchShouldBe: test.dynamicTest?.withoutLoad?.[4]?.shouldBe,
        dynamicTestWithoutLoadBrakeSwitchTestedOrMeasured: test.dynamicTest?.withoutLoad?.[4]?.testedOrMeasured,
        dynamicTestWithoutLoadBrakeSwitchResult: test.dynamicTest?.withoutLoad?.[4]?.remarks,
        dynamicTestWithoutLoadBrakeLockingShouldBe: test.dynamicTest?.withoutLoad?.[5]?.shouldBe,
        dynamicTestWithoutLoadBrakeLockingTestedOrMeasured: test.dynamicTest?.withoutLoad?.[5]?.testedOrMeasured,
        dynamicTestWithoutLoadBrakeLockingResult: test.dynamicTest?.withoutLoad?.[5]?.remarks,
        dynamicTestWithoutLoadElectricalShouldBe: test.dynamicTest?.withoutLoad?.[6]?.shouldBe,
        dynamicTestWithoutLoadElectricalTestedOrMeasured: test.dynamicTest?.withoutLoad?.[6]?.testedOrMeasured,
        dynamicTestWithoutLoadElectricalResult: test.dynamicTest?.withoutLoad?.[6]?.remarks,

        withLoadNoLoadHoist: test.dynamicTest?.withLoad?.[0]?.hoist,
        withLoadNoLoadTraversing: test.dynamicTest?.withLoad?.[0]?.traversing,
        withLoadNoLoadTraveling: test.dynamicTest?.withLoad?.[0]?.traveling,
        withLoadNoLoadBrakeSystem: test.dynamicTest?.withLoad?.[0]?.brakeSystem,
        withLoadNoLoadResult: test.dynamicTest?.withLoad?.[0]?.remarks,
        withLoad25SwlHoist: test.dynamicTest?.withLoad?.[1]?.hoist,
        withLoad25SwlTraversing: test.dynamicTest?.withLoad?.[1]?.traversing,
        withLoad25SwlTraveling: test.dynamicTest?.withLoad?.[1]?.traveling,
        withLoad25SwlBrakeSystem: test.dynamicTest?.withLoad?.[1]?.brakeSystem,
        withLoad25SwlResult: test.dynamicTest?.withLoad?.[1]?.remarks,
        withLoad50SwlHoist: test.dynamicTest?.withLoad?.[2]?.hoist,
        withLoad50SwlTraversing: test.dynamicTest?.withLoad?.[2]?.traversing,
        withLoad50SwlTraveling: test.dynamicTest?.withLoad?.[2]?.traveling,
        withLoad50SwlBrakeSystem: test.dynamicTest?.withLoad?.[2]?.brakeSystem,
        withLoad50SwlResult: test.dynamicTest?.withLoad?.[2]?.remarks,
        withLoad75SwlHoist: test.dynamicTest?.withLoad?.[3]?.hoist,
        withLoad75SwlTraversing: test.dynamicTest?.withLoad?.[3]?.traversing,
        withLoad75SwlTraveling: test.dynamicTest?.withLoad?.[3]?.traveling,
        withLoad75SwlBrakeSystem: test.dynamicTest?.withLoad?.[3]?.brakeSystem,
        withLoad75SwlResult: test.dynamicTest?.withLoad?.[3]?.remarks,
        withLoad100SwlHoist: test.dynamicTest?.withLoad?.[4]?.hoist,
        withLoad100SwlTraversing: test.dynamicTest?.withLoad?.[4]?.traversing,
        withLoad100SwlTraveling: test.dynamicTest?.withLoad?.[4]?.traveling,
        withLoad100SwlBrakeSystem: test.dynamicTest?.withLoad?.[4]?.brakeSystem,
        withLoad100SwlResult: test.dynamicTest?.withLoad?.[4]?.remarks,

        testLoadStatis: test.staticTest?.testLoad,
        singleDeflectionMeasurement: test.staticTest?.deflection?.singleGirder?.measurement,
        singleDeflectionDesc: test.staticTest?.deflection?.singleGirder?.description,
        double2DeflectionMeasurement: test.staticTest?.deflection?.doubleGirder?.measurement,
        double2DeflectionDesc: test.staticTest?.deflection?.doubleGirder?.description,
        double5DeflectionMeasurement: test.staticTest?.deflection?.doubleGirder?.measurement,
        double5DeflectionDesc: test.staticTest?.deflection?.doubleGirder?.description,
        singleGirderDesign: test.staticTest?.singleGirder?.design_mm,
        singleGirderSpan: test.staticTest?.singleGirder?.span_mm,
        resultSingleGrider: formatResultText(test.staticTest?.singleGirder?.result),
        doubleGirderDesign: test.staticTest?.doubleGirder?.design_mm,
        doubleGirderSpan: test.staticTest?.doubleGirder?.span_mm,
        resultDoubleGrider: formatResultText(test.staticTest?.doubleGirder?.result),
        noteStatis: test.staticTest?.notes,

        // --- KESIMPULAN & SARAN ---
        conslusion: data.conclusion,
        recommendations: data.recommendations,

        // --- OTORITAS INSPEKSI ---
        inspectionDate: data.inspectionDate,
    };

    try {
        doc.render(renderData);
    } catch (error) {
        console.error("Error saat rendering dokumen:", error);
        const e = {
            message: error.message,
            name: error.name,
            stack: error.stack,
            properties: error.properties,
        };
        console.log(JSON.stringify({ error: e }));
        throw new Error("Gagal mengisi data ke template.");
    }

    const docxBuffer = doc.getZip().generate({
        type: 'nodebuffer',
        compression: 'DEFLATE'
    });

    const safeOwnerName = (general.ownerName || 'UnknownOwner').replace(/[^\w\s.-]/g, '_');
    const fileName = `Laporan-OverheadCrane-${safeOwnerName}-${data.id || 'new'}.docx`;

    return { docxBuffer, fileName };
};

module.exports = {
    createLaporanOverheadCrane,
};