'use strict';

const PizZip = require('pizzip');
const Docxtemplater = require('docxtemplater');
const { Storage } = require('@google-cloud/storage');
const config = require('../../../../../config');

// Inisialisasi GCS
let privateKey = config.FIRESTORE_PRIVATE_KEY.replace(/\\n/g, '\n');
const storage = new Storage({
    projectId: config.FIRESTORE_PROJECT_ID,
    credentials: { client_email: config.FIRESTORE_CLIENT_EMAIL, private_key: privateKey },
});
const BUCKET_NAME = 'tamplate-audit-riksauji'; // Pastikan nama bucket sudah benar

// Fungsi helper untuk mendapatkan tanda centang (√) berdasarkan status boolean
const getCheckmark = (status) => (status === true ? '√' : '');
// Fungsi helper untuk mendapatkan nilai 'N/A' jika status adalah 'N/A', jika tidak biarkan kosong
const getNaValue = (value) => (value === 'N/A' ? 'N/A' : ''); 

const createLaporanGantryCrane = async (data) => {
    // Path template di GCS
    const templatePath = 'paa/gantryCrane/laporanGantryCrane.docx'; // Sesuaikan path ini jika berbeda

    let content;
    try {
        [content] = await storage.bucket(BUCKET_NAME).file(templatePath).download();
    } catch (error) {
        console.error('Gagal mengunduh template Laporan Gantry Crane:', error);
        throw new Error('Template dokumen Laporan Gantry Crane tidak dapat diakses.');
    }

    const zip = new PizZip(content);
    // Mengatur nullGetter untuk mengembalikan string kosong jika nilai null/undefined
    const doc = new Docxtemplater(zip, { paragraphLoop: true, linebreaks: true, nullGetter: () => "" });

    // Destrukturisasi data untuk kemudahan akses dan keamanan (menghindari error jika properti undefined)
    const g = data.generalData || {};
    const t = data.technicalData || {};
    const vi = data.visualInspection || {};
    const ndt = data.ndt || {};
    const dyn = data.dynamicTesting || {};
    const stat = data.staticTesting || {};

    const renderData = {
        // Data Utama (Root Level)
        examinationType: data.examinationType || '',
        inspectionType: data.inspectionType || '',
        reportNumber: data.reportNumber || '',
        equipmentType: data.equipmentType || '',

        // General Data
        companyName: g.companyName || '',
        companyLocation: g.companyLocation || '',
        usageLocation: g.usageLocation || '',
        location: g.location || '',
        manufacturerHoist: g.manufacturerHoist || '',
        manufacturerStructure: g.manufacturerStructure || '',
        brandOrType: g.brandOrType || '',
        manufactureYear: g.manufactureYear || '',
        serialNumber: g.serialNumber || '',
        maxLiftingCapacityKg: g.maxLiftingCapacityKg || '',
        usagePermitNumber: g.usagePermitNumber || '',
        operatorcertificateStatus: g.operatorcertificateStatus || '',
        technicalDataManualStatus: g.technicalDataManualStatus || '',
        inspectionDate: g.inspectionDate || '',

        // Technical Data
        liftHeight: t.liftHeight || '',
        girderLength: t.girderLength || '',
        hoistingSpeed: t.hoistingSpeed || '',
        travelingSpeed: t.travelingSpeed || '',
        traversingSpeed: t.traversingSpeed || '',
        driveMotorcapacity: t.driveMotorcapacity || '',
        hoistingpowerKw: t.hoistingpowerKw || '',
        travelingpowerKw: t.travelingpowerKw || '',
        traversingpowerKw: t.traversingpowerKw || '',
        hoistingtype: t.hoistingtype || '',
        travelingtype: t.travelingtype || '',
        traversingtype: t.traversingtype || '',
        hoistingrpm: t.hoistingrpm || '',
        travelingrpm: t.travelingrpm || '',
        traversingrpm: t.traversingrpm || '',
        hoistingvoltageV: t.hoistingvoltageV || '',
        travelingvoltageV: t.travelingvoltageV || '',
        traversingvoltageV: t.traversingvoltageV || '',
        hoistingcurrentA: t.hoistingcurrentA || '',
        travelingcurrentA: t.travelingcurrentA || '',
        traversingcurrentA: t.traversingcurrentA || '',
        hoistingfrequencyHz: t.hoistingfrequencyHz || '',
        travelingfrequencyHz: t.travelingfrequencyHz || '',
        traversingfrequencyHz: t.traversingfrequencyHz || '',
        hoistingphase: t.hoistingphase || '',
        travelingphase: t.travelingphase || '',
        traversingphase: t.traversingphase || '',
        hoistingpowerSupply: t.hoistingpowerSupply || '',
        travelingpowerSupply: t.travelingpowerSupply || '',
        traversingpowerSupply: t.traversingpowerSupply || '',
        braketype: t.braketype || '',
        brakemodel: t.brakemodel || '',
        controlBrakehoistingtype: t.controlBrakehoistingtype || '',
        controlBraketravelingtype: t.controlBraketravelingtype || '',
        controlBraketraversingtype: t.controlBraketraversingtype || '',
        controlBrakehoistingmodel: t.controlBrakehoistingmodel || '',
        controlBraketravelingmodel: t.controlBraketravelingmodel || '',
        controlBraketraversingmodel: t.controlBraketraversingmodel || '',
        hookhoistingtype: t.hookhoistingtype || '',
        hooktravelingtype: t.hooktravelingtype || '',
        hooktraversingtype: t.hooktraversingtype || '',
        hookhoistingcapacity: t.hookhoistingcapacity || '',
        hooktravelingcapacity: t.hooktravelingcapacity || '',
        hooktraversingcapacity: t.hooktraversingcapacity || '',
        hookhoistingmaterial: t.hookhoistingmaterial || '',
        hooktravelingmaterial: t.hooktravelingmaterial || '',
        hooktraversingmaterial: t.hooktraversingmaterial || '',
        wireRopeOrChainmediumType: t.wireRopeOrChainmediumType || '',
        mediumTypehoistingtype: t.mediumTypehoistingtype || '',
        mediumTypetravelingtype: t.mediumTypetravelingtype || '',
        mediumTypetraversingtype: t.mediumTypetraversingtype || '',
        mediumTypehoistingconstruction: t.mediumTypehoistingconstruction || '',
        mediumTypetravelingconstruction: t.mediumTypetravelingconstruction || '',
        mediumTypetraversingconstruction: t.mediumTypetraversingconstruction || '',
        mediumTypehoistingdiameter: t.mediumTypehoistingdiameter || '',
        mediumTypetravelingdiameter: t.mediumTypetravelingdiameter || '',
        mediumTypetraversingdiameter: t.mediumTypetraversingdiameter || '',
        mediumTypehoistinglength: t.mediumTypehoistinglength || '',
        mediumTypetravelinglength: t.mediumTypetravelinglength || '',
        mediumTypetraversinglength: t.mediumTypetraversinglength || '',

        // Visual Inspection
        // Menggunakan getCheckmark untuk kedua kolom, dengan negasi untuk kolom 'Tidak Memenuhi Syarat'
        anchorBoltscorrosionMemenuhi: getCheckmark(vi.anchorBoltscorrosionMemenuhi),
        anchorBoltscorrosionTidakMemenuhi: getCheckmark(!vi.anchorBoltscorrosionMemenuhi),
        anchorBoltscorrosionResult: vi.anchorBoltscorrosionResult || getNaValue(vi.anchorBoltscorrosionResult),
        anchorBoltscracksMemenuhi: getCheckmark(vi.anchorBoltscracksMemenuhi),
        anchorBoltscracksTidakMemenuhi: getCheckmark(!vi.anchorBoltscracksMemenuhi),
        anchorBoltscracksResult: vi.anchorBoltscracksResult || getNaValue(vi.anchorBoltscracksResult),
        anchorBoltsdeformationMemenuhi: getCheckmark(vi.anchorBoltsdeformationMemenuhi),
        anchorBoltsdeformationTidakMemenuhi: getCheckmark(!vi.anchorBoltsdeformationMemenuhi),
        anchorBoltsdeformationResult: vi.anchorBoltsdeformationResult || getNaValue(vi.anchorBoltsdeformationResult),
        anchorBoltsfasteningMemenuhi: getCheckmark(vi.anchorBoltsfasteningMemenuhi),
        anchorBoltsfasteningTidakMemenuhi: getCheckmark(!vi.anchorBoltsfasteningMemenuhi),
        anchorBoltsfasteningResult: vi.anchorBoltsfasteningResult || getNaValue(vi.anchorBoltsfasteningResult),
        columnFramecorrosionMemenuhi: getCheckmark(vi.columnFramecorrosionMemenuhi),
        columnFramecorrosionTidakMemenuhi: getCheckmark(!vi.columnFramecorrosionMemenuhi),
        columnFramecorrosionResult: vi.columnFramecorrosionResult || getNaValue(vi.columnFramecorrosionResult),
        columnFramecracksMemenuhi: getCheckmark(vi.columnFramecracksMemenuhi),
        columnFramecracksTidakMemenuhi: getCheckmark(!vi.columnFramecracksMemenuhi),
        columnFramecracksResult: vi.columnFramecracksResult || getNaValue(vi.columnFramecracksResult),
        columnFramedeformationMemenuhi: getCheckmark(vi.columnFramedeformationMemenuhi),
        columnFramedeformationTidakMemenuhi: getCheckmark(!vi.columnFramedeformationMemenuhi),
        columnFramedeformationResult: vi.columnFramedeformationResult || getNaValue(vi.columnFramedeformationResult),
        columnFramefasteningMemenuhi: getCheckmark(vi.columnFramefasteningMemenuhi),
        columnFramefasteningTidakMemenuhi: getCheckmark(!vi.columnFramefasteningMemenuhi),
        columnFramefasteningResult: vi.columnFramefasteningResult || getNaValue(vi.columnFramefasteningResult),
        columnFrametransverseReinforcementMemenuhi: getCheckmark(vi.columnFrametransverseReinforcementMemenuhi),
        columnFrametransverseReinforcementTidakMemenuhi: getCheckmark(!vi.columnFrametransverseReinforcementMemenuhi),
        columnFrametransverseReinforcementResult: vi.columnFrametransverseReinforcementResult || getNaValue(vi.columnFrametransverseReinforcementResult),
        columnFramediagonalReinforcementMemenuhi: getCheckmark(vi.columnFramediagonalReinforcementMemenuhi),
        columnFramediagonalReinforcementTidakMemenuhi: getCheckmark(!vi.columnFramediagonalReinforcementMemenuhi),
        columnFramediagonalReinforcementResult: vi.columnFramediagonalReinforcementResult || getNaValue(vi.columnFramediagonalReinforcementResult),
        laddercorrosionMemenuhi: getCheckmark(vi.laddercorrosionMemenuhi),
        laddercorrosionTidakMemenuhi: getCheckmark(!vi.laddercorrosionMemenuhi),
        laddercorrosionResult: vi.laddercorrosionResult || getNaValue(vi.laddercorrosionResult),
        laddercracksMemenuhi: getCheckmark(vi.laddercracksMemenuhi),
        laddercracksTidakMemenuhi: getCheckmark(!vi.laddercracksMemenuhi),
        laddercracksResult: vi.laddercracksResult || getNaValue(vi.laddercracksResult),
        ladderdeformationMemenuhi: getCheckmark(vi.ladderdeformationMemenuhi),
        ladderdeformationTidakMemenuhi: getCheckmark(!vi.ladderdeformationMemenuhi),
        ladderdeformationResult: vi.ladderdeformationResult || getNaValue(vi.ladderdeformationResult),
        ladderfasteningMemenuhi: getCheckmark(vi.ladderfasteningMemenuhi),
        ladderfasteningTidakMemenuhi: getCheckmark(!vi.ladderfasteningMemenuhi),
        ladderfasteningResult: vi.ladderfasteningResult || getNaValue(vi.ladderfasteningResult),
        workingFloorcorrosionMemenuhi: getCheckmark(vi.workingFloorcorrosionMemenuhi),
        workingFloorcorrosionTidakMemenuhi: getCheckmark(!vi.workingFloorcorrosionMemenuhi),
        workingFloorcorrosionResult: vi.workingFloorcorrosionResult || getNaValue(vi.workingFloorcorrosionResult),
        workingFloorcracksMemenuhi: getCheckmark(vi.workingFloorcracksMemenuhi),
        workingFloorcracksTidakMemenuhi: getCheckmark(!vi.workingFloorcracksMemenuhi),
        workingFloorcracksResult: vi.workingFloorcracksResult || getNaValue(vi.workingFloorcracksResult),
        workingFloordeformationMemenuhi: getCheckmark(vi.workingFloordeformationMemenuhi),
        workingFloordeformationTidakMemenuhi: getCheckmark(!vi.workingFloordeformationMemenuhi),
        workingFloordeformationResult: vi.workingFloordeformationResult || getNaValue(vi.workingFloordeformationResult),
        workingFloorfasteningMemenuhi: getCheckmark(vi.workingFloorfasteningMemenuhi),
        workingFloorfasteningTidakMemenuhi: getCheckmark(!vi.workingFloorfasteningMemenuhi),
        workingFloorfasteningResult: vi.workingFloorfasteningResult || getNaValue(vi.workingFloorfasteningResult),
        railSupportBeamcorrosionMemenuhi: getCheckmark(vi.railSupportBeamcorrosionMemenuhi),
        railSupportBeamcorrosionTidakMemenuhi: getCheckmark(!vi.railSupportBeamcorrosionMemenuhi),
        railSupportBeamcorrosionResult: vi.railSupportBeamcorrosionResult || getNaValue(vi.railSupportBeamcorrosionResult),
        railSupportBeamcracksMemenuhi: getCheckmark(vi.railSupportBeamcracksMemenuhi),
        railSupportBeamcracksTidakMemenuhi: getCheckmark(!vi.railSupportBeamcracksMemenuhi),
        railSupportBeamcracksResult: vi.railSupportBeamcracksResult || getNaValue(vi.railSupportBeamcracksResult),
        railSupportBeamdeformationMemenuhi: getCheckmark(vi.railSupportBeamdeformationMemenuhi),
        railSupportBeamdeformationTidakMemenuhi: getCheckmark(!vi.railSupportBeamdeformationMemenuhi),
        railSupportBeamdeformationResult: vi.railSupportBeamdeformationResult || getNaValue(vi.railSupportBeamdeformationResult),
        railSupportBeamfasteningMemenuhi: getCheckmark(vi.railSupportBeamfasteningMemenuhi),
        railSupportBeamfasteningTidakMemenuhi: getCheckmark(!vi.railSupportBeamfasteningMemenuhi),
        railSupportBeamfasteningResult: vi.railSupportBeamfasteningResult || getNaValue(vi.railSupportBeamfasteningResult),
        travelingRailcorrosionMemenuhi: getCheckmark(vi.travelingRailcorrosionMemenuhi),
        travelingRailcracksTidakMemenuhi: getCheckmark(!vi.travelingRailcracksMemenuhi),
        travelingRailcracksResult: vi.travelingRailcracksResult || getNaValue(vi.travelingRailcracksResult),
        travelingcracksMemenuhi: getCheckmark(vi.travelingcracksMemenuhi),
        travelingcracksTidakMemenuhi: getCheckmark(!vi.travelingcracksMemenuhi),
        travelingcracksResult: vi.travelingcracksResult || getNaValue(vi.travelingcracksResult),
        travelingrailConnectionMemenuhi: getCheckmark(vi.travelingrailConnectionMemenuhi),
        travelingrailConnectionTidakMemenuhi: getCheckmark(!vi.travelingrailConnectionMemenuhi),
        travelingrailConnectionResult: vi.travelingrailConnectionResult || getNaValue(vi.travelingrailConnectionResult),
        travelingrailAlignmentMemenuhi: getCheckmark(vi.travelingrailAlignmentMemenuhi),
        travelingrailAlignmentTidakMemenuhi: getCheckmark(!vi.travelingrailAlignmentMemenuhi),
        travelingrailAlignmentResult: vi.travelingrailAlignmentResult || getNaValue(vi.travelingrailAlignmentResult),
        travelinginterRailAlignmentMemenuhi: getCheckmark(vi.travelinginterRailAlignmentMemenuhi),
        travelinginterRailAlignmentTidakMemenuhi: getCheckmark(!vi.travelinginterRailAlignmentMemenuhi),
        travelinginterRailAlignmentResult: vi.travelinginterRailAlignmentResult || getNaValue(vi.travelinginterRailAlignmentResult),
        travelinginterRailFlatnessMemenuhi: getCheckmark(vi.travelinginterRailFlatnessMemenuhi),
        travelinginterRailFlatnessTidakMemenuhi: getCheckmark(!vi.travelinginterRailFlatnessMemenuhi),
        travelinginterRailFlatnessResult: vi.travelinginterRailFlatnessResult || getNaValue(vi.travelinginterRailFlatnessResult),
        travelingrailConnectionGapMemenuhi: getCheckmark(vi.travelingrailConnectionGapMemenuhi),
        travelingrailConnectionGapTidakMemenuhi: getCheckmark(!vi.travelingrailConnectionGapMemenuhi),
        travelingrailConnectionGapResult: vi.travelingrailConnectionGapResult || getNaValue(vi.travelingrailConnectionGapResult),
        travelingrailFastenerMemenuhi: getCheckmark(vi.travelingrailFastenerMemenuhi),
        travelingrailFastenerTidakMemenuhi: getCheckmark(!vi.travelingrailFastenerMemenuhi),
        travelingrailFastenerResult: vi.travelingrailFastenerResult || getNaValue(vi.travelingrailFastenerResult),
        travelingrailStopperMemenuhi: getCheckmark(vi.travelingrailStopperMemenuhi),
        travelingrailStopperTidakMemenuhi: getCheckmark(!vi.travelingrailStopperMemenuhi),
        travelingrailStopperResult: vi.travelingrailStopperResult || getNaValue(vi.travelingrailStopperResult),
        traversingRailcorrosionMemenuhi: getCheckmark(vi.traversingRailcorrosionMemenuhi),
        traversingRailcorrosionTidakMemenuhi: getCheckmark(!vi.traversingRailcorrosionMemenuhi),
        traversingRailcorrosionResult: vi.traversingRailcorrosionResult || getNaValue(vi.traversingRailcorrosionResult),
        traversingRailcracksMemenuhi: getCheckmark(vi.traversingRailcracksMemenuhi),
        traversingRailcracksTidakMemenuhi: getCheckmark(!vi.traversingRailcracksMemenuhi),
        traversingRailcracksResult: vi.traversingRailcracksResult || getNaValue(vi.traversingRailcracksResult),
        traversingRailrailConnectionMemenuhi: getCheckmark(vi.traversingRailrailConnectionMemenuhi),
        traversingRailrailConnectionTidakMemenuhi: getCheckmark(!vi.traversingRailrailConnectionMemenuhi),
        traversingRailrailConnectionResult: vi.traversingRailrailConnectionResult || getNaValue(vi.traversingRailrailConnectionResult),
        traversingRailrailAlignmentMemenuhi: getCheckmark(vi.traversingRailrailAlignmentMemenuhi),
        traversingRailrailAlignmentTidakMemenuhi: getCheckmark(!vi.traversingRailrailAlignmentMemenuhi),
        traversingRailrailAlignmentResult: vi.traversingRailrailAlignmentResult || getNaValue(vi.traversingRailrailAlignmentResult),
        traversingRailinterRailAlignmentMemenuhi: getCheckmark(vi.traversingRailinterRailAlignmentMemenuhi),
        traversingRailinterRailAlignmentTidakMemenuhi: getCheckmark(!vi.traversingRailinterRailAlignmentMemenuhi),
        traversingRailinterRailAlignmentResult: vi.traversingRailinterRailAlignmentResult || getNaValue(vi.traversingRailinterRailAlignmentResult),
        traversingRailinterRailFlatnessMemenuhi: getCheckmark(vi.traversingRailinterRailFlatnessMemenuhi),
        traversingRailinterRailFlatnessTidakMemenuhi: getCheckmark(!vi.traversingRailinterRailFlatnessMemenuhi),
        traversingRailinterRailFlatnessResult: vi.traversingRailinterRailFlatnessResult || getNaValue(vi.traversingRailinterRailFlatnessResult),
        traversingRailrailConnectionGapMemenuhi: getCheckmark(vi.traversingRailrailConnectionGapMemenuhi),
        traversingRailrailConnectionGapTidakMemenuhi: getCheckmark(!vi.traversingRailrailConnectionGapMemenuhi),
        traversingRailrailConnectionGapResult: vi.traversingRailrailConnectionGapResult || getNaValue(vi.traversingRailrailConnectionGapResult),
        traversingRailrailFastenerMemenuhi: getCheckmark(vi.traversingRailrailFastenerMemenuhi),
        traversingRailrailFastenerTidakMemenuhi: getCheckmark(!vi.traversingRailrailFastenerMemenuhi),
        traversingRailrailFastenerResult: vi.traversingRailrailFastenerResult || getNaValue(vi.traversingRailrailFastenerResult),
        traversingRailrailStopperMemenuhi: getCheckmark(vi.traversingRailrailStopperMemenuhi),
        traversingRailrailStopperTidakMemenuhi: getCheckmark(!vi.traversingRailrailStopperMemenuhi),
        traversingRailrailStopperResult: vi.traversingRailrailStopperResult || getNaValue(vi.traversingRailrailStopperResult),
        girdercorrosionMemenuhi: getCheckmark(vi.girdercorrosionMemenuhi),
        girdercorrosionTidakMemenuhi: getCheckmark(!vi.girdercorrosionMemenuhi),
        girdercorrosionResult: vi.girdercorrosionResult || getNaValue(vi.girdercorrosionResult),
        girdercracksMemenuhi: getCheckmark(vi.girdercracksMemenuhi),
        girdercracksTidakMemenuhi: getCheckmark(!vi.girdercracksMemenuhi),
        girdercracksResult: vi.girdercracksResult || getNaValue(vi.girdercracksResult),
        girdercamberMemenuhi: getCheckmark(vi.girdercamberMemenuhi),
        girdercamberTidakMemenuhi: getCheckmark(!vi.girdercamberMemenuhi),
        girdercamberResult: vi.girdercamberResult || getNaValue(vi.girdercamberResult),
        girderConnectionMemenuhi: getCheckmark(vi.girderConnectionMemenuhi),
        girderConnectionTidakMemenuhi: getCheckmark(!vi.girderConnectionMemenuhi),
        girderConnectionResult: vi.girderConnectionResult || getNaValue(vi.girderConnectionResult),
        girderendGirderConnectionMemenuhi: getCheckmark(vi.girderendGirderConnectionMemenuhi),
        girderendGirderConnectionTidakMemenuhi: getCheckmark(!vi.girderendGirderConnectionMemenuhi),
        girderendGirderConnectionResult: vi.girderendGirderConnectionResult || getNaValue(vi.girderendGirderConnectionResult),
        girdertruckMountingOnGirderMemenuhi: getCheckmark(vi.girdertruckMountingOnGirderMemenuhi),
        girdertruckMountingOnGirderTidakMemenuhi: getCheckmark(!vi.girdertruckMountingOnGirderMemenuhi),
        girdertruckMountingOnGirderResult: vi.girdertruckMountingOnGirderResult || getNaValue(vi.girdertruckMountingOnGirderResult),
        travelingGearboxcorrosionMemenuhi: getCheckmark(vi.travelingGearboxcorrosionMemenuhi),
        travelingGearboxcorrosionTidakMemenuhi: getCheckmark(!vi.travelingGearboxcorrosionMemenuhi),
        travelingGearboxcorrosionResult: vi.travelingGearboxcorrosionResult || getNaValue(vi.travelingGearboxcorrosionResult),
        travelingGearboxcracksMemenuhi: getCheckmark(vi.travelingGearboxcracksMemenuhi),
        travelingGearboxcracksTidakMemenuhi: getCheckmark(!vi.travelingGearboxcracksMemenuhi),
        travelingGearboxcracksResult: vi.travelingGearboxcracksResult || getNaValue(vi.travelingGearboxcracksResult),
        travelingGearboxlubricatingOilMemenuhi: getCheckmark(vi.travelingGearboxlubricatingOilMemenuhi),
        travelingGearboxlubricatingOilTidakMemenuhi: getCheckmark(!vi.travelingGearboxlubricatingOilMemenuhi),
        travelingGearboxlubricatingOilResult: vi.travelingGearboxlubricatingOilResult || getNaValue(vi.travelingGearboxlubricatingOilResult),
        travelingGearboxoilSealMemenuhi: getCheckmark(vi.travelingGearboxoilSealMemenuhi),
        travelingGearboxoilSealTidakMemenuhi: getCheckmark(!vi.travelingGearboxoilSealMemenuhi),
        travelingGearboxoilSealResult: vi.travelingGearboxoilSealResult || getNaValue(vi.travelingGearboxoilSealResult),
        driveWheelswearMemenuhi: getCheckmark(vi.driveWheelswearMemenuhi),
        driveWheelswearTidakMemenuhi: getCheckmark(!vi.driveWheelswearMemenuhi),
        driveWheelswearResult: vi.driveWheelswearResult || getNaValue(vi.driveWheelswearResult),
        driveWheelscracksMemenuhi: getCheckmark(vi.driveWheelscracksMemenuhi),
        driveWheelscracksTidakMemenuhi: getCheckmark(!vi.driveWheelscracksMemenuhi),
        driveWheelscracksResult: vi.driveWheelscracksResult || getNaValue(vi.driveWheelscracksResult),
        driveWheelsdeformationMemenuhi: getCheckmark(vi.driveWheelsdeformationMemenuhi),
        driveWheelsdeformationTidakMemenuhi: getCheckmark(!vi.driveWheelsdeformationMemenuhi),
        driveWheelsdeformationResult: vi.driveWheelsdeformationResult || getNaValue(vi.driveWheelsdeformationResult),
        driveWheelsflangeConditionMemenuhi: getCheckmark(vi.driveWheelsflangeConditionMemenuhi),
        driveWheelsflangeConditionTidakMemenuhi: getCheckmark(!vi.driveWheelsflangeConditionMemenuhi),
        driveWheelsflangeConditionResult: vi.driveWheelsflangeConditionResult || getNaValue(vi.driveWheelsflangeConditionResult),
        driveWheelschainConditionMemenuhi: getCheckmark(vi.driveWheelschainConditionMemenuhi),
        driveWheelschainConditionTidakMemenuhi: getCheckmark(!vi.driveWheelschainConditionMemenuhi),
        driveWheelschainConditionResult: vi.driveWheelschainConditionResult || getNaValue(vi.driveWheelschainConditionResult),
        idleWheelssafetyMemenuhi: getCheckmark(vi.idleWheelssafetyMemenuhi),
        idleWheelssafetyTidakMemenuhi: getCheckmark(!vi.idleWheelssafetyMemenuhi),
        idleWheelssafetyResult: vi.idleWheelssafetyResult || getNaValue(vi.idleWheelssafetyResult),
        idleWheelscracksMemenuhi: getCheckmark(vi.idleWheelscracksMemenuhi),
        idleWheelscracksTidakMemenuhi: getCheckmark(!vi.idleWheelscracksMemenuhi),
        idleWheelscracksResult: vi.idleWheelscracksResult || getNaValue(vi.idleWheelscracksResult),
        idleWheelsdeformationMemenuhi: getCheckmark(vi.idleWheelsdeformationMemenuhi),
        idleWheelsdeformationTidakMemenuhi: getCheckmark(!vi.idleWheelsdeformationMemenuhi),
        idleWheelsdeformationResult: vi.idleWheelsdeformationResult || getNaValue(vi.idleWheelsdeformationResult),
        idleWheelsflangeConditionMemenuhi: getCheckmark(vi.idleWheelsflangeConditionMemenuhi),
        idleWheelsflangeConditionTidakMemenuhi: getCheckmark(!vi.idleWheelsflangeConditionMemenuhi),
        idleWheelsflangeConditionResult: vi.idleWheelsflangeConditionResult || getNaValue(vi.idleWheelsflangeConditionResult),
        wheelConnectoralignmentMemenuhi: getCheckmark(vi.wheelConnectoralignmentMemenuhi),
        wheelConnectoralignmentTidakMemenuhi: getCheckmark(!vi.wheelConnectoralignmentMemenuhi),
        wheelConnectoralignmentResult: vi.wheelConnectoralignmentResult || getNaValue(vi.wheelConnectoralignmentResult),
        wheelConnectorcrossJointMemenuhi: getCheckmark(vi.wheelConnectorcrossJointMemenuhi),
        wheelConnectorcrossJointTidakMemenuhi: getCheckmark(!vi.wheelConnectorcrossJointMemenuhi),
        wheelConnectorcrossJointResult: vi.wheelConnectorcrossJointResult || getNaValue(vi.wheelConnectorcrossJointResult),
        wheelConnectorlubricationMemenuhi: getCheckmark(vi.wheelConnectorlubricationMemenuhi),
        wheelConnectorlubricationTidakMemenuhi: getCheckmark(!vi.wheelConnectorlubricationMemenuhi),
        wheelConnectorlubricationResult: vi.wheelConnectorlubricationResult || getNaValue(vi.wheelConnectorlubricationResult),
        girderStopperconditionMemenuhi: getCheckmark(vi.girderStopperconditionMemenuhi),
        girderStopperconditionTidakMemenuhi: getCheckmark(!vi.girderStopperconditionMemenuhi),
        girderStopperconditionResult: vi.girderStopperconditionResult || getNaValue(vi.girderStopperconditionResult),
        girderStopperreinforcementMemenuhi: getCheckmark(vi.girderStopperreinforcementMemenuhi),
        girderStopperreinforcementTidakMemenuhi: getCheckmark(!vi.girderStopperreinforcementMemenuhi),
        girderStopperreinforcementResult: vi.girderStopperreinforcementResult || getNaValue(vi.girderStopperreinforcementResult),
        trolleyTraversingGearboxfasteningMemenuhi: getCheckmark(vi.trolleyTraversingGearboxfasteningMemenuhi),
        trolleyTraversingGearboxfasteningTidakMemenuhi: getCheckmark(!vi.trolleyTraversingGearboxfasteningMemenuhi),
        trolleyTraversingGearboxfasteningResult: vi.trolleyTraversingGearboxfasteningResult || getNaValue(vi.trolleyTraversingGearboxfasteningResult),
        trolleyTraversingGearboxcorrosionMemenuhi: getCheckmark(vi.trolleyTraversingGearboxcorrosionMemenuhi),
        trolleyTraversingGearboxcorrosionTidakMemenuhi: getCheckmark(!vi.trolleyTraversingGearboxcorrosionMemenuhi),
        trolleyTraversingGearboxcorrosionResult: vi.trolleyTraversingGearboxcorrosionResult || getNaValue(vi.trolleyTraversingGearboxcorrosionResult),
        trolleyTraversingGearboxcracksMemenuhi: getCheckmark(vi.trolleyTraversingGearboxcracksMemenuhi),
        trolleyTraversingGearboxcracksTidakMemenuhi: getCheckmark(!vi.trolleyTraversingGearboxcracksMemenuhi),
        trolleyTraversingGearboxcracksResult: vi.trolleyTraversingGearboxcracksResult || getNaValue(vi.trolleyTraversingGearboxcracksResult),
        trolleyTraversingGearboxlubricatingOilMemenuhi: getCheckmark(vi.trolleyTraversingGearboxlubricatingOilMemenuhi),
        trolleyTraversingGearboxlubricatingOilTidakMemenuhi: getCheckmark(!vi.trolleyTraversingGearboxlubricatingOilMemenuhi),
        trolleyTraversingGearboxlubricatingOilResult: vi.trolleyTraversingGearboxlubricatingOilResult || getNaValue(vi.trolleyTraversingGearboxlubricatingOilResult),
        trolleyTraversingGearboxoilSealMemenuhi: getCheckmark(vi.trolleyTraversingGearboxoilSealMemenuhi),
        trolleyTraversingGearboxoilSealTidakMemenuhi: getCheckmark(!vi.trolleyTraversingGearboxoilSealMemenuhi),
        trolleyTraversingGearboxoilSealResult: vi.trolleyTraversingGearboxoilSealResult || getNaValue(vi.trolleyTraversingGearboxoilSealResult),
        trolleyDriveWheelswearMemenuhi: getCheckmark(vi.trolleyDriveWheelswearMemenuhi),
        trolleyDriveWheelswearTidakMemenuhi: getCheckmark(!vi.trolleyDriveWheelswearMemenuhi),
        trolleyDriveWheelswearResult: vi.trolleyDriveWheelswearResult || getNaValue(vi.trolleyDriveWheelswearResult),
        trolleyDriveWheelscracksMemenuhi: getCheckmark(vi.trolleyDriveWheelscracksMemenuhi),
        trolleyDriveWheelscracksTidakMemenuhi: getCheckmark(!vi.trolleyDriveWheelscracksMemenuhi),
        trolleyDriveWheelscracksResult: vi.trolleyDriveWheelscracksResult || getNaValue(vi.trolleyDriveWheelscracksResult),
        trolleyDriveWheelsdeformationMemenuhi: getCheckmark(vi.trolleyDriveWheelsdeformationMemenuhi),
        trolleyDriveWheelsdeformationTidakMemenuhi: getCheckmark(!vi.trolleyDriveWheelsdeformationMemenuhi),
        trolleyDriveWheelsdeformationResult: vi.trolleyDriveWheelsdeformationResult || getNaValue(vi.trolleyDriveWheelsdeformationResult),
        trolleyDriveWheelsflangeConditionMemenuhi: getCheckmark(vi.trolleyDriveWheelsflangeConditionMemenuhi),
        trolleyDriveWheelsflangeConditionTidakMemenuhi: getCheckmark(!vi.trolleyDriveWheelsflangeConditionMemenuhi),
        trolleyDriveWheelsflangeConditionResult: vi.trolleyDriveWheelsflangeConditionResult || getNaValue(vi.trolleyDriveWheelsflangeConditionResult),
        trolleyDriveWheelschainConditionMemenuhi: getCheckmark(vi.trolleyDriveWheelschainConditionMemenuhi),
        trolleyDriveWheelschainConditionTidakMemenuhi: getCheckmark(!vi.trolleyDriveWheelschainConditionMemenuhi),
        trolleyDriveWheelschainConditionResult: vi.trolleyDriveWheelschainConditionResult || getNaValue(vi.trolleyDriveWheelschainConditionResult),
        trolleyIdleWheelswearMemenuhi: getCheckmark(vi.trolleyIdleWheelswearMemenuhi),
        trolleyIdleWheelswearTidakMemenuhi: getCheckmark(!vi.trolleyIdleWheelswearMemenuhi),
        trolleyIdleWheelswearResult: vi.trolleyIdleWheelswearResult || getNaValue(vi.trolleyIdleWheelswearResult),
        trolleyIdleWheelscracksMemenuhi: getCheckmark(vi.trolleyIdleWheelscracksMemenuhi),
        trolleyIdleWheelscracksTidakMemenuhi: getCheckmark(!vi.trolleyIdleWheelscracksMemenuhi),
        trolleyIdleWheelscracksResult: vi.trolleyIdleWheelscracksResult || getNaValue(vi.trolleyIdleWheelscracksResult),
        trolleyIdleWheelsdeformationMemenuhi: getCheckmark(vi.trolleyIdleWheelsdeformationMemenuhi),
        trolleyIdleWheelsdeformationTidakMemenuhi: getCheckmark(!vi.trolleyIdleWheelsdeformationMemenuhi),
        trolleyIdleWheelsdeformationResult: vi.trolleyIdleWheelsdeformationResult || getNaValue(vi.trolleyIdleWheelsdeformationResult),
        trolleyIdleWheelsflangeConditionMemenuhi: getCheckmark(vi.trolleyIdleWheelsflangeConditionMemenuhi),
        trolleyIdleWheelsflangeConditionTidakMemenuhi: getCheckmark(!vi.trolleyIdleWheelsflangeConditionMemenuhi),
        trolleyIdleWheelsflangeConditionResult: vi.trolleyIdleWheelsflangeConditionResult || getNaValue(vi.trolleyIdleWheelsflangeConditionResult),
        trolleyWheelConnectoralignmentMemenuhi: getCheckmark(vi.trolleyWheelConnectoralignmentMemenuhi),
        trolleyWheelConnectoralignmentTidakMemenuhi: getCheckmark(!vi.trolleyWheelConnectoralignmentMemenuhi),
        trolleyWheelConnectoralignmentResult: vi.trolleyWheelConnectoralignmentResult || getNaValue(vi.trolleyWheelConnectoralignmentResult),
        trolleyWheelConnectorcrossJointMemenuhi: getCheckmark(vi.trolleyWheelConnectorcrossJointMemenuhi),
        trolleyWheelConnectorcrossJointTidakMemenuhi: getCheckmark(!vi.trolleyWheelConnectorcrossJointMemenuhi),
        trolleyWheelConnectorcrossJointResult: vi.trolleyWheelConnectorcrossJointResult || getNaValue(vi.trolleyWheelConnectorcrossJointResult),
        trolleyWheelConnectorlubricationMemenuhi: getCheckmark(vi.trolleyWheelConnectorlubricationMemenuhi),
        trolleyWheelConnectorlubricationTidakMemenuhi: getCheckmark(!vi.trolleyWheelConnectorlubricationMemenuhi),
        trolleyWheelConnectorlubricationResult: vi.trolleyWheelConnectorlubricationResult || getNaValue(vi.trolleyWheelConnectorlubricationResult),
        trolleyGirderStopperconditionMemenuhi: getCheckmark(vi.trolleyGirderStopperconditionMemenuhi),
        trolleyGirderStopperconditionTidakMemenuhi: getCheckmark(!vi.trolleyGirderStopperconditionMemenuhi),
        trolleyGirderStopperconditionResult: vi.trolleyGirderStopperconditionResult || getNaValue(vi.trolleyGirderStopperconditionResult),
        trolleyGirderStopperreinforcementMemenuhi: getCheckmark(vi.trolleyGirderStopperreinforcementMemenuhi),
        trolleyGirderStopperreinforcementTidakMemenuhi: getCheckmark(!vi.trolleyGirderStopperreinforcementMemenuhi),
        trolleyGirderStopperreinforcementResult: vi.trolleyGirderStopperreinforcementResult || getNaValue(vi.trolleyGirderStopperreinforcementResult),
        windingDrumgrooveMemenuhi: getCheckmark(vi.windingDrumgrooveMemenuhi),
        windingDrumgrooveTidakMemenuhi: getCheckmark(!vi.windingDrumgrooveMemenuhi),
        windingDrumgrooveResult: vi.windingDrumgrooveResult || getNaValue(vi.windingDrumgrooveResult),
        windingDrumgrooveLipMemenuhi: getCheckmark(vi.windingDrumgrooveLipMemenuhi),
        windingDrumgrooveLipTidakMemenuhi: getCheckmark(!vi.windingDrumgrooveLipMemenuhi),
        windingDrumgrooveLipResult: vi.windingDrumgrooveLipResult || getNaValue(vi.windingDrumgrooveLipResult),
        windingDrumflangesMemenuhi: getCheckmark(vi.windingDrumflangesMemenuhi),
        windingDrumflangesTidakMemenuhi: getCheckmark(!vi.windingDrumflangesMemenuhi),
        windingDrumflangesResult: vi.windingDrumflangesResult || getNaValue(vi.windingDrumflangesResult),
        visualBrakeInspectionwearMemenuhi: getCheckmark(vi.visualBrakeInspectionwearMemenuhi),
        visualBrakeInspectionwearTidakMemenuhi: getCheckmark(!vi.visualBrakeInspectionwearMemenuhi),
        visualBrakeInspectionwearResult: vi.visualBrakeInspectionwearResult || getNaValue(vi.visualBrakeInspectionwearResult),
        visualBrakeInspectionadjustmentMemenuhi: getCheckmark(vi.visualBrakeInspectionadjustmentMemenuhi),
        visualBrakeInspectionadjustmentTidakMemenuhi: getCheckmark(!vi.visualBrakeInspectionadjustmentMemenuhi),
        visualBrakeInspectionadjustmentResult: vi.visualBrakeInspectionadjustmentResult || getNaValue(vi.visualBrakeInspectionadjustmentResult),
        hoistGearboxlubricationMemenuhi: getCheckmark(vi.hoistGearboxlubricationMemenuhi),
        hoistGearboxlubricationTidakMemenuhi: getCheckmark(!vi.hoistGearboxlubricationMemenuhi),
        hoistGearboxlubricationResult: vi.hoistGearboxlubricationResult || getNaValue(vi.hoistGearboxlubricationResult),
        hoistGearboxoilSealMemenuhi: getCheckmark(vi.hoistGearboxoilSealMemenuhi),
        hoistGearboxoilSealTidakMemenuhi: getCheckmark(!vi.hoistGearboxoilSealMemenuhi),
        hoistGearboxoilSealResult: vi.hoistGearboxoilSealResult || getNaValue(vi.hoistGearboxoilSealResult),
        pulleySprocketpulleyGrooveMemenuhi: getCheckmark(vi.pulleySprocketpulleyGrooveMemenuhi),
        pulleySprocketpulleyGrooveTidakMemenuhi: getCheckmark(!vi.pulleySprocketpulleyGrooveMemenuhi),
        pulleySprocketpulleyGrooveResult: vi.pulleySprocketpulleyGrooveResult || getNaValue(vi.pulleySprocketpulleyGrooveResult),
        pulleySprocketpulleyLipMemenuhi: getCheckmark(vi.pulleySprocketpulleyLipMemenuhi),
        pulleySprocketpulleyLipTidakMemenuhi: getCheckmark(!vi.pulleySprocketpulleyLipMemenuhi),
        pulleySprocketpulleyLipResult: vi.pulleySprocketpulleyLipResult || getNaValue(vi.pulleySprocketpulleyLipResult),
        pulleySprocketpulleyPinMemenuhi: getCheckmark(vi.pulleySprocketpulleyPinMemenuhi),
        pulleySprocketpulleyPinTidakMemenuhi: getCheckmark(!vi.pulleySprocketpulleyPinMemenuhi),
        pulleySprocketpulleyPinResult: vi.pulleySprocketpulleyPinResult || getNaValue(vi.pulleySprocketpulleyPinResult),
        pulleySprocketbearingMemenuhi: getCheckmark(vi.pulleySprocketbearingMemenuhi),
        pulleySprocketbearingTidakMemenuhi: getCheckmark(!vi.pulleySprocketbearingMemenuhi),
        pulleySprocketbearingResult: vi.pulleySprocketbearingResult || getNaValue(vi.pulleySprocketbearingResult),
        pulleySprocketpulleyGuardMemenuhi: getCheckmark(vi.pulleySprocketpulleyGuardMemenuhi),
        pulleySprocketpulleyGuardTidakMemenuhi: getCheckmark(!vi.pulleySprocketpulleyGuardMemenuhi),
        pulleySprocketpulleyGuardResult: vi.pulleySprocketpulleyGuardResult || getNaValue(vi.pulleySprocketpulleyGuardResult),
        pulleySprocketropeChainGuardMemenuhi: getCheckmark(vi.pulleySprocketropeChainGuardMemenuhi),
        pulleySprocketropeChainGuardTidakMemenuhi: getCheckmark(!vi.pulleySprocketropeChainGuardMemenuhi),
        pulleySprocketropeChainGuardResult: vi.pulleySprocketropeChainGuardResult || getNaValue(vi.pulleySprocketropeChainGuardResult),
        mainHookInspectionwearMemenuhi: getCheckmark(vi.mainHookInspectionwearMemenuhi),
        mainHookInspectionwearTidakMemenuhi: getCheckmark(!vi.mainHookInspectionwearMemenuhi),
        mainHookInspectionwearResult: vi.mainHookInspectionwearResult || getNaValue(vi.mainHookInspectionwearResult),
        mainHookInspectionhookOpeningGapMemenuhi: getCheckmark(vi.mainHookInspectionhookOpeningGapMemenuhi),
        mainHookInspectionhookOpeningGapTidakMemenuhi: getCheckmark(!vi.mainHookInspectionhookOpeningGapMemenuhi),
        mainHookInspectionhookOpeningGapResult: vi.mainHookInspectionhookOpeningGapResult || getNaValue(vi.mainHookInspectionhookOpeningGapResult),
        mainHookInspectionswivelNutAndBearingMemenuhi: getCheckmark(vi.mainHookInspectionswivelNutAndBearingMemenuhi),
        mainHookInspectionswivelNutAndBearingTidakMemenuhi: getCheckmark(!vi.mainHookInspectionswivelNutAndBearingMemenuhi),
        mainHookInspectionswivelNutAndBearingResult: vi.mainHookInspectionswivelNutAndBearingResult || getNaValue(vi.mainHookInspectionswivelNutAndBearingResult),
        mainHookInspectiontrunnionMemenuhi: getCheckmark(vi.mainHookInspectiontrunnionMemenuhi),
        mainHookInspectiontrunnionTidakMemenuhi: getCheckmark(!vi.mainHookInspectiontrunnionMemenuhi),
        mainHookInspectiontrunnionResult: vi.mainHookInspectiontrunnionResult || getNaValue(vi.mainHookInspectiontrunnionResult),
        auxiliaryHookInspectionwearMemenuhi: getCheckmark(vi.auxiliaryHookInspectionwearMemenuhi),
        auxiliaryHookInspectionwearTidakMemenuhi: getCheckmark(!vi.auxiliaryHookInspectionwearMemenuhi),
        auxiliaryHookInspectionwearResult: vi.auxiliaryHookInspectionwearResult || getNaValue(vi.auxiliaryHookInspectionwearResult),
        auxiliaryHookInspectionhookOpeningGapMemenuhi: getCheckmark(vi.auxiliaryHookInspectionhookOpeningGapMemenuhi),
        auxiliaryHookInspectionhookOpeningGapTidakMemenuhi: getCheckmark(!vi.auxiliaryHookInspectionhookOpeningGapMemenuhi),
        auxiliaryHookInspectionhookOpeningGapResult: vi.auxiliaryHookInspectionhookOpeningGapResult || getNaValue(vi.auxiliaryHookInspectionhookOpeningGapResult),
        auxiliaryHookInspectionswivelNutAndBearingMemenuhi: getCheckmark(vi.auxiliaryHookInspectionswivelNutAndBearingMemenuhi),
        auxiliaryHookInspectionswivelNutAndBearingTidakMemenuhi: getCheckmark(!vi.auxiliaryHookInspectionswivelNutAndBearingMemenuhi),
        auxiliaryHookInspectionswivelNutAndBearingResult: vi.auxiliaryHookInspectionswivelNutAndBearingResult || getNaValue(vi.auxiliaryHookInspectionswivelNutAndBearingResult),
        auxiliaryHookInspectiontrunnionMemenuhi: getCheckmark(vi.auxiliaryHookInspectiontrunnionMemenuhi),
        auxiliaryHookInspectiontrunnionTidakMemenuhi: getCheckmark(!vi.auxiliaryHookInspectiontrunnionMemenuhi),
        auxiliaryHookInspectiontrunnionResult: vi.auxiliaryHookInspectiontrunnionResult || getNaValue(vi.auxiliaryHookInspectiontrunnionResult),
        mainWireRopeInspectioncorrosionMemenuhi: getCheckmark(vi.mainWireRopeInspectioncorrosionMemenuhi),
        mainWireRopeInspectioncorrosionTidakMemenuhi: getCheckmark(!vi.mainWireRopeInspectioncorrosionMemenuhi),
        mainWireRopeInspectioncorrosionResult: vi.mainWireRopeInspectioncorrosionResult || getNaValue(vi.mainWireRopeInspectioncorrosionResult),
        mainWireRopeInspectionwearMemenuhi: getCheckmark(vi.mainWireRopeInspectionwearMemenuhi),
        mainWireRopeInspectionwearTidakMemenuhi: getCheckmark(!vi.mainWireRopeInspectionwearMemenuhi),
        mainWireRopeInspectionwearResult: vi.mainWireRopeInspectionwearResult || getNaValue(vi.mainWireRopeInspectionwearResult),
        mainWireRopeInspectionbreakageMemenuhi: getCheckmark(vi.mainWireRopeInspectionbreakageMemenuhi),
        mainWireRopeInspectionbreakageTidakMemenuhi: getCheckmark(!vi.mainWireRopeInspectionbreakageMemenuhi),
        mainWireRopeInspectionbreakageResult: vi.mainWireRopeInspectionbreakageResult || getNaValue(vi.mainWireRopeInspectionbreakageResult),
        mainWireRopeInspectiondeformationMemenuhi: getCheckmark(vi.mainWireRopeInspectiondeformationMemenuhi),
        mainWireRopeInspectiondeformationTidakMemenuhi: getCheckmark(!vi.mainWireRopeInspectiondeformationMemenuhi),
        mainWireRopeInspectiondeformationResult: vi.mainWireRopeInspectiondeformationResult || getNaValue(vi.mainWireRopeInspectiondeformationResult),
        auxiliaryWireRopeInspectioncorrosionMemenuhi: getCheckmark(vi.auxiliaryWireRopeInspectioncorrosionMemenuhi),
        auxiliaryWireRopeInspectioncorrosionTidakMemenuhi: getCheckmark(!vi.auxiliaryWireRopeInspectioncorrosionMemenuhi),
        auxiliaryWireRopeInspectioncorrosionResult: vi.auxiliaryWireRopeInspectioncorrosionResult || getNaValue(vi.auxiliaryWireRopeInspectioncorrosionResult),
        auxiliaryWireRopeInspectionwearMemenuhi: getCheckmark(vi.auxiliaryWireRopeInspectionwearMemenuhi),
        auxiliaryWireRopeInspectionwearTidakMemenuhi: getCheckmark(!vi.auxiliaryWireRopeInspectionwearMemenuhi),
        auxiliaryWireRopeInspectionwearResult: vi.auxiliaryWireRopeInspectionwearResult || getNaValue(vi.auxiliaryWireRopeInspectionwearResult),
        auxiliaryWireRopeInspectionbreakageMemenuhi: getCheckmark(vi.auxiliaryWireRopeInspectionbreakageMemenuhi),
        auxiliaryWireRopeInspectionbreakageTidakMemenuhi: getCheckmark(!vi.auxiliaryWireRopeInspectionbreakageMemenuhi),
        auxiliaryWireRopeInspectionbreakageResult: vi.auxiliaryWireRopeInspectionbreakageResult || getNaValue(vi.auxiliaryWireRopeInspectionbreakageResult),
        auxiliaryWireRopeInspectiondeformationMemenuhi: getCheckmark(vi.auxiliaryWireRopeInspectiondeformationMemenuhi),
        auxiliaryWireRopeInspectiondeformationTidakMemenuhi: getCheckmark(!vi.auxiliaryWireRopeInspectiondeformationMemenuhi),
        auxiliaryWireRopeInspectiondeformationResult: vi.auxiliaryWireRopeInspectiondeformationResult || getNaValue(vi.auxiliaryWireRopeInspectiondeformationResult),
        mainChainInspectioncorrosionMemenuhi: getCheckmark(vi.mainChainInspectioncorrosionMemenuhi),
        mainChainInspectioncorrosionTidakMemenuhi: getCheckmark(!vi.mainChainInspectioncorrosionMemenuhi),
        mainChainInspectioncorrosionResult: vi.mainChainInspectioncorrosionResult || getNaValue(vi.mainChainInspectioncorrosionResult),
        mainChainInspectionwearMemenuhi: getCheckmark(vi.mainChainInspectionwearMemenuhi),
        mainChainInspectionwearTidakMemenuhi: getCheckmark(!vi.mainChainInspectionwearMemenuhi),
        mainChainInspectionwearResult: vi.mainChainInspectionwearResult || getNaValue(vi.mainChainInspectionwearResult),
        mainChainInspectioncrackOrBreakageMemenuhi: getCheckmark(vi.mainChainInspectioncrackOrBreakageMemenuhi),
        mainChainInspectioncrackOrBreakageTidakMemenuhi: getCheckmark(!vi.mainChainInspectioncrackOrBreakageMemenuhi),
        mainChainInspectioncrackOrBreakageResult: vi.mainChainInspectioncrackOrBreakageResult || getNaValue(vi.mainChainInspectioncrackOrBreakageResult),
        mainChainInspectiondeformationMemenuhi: getCheckmark(vi.mainChainInspectiondeformationMemenuhi),
        mainChainInspectiondeformationTidakMemenuhi: getCheckmark(!vi.mainChainInspectiondeformationMemenuhi),
        mainChainInspectiondeformationResult: vi.mainChainInspectiondeformationResult || getNaValue(vi.mainChainInspectiondeformationResult),
        auxiliaryChainInspectioncorrosionMemenuhi: getCheckmark(vi.auxiliaryChainInspectioncorrosionMemenuhi),
        auxiliaryChainInspectioncorrosionTidakMemenuhi: getCheckmark(!vi.auxiliaryChainInspectioncorrosionMemenuhi),
        auxiliaryChainInspectioncorrosionResult: vi.auxiliaryChainInspectioncorrosionResult || getNaValue(vi.auxiliaryChainInspectioncorrosionResult),
        auxiliaryChainInspectionwearMemenuhi: getCheckmark(vi.auxiliaryChainInspectionwearMemenuhi),
        auxiliaryChainInspectionwearTidakMemenuhi: getCheckmark(!vi.auxiliaryChainInspectionwearMemenuhi),
        auxiliaryChainInspectionwearResult: vi.auxiliaryChainInspectionwearResult || getNaValue(vi.auxiliaryChainInspectionwearResult),
        auxiliaryChainInspectioncrackOrBreakageMemenuhi: getCheckmark(vi.auxiliaryChainInspectioncrackOrBreakageMemenuhi),
        auxiliaryChainInspectioncrackOrBreakageTidakMemenuhi: getCheckmark(!vi.auxiliaryChainInspectioncrackOrBreakageMemenuhi),
        auxiliaryChainInspectioncrackOrBreakageResult: vi.auxiliaryChainInspectioncrackOrBreakageResult || getNaValue(vi.auxiliaryChainInspectioncrackOrBreakageResult),
        auxiliaryChainInspectiondeformationMemenuhi: getCheckmark(vi.auxiliaryChainInspectiondeformationMemenuhi),
        auxiliaryChainInspectiondeformationTidakMemenuhi: getCheckmark(!vi.auxiliaryChainInspectiondeformationMemenuhi),
        auxiliaryChainInspectiondeformationResult: vi.auxiliaryChainInspectiondeformationResult || getNaValue(vi.auxiliaryChainInspectiondeformationResult),
        limitSwitchlongTravelMemenuhi: getCheckmark(vi.limitSwitchlongTravelMemenuhi),
        limitSwitchlongTravelTidakMemenuhi: getCheckmark(!vi.limitSwitchlongTravelMemenuhi),
        limitSwitchlongTravelResult: vi.limitSwitchlongTravelResult || getNaValue(vi.limitSwitchlongTravelResult),
        limitSwitchcrossTravelMemenuhi: getCheckmark(vi.limitSwitchcrossTravelMemenuhi),
        limitSwitchcrossTravelTidakMemenuhi: getCheckmark(!vi.limitSwitchcrossTravelMemenuhi),
        limitSwitchcrossTravelResult: vi.limitSwitchcrossTravelResult || getNaValue(vi.limitSwitchcrossTravelResult),
        limitSwitchhoistMemenuhi: getCheckmark(vi.limitSwitchhoistMemenuhi),
        limitSwitchhoistTidakMemenuhi: getCheckmark(!vi.limitSwitchhoistMemenuhi),
        limitSwitchhoistResult: vi.limitSwitchhoistResult || getNaValue(vi.limitSwitchhoistResult),
        operatorCabinsafetyLadderMemenuhi: getCheckmark(vi.operatorCabinsafetyLadderMemenuhi),
        operatorCabinsafetyLadderTidakMemenuhi: getCheckmark(!vi.operatorCabinsafetyLadderMemenuhi),
        operatorCabinsafetyLadderResult: vi.operatorCabinsafetyLadderResult || getNaValue(vi.operatorCabinsafetyLadderResult),
        operatorCabindoorMemenuhi: getCheckmark(vi.operatorCabindoorMemenuhi),
        operatorCabindoorTidakMemenuhi: getCheckmark(!vi.operatorCabindoorMemenuhi),
        operatorCabindoorResult: vi.operatorCabindoorResult || getNaValue(vi.operatorCabindoorResult),
        operatorCabinwindowMemenuhi: getCheckmark(vi.operatorCabinwindowMemenuhi),
        operatorCabinwindowTidakMemenuhi: getCheckmark(!vi.operatorCabinwindowMemenuhi),
        operatorCabinwindowResult: vi.operatorCabinwindowResult || getNaValue(vi.operatorCabinwindowResult),
        operatorCabinfanOrACMemenuhi: getCheckmark(vi.operatorCabinfanOrACMemenuhi),
        operatorCabinfanOrACTidakMemenuhi: getCheckmark(!vi.operatorCabinfanOrACMemenuhi),
        operatorCabinfanOrACResult: vi.operatorCabinfanOrACResult || getNaValue(vi.operatorCabinfanOrACResult),
        operatorCabincontrolLeversOrButtonsMemenuhi: getCheckmark(vi.operatorCabincontrolLeversOrButtonsMemenuhi),
        operatorCabincontrolLeversOrButtonsTidakMemenuhi: getCheckmark(!vi.operatorCabincontrolLeversOrButtonsMemenuhi),
        operatorCabincontrolLeversOrButtonsResult: vi.operatorCabincontrolLeversOrButtonsResult || getNaValue(vi.operatorCabincontrolLeversOrButtonsResult),
        operatorCabinpendantControlMemenuhi: getCheckmark(vi.operatorCabinpendantControlMemenuhi),
        operatorCabinpendantControlTidakMemenuhi: getCheckmark(!vi.operatorCabinpendantControlMemenuhi),
        operatorCabinpendantControlResult: vi.operatorCabinpendantControlResult || getNaValue(vi.operatorCabinpendantControlResult),
        operatorCabinlightingMemenuhi: getCheckmark(vi.operatorCabinlightingMemenuhi),
        operatorCabinlightingTidakMemenuhi: getCheckmark(!vi.operatorCabinlightingMemenuhi),
        operatorCabinlightingResult: vi.operatorCabinlightingResult || getNaValue(vi.operatorCabinlightingResult),
        operatorCabinhornMemenuhi: getCheckmark(vi.operatorCabinhornMemenuhi),
        operatorCabinhornTidakMemenuhi: getCheckmark(!vi.operatorCabinhornMemenuhi),
        operatorCabinhornResult: vi.operatorCabinhornResult || getNaValue(vi.operatorCabinhornResult),
        operatorCabinfuseProtectionMemenuhi: getCheckmark(vi.operatorCabinfuseProtectionMemenuhi),
        operatorCabinfuseProtectionTidakMemenuhi: getCheckmark(!vi.operatorCabinfuseProtectionMemenuhi),
        operatorCabinfuseProtectionResult: vi.operatorCabinfuseProtectionResult || getNaValue(vi.operatorCabinfuseProtectionResult),
        operatorCabincommunicationDeviceMemenuhi: getCheckmark(vi.operatorCabincommunicationDeviceMemenuhi),
        operatorCabincommunicationDeviceTidakMemenuhi: getCheckmark(!vi.operatorCabincommunicationDeviceMemenuhi),
        operatorCabincommunicationDeviceResult: vi.operatorCabincommunicationDeviceResult || getNaValue(vi.operatorCabincommunicationDeviceResult),
        operatorCabinfireExtinguisherMemenuhi: getCheckmark(vi.operatorCabinfireExtinguisherMemenuhi),
        operatorCabinfireExtinguisherTidakMemenuhi: getCheckmark(!vi.operatorCabinfireExtinguisherMemenuhi),
        operatorCabinfireExtinguisherResult: vi.operatorCabinfireExtinguisherResult || getNaValue(vi.operatorCabinfireExtinguisherResult),
        operatorCabinoperationalSignsMemenuhi: getCheckmark(vi.operatorCabinoperationalSignsMemenuhi),
        operatorCabinoperationalSignsTidakMemenuhi: getCheckmark(!vi.operatorCabinoperationalSignsMemenuhi),
        operatorCabinoperationalSignsResult: vi.operatorCabinoperationalSignsResult || getNaValue(vi.operatorCabinoperationalSignsResult),
        operatorCabinignitionOrMasterSwitchMemenuhi: getCheckmark(vi.operatorCabinignitionOrMasterSwitchMemenuhi),
        operatorCabinignitionOrMasterSwitchTidakMemenuhi: getCheckmark(!vi.operatorCabinignitionOrMasterSwitchMemenuhi),
        operatorCabinignitionOrMasterSwitchResult: vi.operatorCabinignitionOrMasterSwitchResult || getNaValue(vi.operatorCabinignitionOrMasterSwitchResult),
        electricalComponentspanelConductorConnectorMemenuhi: getCheckmark(vi.electricalComponentspanelConductorConnectorMemenuhi),
        electricalComponentspanelConductorConnectorTidakMemenuhi: getCheckmark(!vi.electricalComponentspanelConductorConnectorMemenuhi),
        electricalComponentspanelConductorConnectorResult: vi.electricalComponentspanelConductorConnectorResult || getNaValue(vi.electricalComponentspanelConductorConnectorResult),
        electricalComponentsconductorProtectionMemenuhi: getCheckmark(vi.electricalComponentsconductorProtectionMemenuhi),
        electricalComponentsconductorProtectionTidakMemenuhi: getCheckmark(!vi.electricalComponentsconductorProtectionMemenuhi),
        electricalComponentsconductorProtectionResult: vi.electricalComponentsconductorProtectionResult || getNaValue(vi.electricalComponentsconductorProtectionResult),
        electricalComponentsmotorInstallationSafetySystemMemenuhi: getCheckmark(vi.electricalComponentsmotorInstallationSafetySystemMemenuhi),
        electricalComponentsmotorInstallationSafetySystemTidakMemenuhi: getCheckmark(!vi.electricalComponentsmotorInstallationSafetySystemMemenuhi),
        electricalComponentsmotorInstallationSafetySystemResult: vi.electricalComponentsmotorInstallationSafetySystemResult || getNaValue(vi.electricalComponentsmotorInstallationSafetySystemResult),
        electricalComponentsgroundingSystemMemenuhi: getCheckmark(vi.electricalComponentsgroundingSystemMemenuhi),
        electricalComponentsgroundingSystemTidakMemenuhi: getCheckmark(!vi.electricalComponentsgroundingSystemMemenuhi),
        electricalComponentsgroundingSystemResult: vi.electricalComponentsgroundingSystemResult || getNaValue(vi.electricalComponentsgroundingSystemResult),
        electricalComponentsinstallationMemenuhi: getCheckmark(vi.electricalComponentsinstallationMemenuhi),
        electricalComponentsinstallationTidakMemenuhi: getCheckmark(!vi.electricalComponentsinstallationMemenuhi),
        electricalComponentsinstallationResult: vi.electricalComponentsinstallationResult || getNaValue(vi.electricalComponentsinstallationResult),

        // NDT
        wireropeMethod: ndt.wireropeMethod || '',
        wirerope: ndt.wirerope || [], // Data dinamis
        HookspecA: ndt.HookspecA || '',
        HookspecB: ndt.HookspecB || '',
        HookspecC: ndt.HookspecC || '',
        HookspecD: ndt.HookspecD || '',
        HookspecE: ndt.HookspecE || '',
        HookspecF: ndt.HookspecF || '',
        HookspecG: ndt.HookspecG || '',
        HookspecH: ndt.HookspecH || '',
        HookspecBaik: getCheckmark(ndt.HookspecBaik),
        HookspecTidakBaik: getCheckmark(!ndt.HookspecBaik), // Perbaikan logika boolean
        HookspecDesc: ndt.HookspecDesc || '',
        measurementResultsA: ndt.measurementResultsA || '',
        measurementResultsB: ndt.measurementResultsB || '',
        measurementResultsC: ndt.measurementResultsC || '',
        measurementResultsD: ndt.measurementResultsD || '',
        measurementResultsE: ndt.measurementResultsE || '',
        measurementResultsF: ndt.measurementResultsF || '',
        measurementResultsG: ndt.measurementResultsG || '',
        measurementResultsH: ndt.measurementResultsH || '',
        measurementResultsBaik: getCheckmark(ndt.measurementResultsBaik),
        measurementResultsTidakBaik: getCheckmark(!ndt.measurementResultsBaik), // Perbaikan logika boolean
        measurementResultsDesc: ndt.measurementResultsDesc || '',
        toleranceA: ndt.toleranceA || '',
        toleranceB: ndt.toleranceB || '',
        toleranceC: ndt.toleranceC || '',
        toleranceD: ndt.toleranceD || '',
        toleranceE: ndt.toleranceE || '',
        toleranceF: ndt.toleranceF || '',
        toleranceG: ndt.toleranceG || '',
        toleranceH: ndt.toleranceH || '',
        toleranceBaik: getCheckmark(ndt.toleranceBaik),
        toleranceTidakBaik: getCheckmark(!ndt.toleranceBaik), // Perbaikan logika boolean
        toleranceDesc: ndt.toleranceDesc || '',
        griderMethod: ndt.griderMethod || '',
        // Memastikan data girder memiliki properti yang benar untuk loop
        girder: (ndt.girder || []).map(item => ({
            ...item,
            griderAda: getCheckmark(item.griderAda),
            griderTidakAda: getCheckmark(!item.griderAda) // Perbaikan logika boolean
        })),

        // Dynamic Testing
        travellingStatus: dyn.travellingStatus || '',
        travellingDesc: dyn.travellingDesc || '',
        traversingStatus: dyn.traversingStatus || '',
        traversingDesc: dyn.traversingDesc || '',
        hoistingStatus: dyn.hoistingStatus || '',
        hoistingDesc: dyn.hoistingDesc || '',
        safetyDeviceStatus: dyn.safetyDeviceStatus || '',
        safetyDeviceDesc: dyn.safetyDeviceDesc || '',
        brakeSwitchStatus: dyn.brakeSwitchStatus || '',
        brakeSwitchDesc: dyn.brakeSwitchDesc || '',
        brakeLockingStatus: dyn.brakeLockingStatus || '',
        brakeLockingDesc: dyn.brakeLockingDesc || '',
        instalasionElectricStatus: dyn.instalasionElectricStatus || '',
        instalasionElectricDesc: dyn.instalasionElectricDesc || '',
        hoist25: dyn.hoist25 || '',
        travesing25: dyn.travesing25 || '',
        travelling25: dyn.travelling25 || '',
        brakeSystem25: dyn.brakeSystem25 || '',
        desc25: dyn.desc25 || '',
        hoist50: dyn.hoist50 || '',
        travesing50: dyn.travesing50 || '',
        travelling50: dyn.travelling50 || '',
        brakeSystem50: dyn.brakeSystem50 || '',
        desc50: dyn.desc50 || '',
        hoist75: dyn.hoist75 || '',
        travesing75: dyn.travesing75 || '',
        travelling75: dyn.travelling75 || '',
        brakeSystem75: dyn.brakeSystem75 || '',
        desc75: dyn.desc75 || '',
        hoist100: dyn.hoist100 || '',
        travesing100: dyn.travesing100 || '',
        travelling100: dyn.travelling100 || '',
        brakeSystem100: dyn.brakeSystem100 || '',
        desc100: dyn.desc100 || '',

        // Static Testing
        loadTest: stat.loadTest || '',
        basedDesign: stat.basedDesign || '33.27', // Menambahkan nilai default jika kosong
        lengthSpan: stat.lengthSpan || '',
        xspan: stat.xspan || '',
        resultDefleksi: stat.resultDefleksi || '',
        defleksi: stat.defleksi || [], // Data dinamis

        // Conclusion & Recommendation
        conclusion: data.conclusion || '',
        recomendation: data.recomendation || '',
    };

    try {
        doc.render(renderData);
    } catch (error) {
        console.error("GAGAL RENDER DOKUMEN:", error.message);
        const e = {
            message: error.message,
            name: error.name,
            stack: error.stack,
            properties: error.properties,
        };
        console.log(JSON.stringify({ error: e }));
        throw error;
    }

    const docxBuffer = doc.getZip().generate({ type: 'nodebuffer', compression: 'DEFLATE' });
    const ownerName = (g.companyName || 'UnknownCompany').replace(/[^\w.-]/g, '_'); 
    const fileName = `Laporan-GantryCrane-${ownerName}-${data.reportNumber || data.id}.docx`;

    return { docxBuffer, fileName };
};

module.exports = {
    createLaporanGantryCrane,
};
