// src/services/documentGenerator/paa/gantryCrane/laporan/generator.js
'use strict';

const PizZip = require('pizzip');
const Docxtemplater = require('docxtemplater');
const { Storage } = require('@google-cloud/storage');
const config = require('../../../../../config');

// Inisialisasi GCS
let privateKey = config.FIRESTORE_PRIVATE_KEY.replace(/\\n/g, '\n');
const storage = new Storage({
    projectId: config.FIRESTORE_PROJECT_ID,
    credentials: { client_email: config.FIRESTORE_CLIENT_EMAIL, private_key: privateKey },
});
const BUCKET_NAME = 'tamplate-audit-riksauji'; // Pastikan nama bucket sudah benar

const getCheckmark = (status) => (status === true ? '√' : '');
const getOppositeCheckmark = (status) => (status === false ? '√' : '');
const getNaValue = (value) => (value === 'N/A' ? 'N/A' : ''); // Untuk mengisi N/A jika sesuai

const createLaporanGantryCrane = async (data) => {
    // Path template di GCS
    const templatePath = 'paa/gantryCrane/laporanGantryCrane.docx'; // Sesuaikan path ini jika berbeda

    let content;
    try {
        [content] = await storage.bucket(BUCKET_NAME).file(templatePath).download();
    } catch (error) {
        console.error('Gagal mengunduh template Laporan Gantry Crane:', error);
        throw new Error('Template dokumen Laporan Gantry Crane tidak dapat diakses.');
    }

    const zip = new PizZip(content);
    const doc = new Docxtemplater(zip, { paragraphLoop: true, linebreaks: true, nullGetter: () => "" });

    // Destrukturisasi data untuk kemudahan akses dan keamanan (menghindari error jika properti undefined)
    const g = data.generalData || {};
    const t = data.technicalData || {};
    const vi = data.visualInspection || {};
    const ndt = data.ndt || {};
    const dyn = data.dynamicTesting || {};
    const stat = data.staticTesting || {};

    const renderData = {
        // Data Utama (Root Level)
        examinationType: data.examinationType || '',
        inspectionType: data.inspectionType || '',
        reportNumber: data.reportNumber || '',
        equipmentType: data.equipmentType || '',

        // General Data
        companyName: g.companyName || '',
        companyLocation: g.companyLocation || '',
        usageLocation: g.usageLocation || '',
        location: g.location || '',
        manufacturerHoist: g.manufacturerHoist || '',
        manufacturerStructure: g.manufacturerStructure || '',
        brandOrType: g.brandOrType || '',
        manufactureYear: g.manufactureYear || '',
        serialNumber: g.serialNumber || '',
        maxLiftingCapacityKg: g.maxLiftingCapacityKg || '',
        usagePermitNumber: g.usagePermitNumber || '',
        operatorcertificateStatus: g.operatorcertificateStatus || '',
        technicalDataManualStatus: g.technicalDataManualStatus || '',
        inspectionDate: g.inspectionDate || '',

        // Technical Data
        liftHeight: t.liftHeight || '',
        girderLength: t.girderLength || '',
        hoistingSpeed: t.hoistingSpeed || '',
        travelingSpeed: t.travelingSpeed || '',
        traversingSpeed: t.traversingSpeed || '',
        driveMotorcapacity: t.driveMotorcapacity || '',
        hoistingpowerKw: t.hoistingpowerKw || '',
        travelingpowerKw: t.travelingpowerKw || '',
        traversingpowerKw: t.traversingpowerKw || '',
        hoistingtype: t.hoistingtype || '',
        travelingtype: t.travelingtype || '',
        traversingtype: t.traversingtype || '',
        hoistingrpm: t.hoistingrpm || '',
        travelingrpm: t.travelingrpm || '',
        traversingrpm: t.traversingrpm || '',
        hoistingvoltageV: t.hoistingvoltageV || '',
        travelingvoltageV: t.travelingvoltageV || '',
        traversingvoltageV: t.traversingvoltageV || '',
        hoistingcurrentA: t.hoistingcurrentA || '',
        travelingcurrentA: t.travelingcurrentA || '',
        traversingcurrentA: t.traversingcurrentA || '',
        hoistingfrequencyHz: t.hoistingfrequencyHz || '',
        travelingfrequencyHz: t.travelingfrequencyHz || '',
        traversingfrequencyHz: t.traversingfrequencyHz || '',
        hoistingphase: t.hoistingphase || '',
        travelingphase: t.travelingphase || '',
        traversingphase: t.traversingphase || '',
        hoistingpowerSupply: t.hoistingpowerSupply || '',
        travelingpowerSupply: t.travelingpowerSupply || '',
        traversingpowerSupply: t.traversingpowerSupply || '',
        braketype: t.braketype || '',
        brakemodel: t.brakemodel || '',
        controlBrakehoistingtype: t.controlBrakehoistingtype || '',
        controlBraketravelingtype: t.controlBraketravelingtype || '',
        controlBraketraversingtype: t.controlBraketraversingtype || '',
        controlBrakehoistingmodel: t.controlBrakehoistingmodel || '',
        controlBraketravelingmodel: t.controlBraketravelingmodel || '',
        controlBraketraversingmodel: t.controlBraketraversingmodel || '',
        hookhoistingtype: t.hookhoistingtype || '',
        hooktravelingtype: t.hooktravelingtype || '',
        hooktraversingtype: t.hooktraversingtype || '',
        hookhoistingcapacity: t.hookhoistingcapacity || '',
        hooktravelingcapacity: t.hooktravelingcapacity || '',
        hooktraversingcapacity: t.hooktraversingcapacity || '',
        hookhoistingmaterial: t.hookhoistingmaterial || '',
        hooktravelingmaterial: t.hooktravelingmaterial || '',
        hooktraversingmaterial: t.hooktraversingmaterial || '',
        wireRopeOrChainmediumType: t.wireRopeOrChainmediumType || '',
        mediumTypehoistingtype: t.mediumTypehoistingtype || '',
        mediumTypetravelingtype: t.mediumTypetravelingtype || '',
        mediumTypetraversingtype: t.mediumTypetraversingtype || '',
        mediumTypehoistingconstruction: t.mediumTypehoistingconstruction || '',
        mediumTypetravelingconstruction: t.mediumTypetravelingconstruction || '',
        mediumTypetraversingconstruction: t.mediumTypetraversingconstruction || '',
        mediumTypehoistingdiameter: t.mediumTypehoistingdiameter || '',
        mediumTypetravelingdiameter: t.mediumTypetravelingdiameter || '',
        mediumTypetraversingdiameter: t.mediumTypetraversingdiameter || '',
        mediumTypehoistinglength: t.mediumTypehoistinglength || '',
        mediumTypetravelinglength: t.mediumTypetravelinglength || '',
        mediumTypetraversinglength: t.mediumTypetraversinglength || '',

        // Visual Inspection
        anchorBoltscorrosionMemenuhi: getCheckmark(vi.anchorBoltscorrosionMemenuhi),
        anchorBoltscorrosionTidakMemenuhi: getOppositeCheckmark(vi.anchorBoltscorrosionTidakMemenuhi),
        anchorBoltscorrosionResult: vi.anchorBoltscorrosionResult || getNaValue(vi.anchorBoltscorrosionResult),
        anchorBoltscracksMemenuhi: getCheckmark(vi.anchorBoltscracksMemenuhi),
        anchorBoltscracksTidakMemenuhi: getOppositeCheckmark(vi.anchorBoltscracksTidakMemenuhi),
        anchorBoltscracksResult: vi.anchorBoltscracksResult || getNaValue(vi.anchorBoltscracksResult),
        anchorBoltsdeformationMemenuhi: getCheckmark(vi.anchorBoltsdeformationMemenuhi),
        anchorBoltsdeformationTidakMemenuhi: getOppositeCheckmark(vi.anchorBoltsdeformationTidakMemenuhi),
        anchorBoltsdeformationResult: vi.anchorBoltsdeformationResult || getNaValue(vi.anchorBoltsdeformationResult),
        anchorBoltsfasteningMemenuhi: getCheckmark(vi.anchorBoltsfasteningMemenuhi),
        anchorBoltsfasteningTidakMemenuhi: getOppositeCheckmark(vi.anchorBoltsfasteningTidakMemenuhi),
        anchorBoltsfasteningResult: vi.anchorBoltsfasteningResult || getNaValue(vi.anchorBoltsfasteningResult),
        columnFramecorrosionMemenuhi: getCheckmark(vi.columnFramecorrosionMemenuhi),
        columnFramecorrosionTidakMemenuhi: getOppositeCheckmark(vi.columnFramecorrosionTidakMemenuhi),
        columnFramecorrosionResult: vi.columnFramecorrosionResult || getNaValue(vi.columnFramecorrosionResult),
        columnFramecracksMemenuhi: getCheckmark(vi.columnFramecracksMemenuhi),
        columnFramecracksTidakMemenuhi: getOppositeCheckmark(vi.columnFramecracksTidakMemenuhi),
        columnFramecracksResult: vi.columnFramecracksResult || getNaValue(vi.columnFramecracksResult),
        columnFramedeformationMemenuhi: getCheckmark(vi.columnFramedeformationMemenuhi),
        columnFramedeformationTidakMemenuhi: getOppositeCheckmark(vi.columnFramedeformationTidakMemenuhi),
        columnFramedeformationResult: vi.columnFramedeformationResult || getNaValue(vi.columnFramedeformationResult),
        columnFramefasteningMemenuhi: getCheckmark(vi.columnFramefasteningMemenuhi),
        columnFramefasteningTidakMemenuhi: getOppositeCheckmark(vi.columnFramefasteningTidakMemenuhi),
        columnFramefasteningResult: vi.columnFramefasteningResult || getNaValue(vi.columnFramefasteningResult),
        columnFrametransverseReinforcementMemenuhi: getCheckmark(vi.columnFrametransverseReinforcementMemenuhi),
        columnFrametransverseReinforcementTidakMemenuhi: getOppositeCheckmark(vi.columnFrametransverseReinforcementTidakMemenuhi),
        columnFrametransverseReinforcementResult: vi.columnFrametransverseReinforcementResult || getNaValue(vi.columnFrametransverseReinforcementResult),
        columnFramediagonalReinforcementMemenuhi: getCheckmark(vi.columnFramediagonalReinforcementMemenuhi),
        columnFramediagonalReinforcementTidakMemenuhi: getOppositeCheckmark(vi.columnFramediagonalReinforcementTidakMemenuhi),
        columnFramediagonalReinforcementResult: vi.columnFramediagonalReinforcementResult || getNaValue(vi.columnFramediagonalReinforcementResult),
        laddercorrosionMemenuhi: getCheckmark(vi.laddercorrosionMemenuhi),
        laddercorrosionTidakMemenuhi: getOppositeCheckmark(vi.laddercorrosionTidakMemenuhi),
        laddercorrosionResult: vi.laddercorrosionResult || getNaValue(vi.laddercorrosionResult),
        laddercracksMemenuhi: getCheckmark(vi.laddercracksMemenuhi),
        laddercracksTidakMemenuhi: getOppositeCheckmark(vi.laddercracksTidakMemenuhi),
        laddercracksResult: vi.laddercracksResult || getNaValue(vi.laddercracksResult),
        ladderdeformationMemenuhi: getCheckmark(vi.ladderdeformationMemenuhi),
        ladderdeformationTidakMemenuhi: getOppositeCheckmark(vi.ladderdeformationTidakMemenuhi),
        ladderdeformationResult: vi.ladderdeformationResult || getNaValue(vi.ladderdeformationResult),
        ladderfasteningMemenuhi: getCheckmark(vi.ladderfasteningMemenuhi),
        ladderfasteningTidakMemenuhi: getOppositeCheckmark(vi.ladderfasteningTidakMemenuhi),
        ladderfasteningResult: vi.ladderfasteningResult || getNaValue(vi.ladderfasteningResult),
        workingFloorcorrosionMemenuhi: getCheckmark(vi.workingFloorcorrosionMemenuhi),
        workingFloorcorrosionTidakMemenuhi: getOppositeCheckmark(vi.workingFloorcorrosionTidakMemenuhi),
        workingFloorcorrosionResult: vi.workingFloorcorrosionResult || getNaValue(vi.workingFloorcorrosionResult),
        workingFloorcracksMemenuhi: getCheckmark(vi.workingFloorcracksMemenuhi),
        workingFloorcracksTidakMemenuhi: getOppositeCheckmark(vi.workingFloorcracksTidakMemenuhi),
        workingFloorcracksResult: vi.workingFloorcracksResult || getNaValue(vi.workingFloorcracksResult),
        workingFloordeformationMemenuhi: getCheckmark(vi.workingFloordeformationMemenuhi),
        workingFloordeformationTidakMemenuhi: getOppositeCheckmark(vi.workingFloordeformationTidakMemenuhi),
        workingFloordeformationResult: vi.workingFloordeformationResult || getNaValue(vi.workingFloordeformationResult),
        workingFloorfasteningMemenuhi: getCheckmark(vi.workingFloorfasteningMemenuhi),
        workingFloorfasteningTidakMemenuhi: getOppositeCheckmark(vi.workingFloorfasteningTidakMemenuhi),
        workingFloorfasteningResult: vi.workingFloorfasteningResult || getNaValue(vi.workingFloorfasteningResult),
        railSupportBeamcorrosionMemenuhi: getCheckmark(vi.railSupportBeamcorrosionMemenuhi),
        railSupportBeamcorrosionTidakMemenuhi: getOppositeCheckmark(vi.railSupportBeamcorrosionTidakMemenuhi),
        railSupportBeamcorrosionResult: vi.railSupportBeamcorrosionResult || getNaValue(vi.railSupportBeamcorrosionResult),
        railSupportBeamcracksMemenuhi: getCheckmark(vi.railSupportBeamcracksMemenuhi),
        railSupportBeamcracksTidakMemenuhi: getOppositeCheckmark(vi.railSupportBeamcracksTidakMemenuhi),
        railSupportBeamcracksResult: vi.railSupportBeamcracksResult || getNaValue(vi.railSupportBeamcracksResult),
        railSupportBeamdeformationMemenuhi: getCheckmark(vi.railSupportBeamdeformationMemenuhi),
        railSupportBeamdeformationTidakMemenuhi: getOppositeCheckmark(vi.railSupportBeamdeformationTidakMemenuhi),
        railSupportBeamdeformationResult: vi.railSupportBeamdeformationResult || getNaValue(vi.railSupportBeamdeformationResult),
        railSupportBeamfasteningMemenuhi: getCheckmark(vi.railSupportBeamfasteningMemenuhi),
        railSupportBeamfasteningTidakMemenuhi: getOppositeCheckmark(vi.railSupportBeamfasteningTidakMemenuhi),
        railSupportBeamfasteningResult: vi.railSupportBeamfasteningResult || getNaValue(vi.railSupportBeamfasteningResult),
        travelingRailcorrosionMemenuhi: getCheckmark(vi.travelingRailcorrosionMemenuhi),
        travelingRailcracksTidakMemenuhi: getOppositeCheckmark(vi.travelingRailcracksTidakMemenuhi),
        travelingRailcracksResult: vi.travelingRailcracksResult || getNaValue(vi.travelingRailcracksResult),
        travelingcracksMemenuhi: getCheckmark(vi.travelingcracksMemenuhi),
        travelingcracksTidakMemenuhi: getOppositeCheckmark(vi.travelingcracksTidakMemenuhi),
        travelingcracksResult: vi.travelingcracksResult || getNaValue(vi.travelingcracksResult),
        travelingrailConnectionMemenuhi: getCheckmark(vi.travelingrailConnectionMemenuhi),
        travelingrailConnectionTidakMemenuhi: getOppositeCheckmark(vi.travelingrailConnectionTidakMemenuhi),
        travelingrailConnectionResult: vi.travelingrailConnectionResult || getNaValue(vi.travelingrailConnectionResult),
        travelingrailAlignmentMemenuhi: getCheckmark(vi.travelingrailAlignmentMemenuhi),
        travelingrailAlignmentTidakMemenuhi: getOppositeCheckmark(vi.travelingrailAlignmentTidakMemenuhi),
        travelingrailAlignmentResult: vi.travelingrailAlignmentResult || getNaValue(vi.travelingrailAlignmentResult),
        travelinginterRailAlignmentMemenuhi: getCheckmark(vi.travelinginterRailAlignmentMemenuhi),
        travelinginterRailAlignmentTidakMemenuhi: getOppositeCheckmark(vi.travelinginterRailAlignmentTidakMemenuhi),
        travelinginterRailAlignmentResult: vi.travelinginterRailAlignmentResult || getNaValue(vi.travelinginterRailAlignmentResult),
        travelinginterRailFlatnessMemenuhi: getCheckmark(vi.travelinginterRailFlatnessMemenuhi),
        travelinginterRailFlatnessTidakMemenuhi: getOppositeCheckmark(vi.travelinginterRailFlatnessTidakMemenuhi),
        travelinginterRailFlatnessResult: vi.travelinginterRailFlatnessResult || getNaValue(vi.travelinginterRailFlatnessResult),
        travelingrailConnectionGapMemenuhi: getCheckmark(vi.travelingrailConnectionGapMemenuhi),
        travelingrailConnectionGapTidakMemenuhi: getOppositeCheckmark(vi.travelingrailConnectionGapTidakMemenuhi),
        travelingrailConnectionGapResult: vi.travelingrailConnectionGapResult || getNaValue(vi.travelingrailConnectionGapResult),
        travelingrailFastenerMemenuhi: getCheckmark(vi.travelingrailFastenerMemenuhi),
        travelingrailFastenerTidakMemenuhi: getOppositeCheckmark(vi.travelingrailFastenerTidakMemenuhi),
        travelingrailFastenerResult: vi.travelingrailFastenerResult || getNaValue(vi.travelingrailFastenerResult),
        travelingrailStopperMemenuhi: getCheckmark(vi.travelingrailStopperMemenuhi),
        travelingrailStopperTidakMemenuhi: getOppositeCheckmark(vi.travelingrailStopperTidakMemenuhi),
        travelingrailStopperResult: vi.travelingrailStopperResult || getNaValue(vi.travelingrailStopperResult),
        traversingRailcorrosionMemenuhi: getCheckmark(vi.traversingRailcorrosionMemenuhi),
        traversingRailcorrosionTidakMemenuhi: getOppositeCheckmark(vi.traversingRailcorrosionTidakMemenuhi),
        traversingRailcorrosionResult: vi.traversingRailcorrosionResult || getNaValue(vi.traversingRailcorrosionResult),
        traversingRailcracksMemenuhi: getCheckmark(vi.traversingRailcracksMemenuhi),
        traversingRailcracksTidakMemenuhi: getOppositeCheckmark(vi.traversingRailcracksTidakMemenuhi),
        traversingRailcracksResult: vi.traversingRailcracksResult || getNaValue(vi.traversingRailcracksResult),
        traversingRailrailConnectionMemenuhi: getCheckmark(vi.traversingRailrailConnectionMemenuhi),
        traversingRailrailConnectionTidakMemenuhi: getOppositeCheckmark(vi.traversingRailrailConnectionTidakMemenuhi),
        traversingRailrailConnectionResult: vi.traversingRailrailConnectionResult || getNaValue(vi.traversingRailrailConnectionResult),
        traversingRailrailAlignmentMemenuhi: getCheckmark(vi.traversingRailrailAlignmentMemenuhi),
        traversingRailrailAlignmentTidakMemenuhi: getOppositeCheckmark(vi.traversingRailrailAlignmentTidakMemenuhi),
        traversingRailrailAlignmentResult: vi.traversingRailrailAlignmentResult || getNaValue(vi.traversingRailrailAlignmentResult),
        traversingRailinterRailAlignmentMemenuhi: getCheckmark(vi.traversingRailinterRailAlignmentMemenuhi),
        traversingRailinterRailAlignmentTidakMemenuhi: getOppositeCheckmark(vi.traversingRailinterRailAlignmentTidakMemenuhi),
        traversingRailinterRailAlignmentResult: vi.traversingRailinterRailAlignmentResult || getNaValue(vi.traversingRailinterRailAlignmentResult),
        traversingRailinterRailFlatnessMemenuhi: getCheckmark(vi.traversingRailinterRailFlatnessMemenuhi),
        traversingRailinterRailFlatnessTidakMemenuhi: getOppositeCheckmark(vi.traversingRailinterRailFlatnessTidakMemenuhi),
        traversingRailinterRailFlatnessResult: vi.traversingRailinterRailFlatnessResult || getNaValue(vi.traversingRailinterRailFlatnessResult),
        traversingRailrailConnectionGapMemenuhi: getCheckmark(vi.traversingRailrailConnectionGapMemenuhi),
        traversingRailrailConnectionGapTidakMemenuhi: getOppositeCheckmark(vi.traversingRailrailConnectionGapTidakMemenuhi),
        traversingRailrailConnectionGapResult: vi.traversingRailrailConnectionGapResult || getNaValue(vi.traversingRailrailConnectionGapResult),
        traversingRailrailFastenerMemenuhi: getCheckmark(vi.traversingRailrailFastenerMemenuhi),
        traversingRailrailFastenerTidakMemenuhi: getOppositeCheckmark(vi.traversingRailrailFastenerTidakMemenuhi),
        traversingRailrailFastenerResult: vi.traversingRailrailFastenerResult || getNaValue(vi.traversingRailrailFastenerResult),
        traversingRailrailStopperMemenuhi: getCheckmark(vi.traversingRailrailStopperMemenuhi),
        traversingRailrailStopperTidakMemenuhi: getOppositeCheckmark(vi.traversingRailrailStopperTidakMemenuhi),
        traversingRailrailStopperResult: vi.traversingRailrailStopperResult || getNaValue(vi.traversingRailrailStopperResult),
        girdercorrosionMemenuhi: getCheckmark(vi.girdercorrosionMemenuhi),
        girdercorrosionTidakMemenuhi: getOppositeCheckmark(vi.girdercorrosionTidakMemenuhi),
        girdercorrosionResult: vi.girdercorrosionResult || getNaValue(vi.girdercorrosionResult),
        girdercracksMemenuhi: getCheckmark(vi.girdercracksMemenuhi),
        girdercracksTidakMemenuhi: getOppositeCheckmark(vi.girdercracksTidakMemenuhi),
        girdercracksResult: vi.girdercracksResult || getNaValue(vi.girdercracksResult),
        girdercamberMemenuhi: getCheckmark(vi.girdercamberMemenuhi),
        girdercamberTidakMemenuhi: getOppositeCheckmark(vi.girdercamberTidakMemenuhi),
        girdercamberResult: vi.girdercamberResult || getNaValue(vi.girdercamberResult),
        girderConnectionMemenuhi: getCheckmark(vi.girderConnectionMemenuhi),
        girderConnectionTidakMemenuhi: getOppositeCheckmark(vi.girderConnectionTidakMemenuhi),
        girderConnectionResult: vi.girderConnectionResult || getNaValue(vi.girderConnectionResult),
        girderendGirderConnectionMemenuhi: getCheckmark(vi.girderendGirderConnectionMemenuhi),
        girderendGirderConnectionTidakMemenuhi: getOppositeCheckmark(vi.girderendGirderConnectionTidakMemenuhi),
        girderendGirderConnectionResult: vi.girderendGirderConnectionResult || getNaValue(vi.girderendGirderConnectionResult),
        girdertruckMountingOnGirderMemenuhi: getCheckmark(vi.girdertruckMountingOnGirderMemenuhi),
        girdertruckMountingOnGirderTidakMemenuhi: getOppositeCheckmark(vi.girdertruckMountingOnGirderTidakMemenuhi),
        girdertruckMountingOnGirderResult: vi.girdertruckMountingOnGirderResult || getNaValue(vi.girdertruckMountingOnGirderResult),
        travelingGearboxcorrosionMemenuhi: getCheckmark(vi.travelingGearboxcorrosionMemenuhi),
        travelingGearboxcorrosionTidakMemenuhi: getOppositeCheckmark(vi.travelingGearboxcorrosionTidakMemenuhi),
        travelingGearboxcorrosionResult: vi.travelingGearboxcorrosionResult || getNaValue(vi.travelingGearboxcorrosionResult),
        travelingGearboxcracksMemenuhi: getCheckmark(vi.travelingGearboxcracksMemenuhi),
        travelingGearboxcracksTidakMemenuhi: getOppositeCheckmark(vi.travelingGearboxcracksTidakMemenuhi),
        travelingGearboxcracksResult: vi.travelingGearboxcracksResult || getNaValue(vi.travelingGearboxcracksResult),
        travelingGearboxlubricatingOilMemenuhi: getCheckmark(vi.travelingGearboxlubricatingOilMemenuhi),
        travelingGearboxlubricatingOilTidakMemenuhi: getOppositeCheckmark(vi.travelingGearboxlubricatingOilTidakMemenuhi),
        travelingGearboxlubricatingOilResult: vi.travelingGearboxlubricatingOilResult || getNaValue(vi.travelingGearboxlubricatingOilResult),
        travelingGearboxoilSealMemenuhi: getCheckmark(vi.travelingGearboxoilSealMemenuhi),
        travelingGearboxoilSealTidakMemenuhi: getOppositeCheckmark(vi.travelingGearboxoilSealTidakMemenuhi),
        travelingGearboxoilSealResult: vi.travelingGearboxoilSealResult || getNaValue(vi.travelingGearboxoilSealResult),
        driveWheelswearMemenuhi: getCheckmark(vi.driveWheelswearMemenuhi),
        driveWheelswearTidakMemenuhi: getOppositeCheckmark(vi.driveWheelswearTidakMemenuhi),
        driveWheelswearResult: vi.driveWheelswearResult || getNaValue(vi.driveWheelswearResult),
        driveWheelscracksMemenuhi: getCheckmark(vi.driveWheelscracksMemenuhi),
        driveWheelscracksTidakMemenuhi: getOppositeCheckmark(vi.driveWheelscracksTidakMemenuhi),
        driveWheelscracksResult: vi.driveWheelscracksResult || getNaValue(vi.driveWheelscracksResult),
        driveWheelsdeformationMemenuhi: getCheckmark(vi.driveWheelsdeformationMemenuhi),
        driveWheelsdeformationTidakMemenuhi: getOppositeCheckmark(vi.driveWheelsdeformationTidakMemenuhi),
        driveWheelsdeformationResult: vi.driveWheelsdeformationResult || getNaValue(vi.driveWheelsdeformationResult),
        driveWheelsflangeConditionMemenuhi: getCheckmark(vi.driveWheelsflangeConditionMemenuhi),
        driveWheelsflangeConditionTidakMemenuhi: getOppositeCheckmark(vi.driveWheelsflangeConditionTidakMemenuhi),
        driveWheelsflangeConditionResult: vi.driveWheelsflangeConditionResult || getNaValue(vi.driveWheelsflangeConditionResult),
        driveWheelschainConditionMemenuhi: getCheckmark(vi.driveWheelschainConditionMemenuhi),
        driveWheelschainConditionTidakMemenuhi: getOppositeCheckmark(vi.driveWheelschainConditionTidakMemenuhi),
        driveWheelschainConditionResult: vi.driveWheelschainConditionResult || getNaValue(vi.driveWheelschainConditionResult),
        idleWheelssafetyMemenuhi: getCheckmark(vi.idleWheelssafetyMemenuhi),
        idleWheelssafetyTidakMemenuhi: getOppositeCheckmark(vi.idleWheelssafetyTidakMemenuhi),
        idleWheelssafetyResult: vi.idleWheelssafetyResult || getNaValue(vi.idleWheelssafetyResult),
        idleWheelscracksMemenuhi: getCheckmark(vi.idleWheelscracksMemenuhi),
        idleWheelscracksTidakMemenuhi: getOppositeCheckmark(vi.idleWheelscracksTidakMemenuhi),
        idleWheelscracksResult: vi.idleWheelscracksResult || getNaValue(vi.idleWheelscracksResult),
        idleWheelsdeformationMemenuhi: getCheckmark(vi.idleWheelsdeformationMemenuhi),
        idleWheelsdeformationTidakMemenuhi: getOppositeCheckmark(vi.idleWheelsdeformationTidakMemenuhi),
        idleWheelsdeformationResult: vi.idleWheelsdeformationResult || getNaValue(vi.idleWheelsdeformationResult),
        idleWheelsflangeConditionMemenuhi: getCheckmark(vi.idleWheelsflangeConditionMemenuhi),
        idleWheelsflangeConditionTidakMemenuhi: getOppositeCheckmark(vi.idleWheelsflangeConditionTidakMemenuhi),
        idleWheelsflangeConditionResult: vi.idleWheelsflangeConditionResult || getNaValue(vi.idleWheelsflangeConditionResult),
        wheelConnectoralignmentMemenuhi: getCheckmark(vi.wheelConnectoralignmentMemenuhi),
        wheelConnectoralignmentTidakMemenuhi: getOppositeCheckmark(vi.wheelConnectoralignmentTidakMemenuhi),
        wheelConnectoralignmentResult: vi.wheelConnectoralignmentResult || getNaValue(vi.wheelConnectoralignmentResult),
        wheelConnectorcrossJointMemenuhi: getCheckmark(vi.wheelConnectorcrossJointMemenuhi),
        wheelConnectorcrossJointTidakMemenuhi: getOppositeCheckmark(vi.wheelConnectorcrossJointTidakMemenuhi),
        wheelConnectorcrossJointResult: vi.wheelConnectorcrossJointResult || getNaValue(vi.wheelConnectorcrossJointResult),
        wheelConnectorlubricationMemenuhi: getCheckmark(vi.wheelConnectorlubricationMemenuhi),
        wheelConnectorlubricationTidakMemenuhi: getOppositeCheckmark(vi.wheelConnectorlubricationTidakMemenuhi),
        wheelConnectorlubricationResult: vi.wheelConnectorlubricationResult || getNaValue(vi.wheelConnectorlubricationResult),
        girderStopperconditionMemenuhi: getCheckmark(vi.girderStopperconditionMemenuhi),
        girderStopperconditionTidakMemenuhi: getOppositeCheckmark(vi.girderStopperconditionTidakMemenuhi),
        girderStopperconditionResult: vi.girderStopperconditionResult || getNaValue(vi.girderStopperconditionResult),
        girderStopperreinforcementMemenuhi: getCheckmark(vi.girderStopperreinforcementMemenuhi),
        girderStopperreinforcementTidakMemenuhi: getOppositeCheckmark(vi.girderStopperreinforcementTidakMemenuhi),
        girderStopperreinforcementResult: vi.girderStopperreinforcementResult || getNaValue(vi.girderStopperreinforcementResult),
        trolleyTraversingGearboxfasteningMemenuhi: getCheckmark(vi.trolleyTraversingGearboxfasteningMemenuhi),
        trolleyTraversingGearboxfasteningTidakMemenuhi: getOppositeCheckmark(vi.trolleyTraversingGearboxfasteningTidakMemenuhi),
        trolleyTraversingGearboxfasteningResult: vi.trolleyTraversingGearboxfasteningResult || getNaValue(vi.trolleyTraversingGearboxfasteningResult),
        trolleyTraversingGearboxcorrosionMemenuhi: getCheckmark(vi.trolleyTraversingGearboxcorrosionMemenuhi),
        trolleyTraversingGearboxcorrosionTidakMemenuhi: getOppositeCheckmark(vi.trolleyTraversingGearboxcorrosionTidakMemenuhi),
        trolleyTraversingGearboxcorrosionResult: vi.trolleyTraversingGearboxcorrosionResult || getNaValue(vi.trolleyTraversingGearboxcorrosionResult),
        trolleyTraversingGearboxcracksMemenuhi: getCheckmark(vi.trolleyTraversingGearboxcracksMemenuhi),
        trolleyTraversingGearboxcracksTidakMemenuhi: getOppositeCheckmark(vi.trolleyTraversingGearboxcracksTidakMemenuhi),
        trolleyTraversingGearboxcracksResult: vi.trolleyTraversingGearboxcracksResult || getNaValue(vi.trolleyTraversingGearboxcracksResult),
        trolleyTraversingGearboxlubricatingOilMemenuhi: getCheckmark(vi.trolleyTraversingGearboxlubricatingOilMemenuhi),
        trolleyTraversingGearboxlubricatingOilTidakMemenuhi: getOppositeCheckmark(vi.trolleyTraversingGearboxlubricatingOilTidakMemenuhi),
        trolleyTraversingGearboxlubricatingOilResult: vi.trolleyTraversingGearboxlubricatingOilResult || getNaValue(vi.trolleyTraversingGearboxlubricatingOilResult),
        trolleyTraversingGearboxoilSealMemenuhi: getCheckmark(vi.trolleyTraversingGearboxoilSealMemenuhi),
        trolleyTraversingGearboxoilSealTidakMemenuhi: getOppositeCheckmark(vi.trolleyTraversingGearboxoilSealTidakMemenuhi),
        trolleyTraversingGearboxoilSealResult: vi.trolleyTraversingGearboxoilSealResult || getNaValue(vi.trolleyTraversingGearboxoilSealResult),
        trolleyDriveWheelswearMemenuhi: getCheckmark(vi.trolleyDriveWheelswearMemenuhi),
        trolleyDriveWheelswearTidakMemenuhi: getOppositeCheckmark(vi.trolleyDriveWheelswearTidakMemenuhi),
        trolleyDriveWheelswearResult: vi.trolleyDriveWheelswearResult || getNaValue(vi.trolleyDriveWheelswearResult),
        trolleyDriveWheelscracksMemenuhi: getCheckmark(vi.trolleyDriveWheelscracksMemenuhi),
        trolleyDriveWheelscracksTidakMemenuhi: getOppositeCheckmark(vi.trolleyDriveWheelscracksTidakMemenuhi),
        trolleyDriveWheelscracksResult: vi.trolleyDriveWheelscracksResult || getNaValue(vi.trolleyDriveWheelscracksResult),
        trolleyDriveWheelsdeformationMemenuhi: getCheckmark(vi.trolleyDriveWheelsdeformationMemenuhi),
        trolleyDriveWheelsdeformationTidakMemenuhi: getOppositeCheckmark(vi.trolleyDriveWheelsdeformationTidakMemenuhi),
        trolleyDriveWheelsdeformationResult: vi.trolleyDriveWheelsdeformationResult || getNaValue(vi.trolleyDriveWheelsdeformationResult),
        trolleyDriveWheelsflangeConditionMemenuhi: getCheckmark(vi.trolleyDriveWheelsflangeConditionMemenuhi),
        trolleyDriveWheelsflangeConditionTidakMemenuhi: getOppositeCheckmark(vi.trolleyDriveWheelsflangeConditionTidakMemenuhi),
        trolleyDriveWheelsflangeConditionResult: vi.trolleyDriveWheelsflangeConditionResult || getNaValue(vi.trolleyDriveWheelsflangeConditionResult),
        trolleyDriveWheelschainConditionMemenuhi: getCheckmark(vi.trolleyDriveWheelschainConditionMemenuhi),
        trolleyDriveWheelschainConditionTidakMemenuhi: getOppositeCheckmark(vi.trolleyDriveWheelschainConditionTidakMemenuhi),
        trolleyDriveWheelschainConditionResult: vi.trolleyDriveWheelschainConditionResult || getNaValue(vi.trolleyDriveWheelschainConditionResult),
        trolleyIdleWheelswearMemenuhi: getCheckmark(vi.trolleyIdleWheelswearMemenuhi),
        trolleyIdleWheelswearTidakMemenuhi: getOppositeCheckmark(vi.trolleyIdleWheelswearTidakMemenuhi),
        trolleyIdleWheelswearResult: vi.trolleyIdleWheelswearResult || getNaValue(vi.trolleyIdleWheelswearResult),
        trolleyIdleWheelscracksMemenuhi: getCheckmark(vi.trolleyIdleWheelscracksMemenuhi),
        trolleyIdleWheelscracksTidakMemenuhi: getOppositeCheckmark(vi.trolleyIdleWheelscracksTidakMemenuhi),
        trolleyIdleWheelscracksResult: vi.trolleyIdleWheelscracksResult || getNaValue(vi.trolleyIdleWheelscracksResult),
        trolleyIdleWheelsdeformationMemenuhi: getCheckmark(vi.trolleyIdleWheelsdeformationMemenuhi),
        trolleyIdleWheelsdeformationTidakMemenuhi: getOppositeCheckmark(vi.trolleyIdleWheelsdeformationTidakMemenuhi),
        trolleyIdleWheelsdeformationResult: vi.trolleyIdleWheelsdeformationResult || getNaValue(vi.trolleyIdleWheelsdeformationResult),
        trolleyIdleWheelsflangeConditionMemenuhi: getCheckmark(vi.trolleyIdleWheelsflangeConditionMemenuhi),
        trolleyIdleWheelsflangeConditionTidakMemenuhi: getOppositeCheckmark(vi.trolleyIdleWheelsflangeConditionTidakMemenuhi),
        trolleyIdleWheelsflangeConditionResult: vi.trolleyIdleWheelsflangeConditionResult || getNaValue(vi.trolleyIdleWheelsflangeConditionResult),
        trolleyWheelConnectoralignmentMemenuhi: getCheckmark(vi.trolleyWheelConnectoralignmentMemenuhi),
        trolleyWheelConnectoralignmentTidakMemenuhi: getOppositeCheckmark(vi.trolleyWheelConnectoralignmentTidakMemenuhi),
        trolleyWheelConnectoralignmentResult: vi.trolleyWheelConnectoralignmentResult || getNaValue(vi.trolleyWheelConnectoralignmentResult),
        trolleyWheelConnectorcrossJointMemenuhi: getCheckmark(vi.trolleyWheelConnectorcrossJointMemenuhi),
        trolleyWheelConnectorcrossJointTidakMemenuhi: getOppositeCheckmark(vi.trolleyWheelConnectorcrossJointTidakMemenuhi),
        trolleyWheelConnectorcrossJointResult: vi.trolleyWheelConnectorcrossJointResult || getNaValue(vi.trolleyWheelConnectorcrossJointResult),
        trolleyWheelConnectorlubricationMemenuhi: getCheckmark(vi.trolleyWheelConnectorlubricationMemenuhi),
        trolleyWheelConnectorlubricationTidakMemenuhi: getOppositeCheckmark(vi.trolleyWheelConnectorlubricationTidakMemenuhi),
        trolleyWheelConnectorlubricationResult: vi.trolleyWheelConnectorlubricationResult || getNaValue(vi.trolleyWheelConnectorlubricationResult),
        trolleyGirderStopperconditionMemenuhi: getCheckmark(vi.trolleyGirderStopperconditionMemenuhi),
        trolleyGirderStopperconditionTidakMemenuhi: getOppositeCheckmark(vi.trolleyGirderStopperconditionTidakMemenuhi),
        trolleyGirderStopperconditionResult: vi.trolleyGirderStopperconditionResult || getNaValue(vi.trolleyGirderStopperconditionResult),
        trolleyGirderStopperreinforcementMemenuhi: getCheckmark(vi.trolleyGirderStopperreinforcementMemenuhi),
        trolleyGirderStopperreinforcementTidakMemenuhi: getOppositeCheckmark(vi.trolleyGirderStopperreinforcementTidakMemenuhi),
        trolleyGirderStopperreinforcementResult: vi.trolleyGirderStopperreinforcementResult || getNaValue(vi.trolleyGirderStopperreinforcementResult),
        windingDrumgrooveMemenuhi: getCheckmark(vi.windingDrumgrooveMemenuhi),
        windingDrumgrooveTidakMemenuhi: getOppositeCheckmark(vi.windingDrumgrooveTidakMemenuhi),
        windingDrumgrooveResult: vi.windingDrumgrooveResult || getNaValue(vi.windingDrumgrooveResult),
        windingDrumgrooveLipMemenuhi: getCheckmark(vi.windingDrumgrooveLipMemenuhi),
        windingDrumgrooveLipTidakMemenuhi: getOppositeCheckmark(vi.windingDrumgrooveLipTidakMemenuhi),
        windingDrumgrooveLipResult: vi.windingDrumgrooveLipResult || getNaValue(vi.windingDrumgrooveLipResult),
        windingDrumflangesMemenuhi: getCheckmark(vi.windingDrumflangesMemenuhi),
        windingDrumflangesTidakMemenuhi: getOppositeCheckmark(vi.windingDrumflangesTidakMemenuhi),
        windingDrumflangesResult: vi.windingDrumflangesResult || getNaValue(vi.windingDrumflangesResult),
        visualBrakeInspectionwearMemenuhi: getCheckmark(vi.visualBrakeInspectionwearMemenuhi),
        visualBrakeInspectionwearTidakMemenuhi: getOppositeCheckmark(vi.visualBrakeInspectionwearTidakMemenuhi),
        visualBrakeInspectionwearResult: vi.visualBrakeInspectionwearResult || getNaValue(vi.visualBrakeInspectionwearResult),
        visualBrakeInspectionadjustmentMemenuhi: getCheckmark(vi.visualBrakeInspectionadjustmentMemenuhi),
        visualBrakeInspectionadjustmentTidakMemenuhi: getOppositeCheckmark(vi.visualBrakeInspectionadjustmentTidakMemenuhi),
        visualBrakeInspectionadjustmentResult: vi.visualBrakeInspectionadjustmentResult || getNaValue(vi.visualBrakeInspectionadjustmentResult),
        hoistGearboxlubricationMemenuhi: getCheckmark(vi.hoistGearboxlubricationMemenuhi),
        hoistGearboxlubricationTidakMemenuhi: getOppositeCheckmark(vi.hoistGearboxlubricationTidakMemenuhi),
        hoistGearboxlubricationResult: vi.hoistGearboxlubricationResult || getNaValue(vi.hoistGearboxlubricationResult),
        hoistGearboxoilSealMemenuhi: getCheckmark(vi.hoistGearboxoilSealMemenuhi),
        hoistGearboxoilSealTidakMemenuhi: getOppositeCheckmark(vi.hoistGearboxoilSealTidakMemenuhi),
        hoistGearboxoilSealResult: vi.hoistGearboxoilSealResult || getNaValue(vi.hoistGearboxoilSealResult),
        pulleySprocketpulleyGrooveMemenuhi: getCheckmark(vi.pulleySprocketpulleyGrooveMemenuhi),
        pulleySprocketpulleyGrooveTidakMemenuhi: getOppositeCheckmark(vi.pulleySprocketpulleyGrooveTidakMemenuhi),
        pulleySprocketpulleyGrooveResult: vi.pulleySprocketpulleyGrooveResult || getNaValue(vi.pulleySprocketpulleyGrooveResult),
        pulleySprocketpulleyLipMemenuhi: getCheckmark(vi.pulleySprocketpulleyLipMemenuhi),
        pulleySprocketpulleyLipTidakMemenuhi: getOppositeCheckmark(vi.pulleySprocketpulleyLipTidakMemenuhi),
        pulleySprocketpulleyLipResult: vi.pulleySprocketpulleyLipResult || getNaValue(vi.pulleySprocketpulleyLipResult),
        pulleySprocketpulleyPinMemenuhi: getCheckmark(vi.pulleySprocketpulleyPinMemenuhi),
        pulleySprocketpulleyPinTidakMemenuhi: getOppositeCheckmark(vi.pulleySprocketpulleyPinTidakMemenuhi),
        pulleySprocketpulleyPinResult: vi.pulleySprocketpulleyPinResult || getNaValue(vi.pulleySprocketpulleyPinResult),
        pulleySprocketbearingMemenuhi: getCheckmark(vi.pulleySprocketbearingMemenuhi),
        pulleySprocketbearingTidakMemenuhi: getOppositeCheckmark(vi.pulleySprocketbearingTidakMemenuhi),
        pulleySprocketbearingResult: vi.pulleySprocketbearingResult || getNaValue(vi.pulleySprocketbearingResult),
        pulleySprocketpulleyGuardMemenuhi: getCheckmark(vi.pulleySprocketpulleyGuardMemenuhi),
        pulleySprocketpulleyGuardTidakMemenuhi: getOppositeCheckmark(vi.pulleySprocketpulleyGuardTidakMemenuhi),
        pulleySprocketpulleyGuardResult: vi.pulleySprocketpulleyGuardResult || getNaValue(vi.pulleySprocketpulleyGuardResult),
        pulleySprocketropeChainGuardMemenuhi: getCheckmark(vi.pulleySprocketropeChainGuardMemenuhi),
        pulleySprocketropeChainGuardTidakMemenuhi: getOppositeCheckmark(vi.pulleySprocketropeChainGuardTidakMemenuhi),
        pulleySprocketropeChainGuardResult: vi.pulleySprocketropeChainGuardResult || getNaValue(vi.pulleySprocketropeChainGuardResult),
        mainHookInspectionwearMemenuhi: getCheckmark(vi.mainHookInspectionwearMemenuhi),
        mainHookInspectionwearTidakMemenuhi: getOppositeCheckmark(vi.mainHookInspectionwearTidakMemenuhi),
        mainHookInspectionwearResult: vi.mainHookInspectionwearResult || getNaValue(vi.mainHookInspectionwearResult),
        mainHookInspectionhookOpeningGapMemenuhi: getCheckmark(vi.mainHookInspectionhookOpeningGapMemenuhi),
        mainHookInspectionhookOpeningGapTidakMemenuhi: getOppositeCheckmark(vi.mainHookInspectionhookOpeningGapTidakMemenuhi),
        mainHookInspectionhookOpeningGapResult: vi.mainHookInspectionhookOpeningGapResult || getNaValue(vi.mainHookInspectionhookOpeningGapResult),
        mainHookInspectionswivelNutAndBearingMemenuhi: getCheckmark(vi.mainHookInspectionswivelNutAndBearingMemenuhi),
        mainHookInspectionswivelNutAndBearingTidakMemenuhi: getOppositeCheckmark(vi.mainHookInspectionswivelNutAndBearingTidakMemenuhi),
        mainHookInspectionswivelNutAndBearingResult: vi.mainHookInspectionswivelNutAndBearingResult || getNaValue(vi.mainHookInspectionswivelNutAndBearingResult),
        mainHookInspectiontrunnionMemenuhi: getCheckmark(vi.mainHookInspectiontrunnionMemenuhi),
        mainHookInspectiontrunnionTidakMemenuhi: getOppositeCheckmark(vi.mainHookInspectiontrunnionTidakMemenuhi),
        mainHookInspectiontrunnionResult: vi.mainHookInspectiontrunnionResult || getNaValue(vi.mainHookInspectiontrunnionResult),
        auxiliaryHookInspectionwearMemenuhi: getCheckmark(vi.auxiliaryHookInspectionwearMemenuhi),
        auxiliaryHookInspectionwearTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryHookInspectionwearTidakMemenuhi),
        auxiliaryHookInspectionwearResult: vi.auxiliaryHookInspectionwearResult || getNaValue(vi.auxiliaryHookInspectionwearResult),
        auxiliaryHookInspectionhookOpeningGapMemenuhi: getCheckmark(vi.auxiliaryHookInspectionhookOpeningGapMemenuhi),
        auxiliaryHookInspectionhookOpeningGapTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryHookInspectionhookOpeningGapTidakMemenuhi),
        auxiliaryHookInspectionhookOpeningGapResult: vi.auxiliaryHookInspectionhookOpeningGapResult || getNaValue(vi.auxiliaryHookInspectionhookOpeningGapResult),
        auxiliaryHookInspectionswivelNutAndBearingMemenuhi: getCheckmark(vi.auxiliaryHookInspectionswivelNutAndBearingMemenuhi),
        auxiliaryHookInspectionswivelNutAndBearingTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryHookInspectionswivelNutAndBearingTidakMemenuhi),
        auxiliaryHookInspectionswivelNutAndBearingResult: vi.auxiliaryHookInspectionswivelNutAndBearingResult || getNaValue(vi.auxiliaryHookInspectionswivelNutAndBearingResult),
        auxiliaryHookInspectiontrunnionMemenuhi: getCheckmark(vi.auxiliaryHookInspectiontrunnionMemenuhi),
        auxiliaryHookInspectiontrunnionTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryHookInspectiontrunnionTidakMemenuhi),
        auxiliaryHookInspectiontrunnionResult: vi.auxiliaryHookInspectiontrunnionResult || getNaValue(vi.auxiliaryHookInspectiontrunnionResult),
        mainWireRopeInspectioncorrosionMemenuhi: getCheckmark(vi.mainWireRopeInspectioncorrosionMemenuhi),
        mainWireRopeInspectioncorrosionTidakMemenuhi: getOppositeCheckmark(vi.mainWireRopeInspectioncorrosionTidakMemenuhi),
        mainWireRopeInspectioncorrosionResult: vi.mainWireRopeInspectioncorrosionResult || getNaValue(vi.mainWireRopeInspectioncorrosionResult),
        mainWireRopeInspectionwearMemenuhi: getCheckmark(vi.mainWireRopeInspectionwearMemenuhi),
        mainWireRopeInspectionwearTidakMemenuhi: getOppositeCheckmark(vi.mainWireRopeInspectionwearTidakMemenuhi),
        mainWireRopeInspectionwearResult: vi.mainWireRopeInspectionwearResult || getNaValue(vi.mainWireRopeInspectionwearResult),
        mainWireRopeInspectionbreakageMemenuhi: getCheckmark(vi.mainWireRopeInspectionbreakageMemenuhi),
        mainWireRopeInspectionbreakageTidakMemenuhi: getOppositeCheckmark(vi.mainWireRopeInspectionbreakageTidakMemenuhi),
        mainWireRopeInspectionbreakageResult: vi.mainWireRopeInspectionbreakageResult || getNaValue(vi.mainWireRopeInspectionbreakageResult),
        mainWireRopeInspectiondeformationMemenuhi: getCheckmark(vi.mainWireRopeInspectiondeformationMemenuhi),
        mainWireRopeInspectiondeformationTidakMemenuhi: getOppositeCheckmark(vi.mainWireRopeInspectiondeformationTidakMemenuhi),
        mainWireRopeInspectiondeformationResult: vi.mainWireRopeInspectiondeformationResult || getNaValue(vi.mainWireRopeInspectiondeformationResult),
        auxiliaryWireRopeInspectioncorrosionMemenuhi: getCheckmark(vi.auxiliaryWireRopeInspectioncorrosionMemenuhi),
        auxiliaryWireRopeInspectioncorrosionTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryWireRopeInspectioncorrosionTidakMemenuhi),
        auxiliaryWireRopeInspectioncorrosionResult: vi.auxiliaryWireRopeInspectioncorrosionResult || getNaValue(vi.auxiliaryWireRopeInspectioncorrosionResult),
        auxiliaryWireRopeInspectionwearMemenuhi: getCheckmark(vi.auxiliaryWireRopeInspectionwearMemenuhi),
        auxiliaryWireRopeInspectionwearTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryWireRopeInspectionwearTidakMemenuhi),
        auxiliaryWireRopeInspectionwearResult: vi.auxiliaryWireRopeInspectionwearResult || getNaValue(vi.auxiliaryWireRopeInspectionwearResult),
        auxiliaryWireRopeInspectionbreakageMemenuhi: getCheckmark(vi.auxiliaryWireRopeInspectionbreakageMemenuhi),
        auxiliaryWireRopeInspectionbreakageTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryWireRopeInspectionbreakageTidakMemenuhi),
        auxiliaryWireRopeInspectionbreakageResult: vi.auxiliaryWireRopeInspectionbreakageResult || getNaValue(vi.auxiliaryWireRopeInspectionbreakageResult),
        auxiliaryWireRopeInspectiondeformationMemenuhi: getCheckmark(vi.auxiliaryWireRopeInspectiondeformationMemenuhi),
        auxiliaryWireRopeInspectiondeformationTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryWireRopeInspectiondeformationTidakMemenuhi),
        auxiliaryWireRopeInspectiondeformationResult: vi.auxiliaryWireRopeInspectiondeformationResult || getNaValue(vi.auxiliaryWireRopeInspectiondeformationResult),
        mainChainInspectioncorrosionMemenuhi: getCheckmark(vi.mainChainInspectioncorrosionMemenuhi),
        mainChainInspectioncorrosionTidakMemenuhi: getOppositeCheckmark(vi.mainChainInspectioncorrosionTidakMemenuhi),
        mainChainInspectioncorrosionResult: vi.mainChainInspectioncorrosionResult || getNaValue(vi.mainChainInspectioncorrosionResult),
        mainChainInspectionwearMemenuhi: getCheckmark(vi.mainChainInspectionwearMemenuhi),
        mainChainInspectionwearTidakMemenuhi: getOppositeCheckmark(vi.mainChainInspectionwearTidakMemenuhi),
        mainChainInspectionwearResult: vi.mainChainInspectionwearResult || getNaValue(vi.mainChainInspectionwearResult),
        mainChainInspectioncrackOrBreakageMemenuhi: getCheckmark(vi.mainChainInspectioncrackOrBreakageMemenuhi),
        mainChainInspectioncrackOrBreakageTidakMemenuhi: getOppositeCheckmark(vi.mainChainInspectioncrackOrBreakageTidakMemenuhi),
        mainChainInspectioncrackOrBreakageResult: vi.mainChainInspectioncrackOrBreakageResult || getNaValue(vi.mainChainInspectioncrackOrBreakageResult),
        mainChainInspectiondeformationMemenuhi: getCheckmark(vi.mainChainInspectiondeformationMemenuhi),
        mainChainInspectiondeformationTidakMemenuhi: getOppositeCheckmark(vi.mainChainInspectiondeformationTidakMemenuhi),
        mainChainInspectiondeformationResult: vi.mainChainInspectiondeformationResult || getNaValue(vi.mainChainInspectiondeformationResult),
        auxiliaryChainInspectioncorrosionMemenuhi: getCheckmark(vi.auxiliaryChainInspectioncorrosionMemenuhi),
        auxiliaryChainInspectioncorrosionTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryChainInspectioncorrosionTidakMemenuhi),
        auxiliaryChainInspectioncorrosionResult: vi.auxiliaryChainInspectioncorrosionResult || getNaValue(vi.auxiliaryChainInspectioncorrosionResult),
        auxiliaryChainInspectionwearMemenuhi: getCheckmark(vi.auxiliaryChainInspectionwearMemenuhi),
        auxiliaryChainInspectionwearTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryChainInspectionwearTidakMemenuhi),
        auxiliaryChainInspectionwearResult: vi.auxiliaryChainInspectionwearResult || getNaValue(vi.auxiliaryChainInspectionwearResult),
        auxiliaryChainInspectioncrackOrBreakageMemenuhi: getCheckmark(vi.auxiliaryChainInspectioncrackOrBreakageMemenuhi),
        auxiliaryChainInspectioncrackOrBreakageTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryChainInspectioncrackOrBreakageTidakMemenuhi),
        auxiliaryChainInspectioncrackOrBreakageResult: vi.auxiliaryChainInspectioncrackOrBreakageResult || getNaValue(vi.auxiliaryChainInspectioncrackOrBreakageResult),
        auxiliaryChainInspectiondeformationMemenuhi: getCheckmark(vi.auxiliaryChainInspectiondeformationMemenuhi),
        auxiliaryChainInspectiondeformationTidakMemenuhi: getOppositeCheckmark(vi.auxiliaryChainInspectiondeformationTidakMemenuhi),
        auxiliaryChainInspectiondeformationResult: vi.auxiliaryChainInspectiondeformationResult || getNaValue(vi.auxiliaryChainInspectiondeformationResult),
        limitSwitchlongTravelMemenuhi: getCheckmark(vi.limitSwitchlongTravelMemenuhi),
        limitSwitchlongTravelTidakMemenuhi: getOppositeCheckmark(vi.limitSwitchlongTravelTidakMemenuhi),
        limitSwitchlongTravelResult: vi.limitSwitchlongTravelResult || getNaValue(vi.limitSwitchlongTravelResult),
        limitSwitchcrossTravelMemenuhi: getCheckmark(vi.limitSwitchcrossTravelMemenuhi),
        limitSwitchcrossTravelTidakMemenuhi: getOppositeCheckmark(vi.limitSwitchcrossTravelTidakMemenuhi),
        limitSwitchcrossTravelResult: vi.limitSwitchcrossTravelResult || getNaValue(vi.limitSwitchcrossTravelResult),
        limitSwitchhoistMemenuhi: getCheckmark(vi.limitSwitchhoistMemenuhi),
        limitSwitchhoistTidakMemenuhi: getOppositeCheckmark(vi.limitSwitchhoistTidakMemenuhi),
        limitSwitchhoistResult: vi.limitSwitchhoistResult || getNaValue(vi.limitSwitchhoistResult),
        operatorCabinsafetyLadderMemenuhi: getCheckmark(vi.operatorCabinsafetyLadderMemenuhi),
        operatorCabinsafetyLadderTidakMemenuhi: getOppositeCheckmark(vi.operatorCabinsafetyLadderTidakMemenuhi),
        operatorCabinsafetyLadderResult: vi.operatorCabinsafetyLadderResult || getNaValue(vi.operatorCabinsafetyLadderResult),
        operatorCabindoorMemenuhi: getCheckmark(vi.operatorCabindoorMemenuhi),
        operatorCabindoorTidakMemenuhi: getOppositeCheckmark(vi.operatorCabindoorTidakMemenuhi),
        operatorCabindoorResult: vi.operatorCabindoorResult || getNaValue(vi.operatorCabindoorResult),
        operatorCabinwindowMemenuhi: getCheckmark(vi.operatorCabinwindowMemenuhi),
        operatorCabinwindowTidakMemenuhi: getOppositeCheckmark(vi.operatorCabinwindowTidakMemenuhi),
        operatorCabinwindowResult: vi.operatorCabinwindowResult || getNaValue(vi.operatorCabinwindowResult),
        operatorCabinfanOrACMemenuhi: getCheckmark(vi.operatorCabinfanOrACMemenuhi),
        operatorCabinfanOrACTidakMemenuhi: getOppositeCheckmark(vi.operatorCabinfanOrACTidakMemenuhi),
        operatorCabinfanOrACResult: vi.operatorCabinfanOrACResult || getNaValue(vi.operatorCabinfanOrACResult),
        operatorCabincontrolLeversOrButtonsMemenuhi: getCheckmark(vi.operatorCabincontrolLeversOrButtonsMemenuhi),
        operatorCabincontrolLeversOrButtonsTidakMemenuhi: getOppositeCheckmark(vi.operatorCabincontrolLeversOrButtonsTidakMemenuhi),
        operatorCabincontrolLeversOrButtonsResult: vi.operatorCabincontrolLeversOrButtonsResult || getNaValue(vi.operatorCabincontrolLeversOrButtonsResult),
        operatorCabinpendantControlMemenuhi: getCheckmark(vi.operatorCabinpendantControlMemenuhi),
        operatorCabinpendantControlTidakMemenuhi: getOppositeCheckmark(vi.operatorCabinpendantControlTidakMemenuhi),
        operatorCabinpendantControlResult: vi.operatorCabinpendantControlResult || getNaValue(vi.operatorCabinpendantControlResult),
        operatorCabinlightingMemenuhi: getCheckmark(vi.operatorCabinlightingMemenuhi),
        operatorCabinlightingTidakMemenuhi: getOppositeCheckmark(vi.operatorCabinlightingTidakMemenuhi),
        operatorCabinlightingResult: vi.operatorCabinlightingResult || getNaValue(vi.operatorCabinlightingResult),
        operatorCabinhornMemenuhi: getCheckmark(vi.operatorCabinhornMemenuhi),
        operatorCabinhornTidakMemenuhi: getOppositeCheckmark(vi.operatorCabinhornTidakMemenuhi),
        operatorCabinhornResult: vi.operatorCabinhornResult || getNaValue(vi.operatorCabinhornResult),
        operatorCabinfuseProtectionMemenuhi: getCheckmark(vi.operatorCabinfuseProtectionMemenuhi),
        operatorCabinfuseProtectionTidakMemenuhi: getOppositeCheckmark(vi.operatorCabinfuseProtectionTidakMemenuhi),
        operatorCabinfuseProtectionResult: vi.operatorCabinfuseProtectionResult || getNaValue(vi.operatorCabinfuseProtectionResult),
        operatorCabincommunicationDeviceMemenuhi: getCheckmark(vi.operatorCabincommunicationDeviceMemenuhi),
        operatorCabincommunicationDeviceTidakMemenuhi: getOppositeCheckmark(vi.operatorCabincommunicationDeviceTidakMemenuhi),
        operatorCabincommunicationDeviceResult: vi.operatorCabincommunicationDeviceResult || getNaValue(vi.operatorCabincommunicationDeviceResult),
        operatorCabinfireExtinguisherMemenuhi: getCheckmark(vi.operatorCabinfireExtinguisherMemenuhi),
        operatorCabinfireExtinguisherTidakMemenuhi: getOppositeCheckmark(vi.operatorCabinfireExtinguisherTidakMemenuhi),
        operatorCabinfireExtinguisherResult: vi.operatorCabinfireExtinguisherResult || getNaValue(vi.operatorCabinfireExtinguisherResult),
        operatorCabinoperationalSignsMemenuhi: getCheckmark(vi.operatorCabinoperationalSignsMemenuhi),
        operatorCabinoperationalSignsTidakMemenuhi: getOppositeCheckmark(vi.operatorCabinoperationalSignsTidakMemenuhi),
        operatorCabinoperationalSignsResult: vi.operatorCabinoperationalSignsResult || getNaValue(vi.operatorCabinoperationalSignsResult),
        operatorCabinignitionOrMasterSwitchMemenuhi: getCheckmark(vi.operatorCabinignitionOrMasterSwitchMemenuhi),
        operatorCabinignitionOrMasterSwitchTidakMemenuhi: getOppositeCheckmark(vi.operatorCabinignitionOrMasterSwitchTidakMemenuhi),
        operatorCabinignitionOrMasterSwitchResult: vi.operatorCabinignitionOrMasterSwitchResult || getNaValue(vi.operatorCabinignitionOrMasterSwitchResult),
        electricalComponentspanelConductorConnectorMemenuhi: getCheckmark(vi.electricalComponentspanelConductorConnectorMemenuhi),
        electricalComponentspanelConductorConnectorTidakMemenuhi: getOppositeCheckmark(vi.electricalComponentspanelConductorConnectorTidakMemenuhi),
        electricalComponentspanelConductorConnectorResult: vi.electricalComponentspanelConductorConnectorResult || getNaValue(vi.electricalComponentspanelConductorConnectorResult),
        electricalComponentsconductorProtectionMemenuhi: getCheckmark(vi.electricalComponentsconductorProtectionMemenuhi),
        electricalComponentsconductorProtectionTidakMemenuhi: getOppositeCheckmark(vi.electricalComponentsconductorProtectionTidakMemenuhi),
        electricalComponentsconductorProtectionResult: vi.electricalComponentsconductorProtectionResult || getNaValue(vi.electricalComponentsconductorProtectionResult),
        electricalComponentsmotorInstallationSafetySystemMemenuhi: getCheckmark(vi.electricalComponentsmotorInstallationSafetySystemMemenuhi),
        electricalComponentsmotorInstallationSafetySystemTidakMemenuhi: getOppositeCheckmark(vi.electricalComponentsmotorInstallationSafetySystemTidakMemenuhi),
        electricalComponentsmotorInstallationSafetySystemResult: vi.electricalComponentsmotorInstallationSafetySystemResult || getNaValue(vi.electricalComponentsmotorInstallationSafetySystemResult),
        electricalComponentsgroundingSystemMemenuhi: getCheckmark(vi.electricalComponentsgroundingSystemMemenuhi),
        electricalComponentsgroundingSystemTidakMemenuhi: getOppositeCheckmark(vi.electricalComponentsgroundingSystemTidakMemenuhi),
        electricalComponentsgroundingSystemResult: vi.electricalComponentsgroundingSystemResult || getNaValue(vi.electricalComponentsgroundingSystemResult),
        electricalComponentsinstallationMemenuhi: getCheckmark(vi.electricalComponentsinstallationMemenuhi),
        electricalComponentsinstallationTidakMemenuhi: getOppositeCheckmark(vi.electricalComponentsinstallationTidakMemenuhi),
        electricalComponentsinstallationResult: vi.electricalComponentsinstallationResult || getNaValue(vi.electricalComponentsinstallationResult),

        // NDT
        wireropeMethod: ndt.wireropeMethod || '',
        wirerope: ndt.wirerope || [], // Data dinamis
        HookspecA: ndt.HookspecA || '',
        HookspecB: ndt.HookspecB || '',
        HookspecC: ndt.HookspecC || '',
        HookspecD: ndt.HookspecD || '',
        HookspecE: ndt.HookspecE || '',
        HookspecF: ndt.HookspecF || '',
        HookspecG: ndt.HookspecG || '',
        HookspecH: ndt.HookspecH || '',
        HookspecBaik: getCheckmark(ndt.HookspecBaik),
        HookspecTidakBaik: getOppositeCheckmark(ndt.HookspecTidakBaik),
        HookspecDesc: ndt.HookspecDesc || '',
        measurementResultsA: ndt.measurementResultsA || '',
        measurementResultsB: ndt.measurementResultsB || '',
        measurementResultsC: ndt.measurementResultsC || '',
        measurementResultsD: ndt.measurementResultsD || '',
        measurementResultsE: ndt.measurementResultsE || '',
        measurementResultsF: ndt.measurementResultsF || '',
        measurementResultsG: ndt.measurementResultsG || '',
        measurementResultsH: ndt.measurementResultsH || '',
        measurementResultsBaik: getCheckmark(ndt.measurementResultsBaik),
        measurementResultsTidakBaik: getOppositeCheckmark(ndt.measurementResultsTidakBaik),
        measurementResultsDesc: ndt.measurementResultsDesc || '',
        toleranceA: ndt.toleranceA || '',
        toleranceB: ndt.toleranceB || '',
        toleranceC: ndt.toleranceC || '',
        toleranceD: ndt.toleranceD || '',
        toleranceE: ndt.toleranceE || '',
        toleranceF: ndt.toleranceF || '',
        toleranceG: ndt.toleranceG || '',
        toleranceH: ndt.toleranceH || '',
        toleranceBaik: getCheckmark(ndt.toleranceBaik),
        toleranceTidakBaik: getOppositeCheckmark(ndt.toleranceTidakBaik),
        toleranceDesc: ndt.toleranceDesc || '',
        griderMethod: ndt.griderMethod || '',
        girder: ndt.girder || [], // Data dinamis

        // Dynamic Testing
        travellingStatus: dyn.travellingStatus || '',
        travellingDesc: dyn.travellingDesc || '',
        traversingStatus: dyn.traversingStatus || '',
        traversingDesc: dyn.traversingDesc || '',
        hoistingStatus: dyn.hoistingStatus || '',
        hoistingDesc: dyn.hoistingDesc || '',
        safetyDeviceStatus: dyn.safetyDeviceStatus || '',
        safetyDeviceDesc: dyn.safetyDeviceDesc || '',
        brakeSwitchStatus: dyn.brakeSwitchStatus || '',
        brakeSwitchDesc: dyn.brakeSwitchDesc || '',
        brakeLockingStatus: dyn.brakeLockingStatus || '',
        brakeLockingDesc: dyn.brakeLockingDesc || '',
        instalasionElectricStatus: dyn.instalasionElectricStatus || '',
        instalasionElectricDesc: dyn.instalasionElectricDesc || '',
        hoist25: dyn.hoist25 || '',
        travesing25: dyn.travesing25 || '',
        travelling25: dyn.travelling25 || '',
        brakeSystem25: dyn.brakeSystem25 || '',
        desc25: dyn.desc25 || '',
        hoist50: dyn.hoist50 || '',
        travesing50: dyn.travesing50 || '',
        travelling50: dyn.travelling50 || '',
        brakeSystem50: dyn.brakeSystem50 || '',
        desc50: dyn.desc50 || '',
        hoist75: dyn.hoist75 || '',
        travesing75: dyn.travesing75 || '',
        travelling75: dyn.travelling75 || '',
        brakeSystem75: dyn.brakeSystem75 || '',
        desc75: dyn.desc75 || '',
        hoist100: dyn.hoist100 || '',
        travesing100: dyn.travesing100 || '',
        travelling100: dyn.travelling100 || '',
        brakeSystem100: dyn.brakeSystem100 || '',
        desc100: dyn.desc100 || '',

        // Static Testing
        loadTest: stat.loadTest || '',
        basedDesign: stat.basedDesign || '',
        lengthSpan: stat.lengthSpan || '',
        xspan: stat.xspan || '',
        resultDefleksi: stat.resultDefleksi || '',
        defleksi: stat.defleksi || [], // Data dinamis

        // Conclusion & Recommendation
        conclusion: data.conclusion || '',
        recomendation: data.recomendation || '',
    };

    try {
        doc.render(renderData);
    } catch (error) {
        console.error("GAGAL RENDER DOKUMEN:", error.message);
        const e = {
            message: error.message,
            name: error.name,
            stack: error.stack,
            properties: error.properties,
        };
        console.log(JSON.stringify({ error: e }));
        throw error;
    }

    const docxBuffer = doc.getZip().generate({ type: 'nodebuffer', compression: 'DEFLATE' });
    const ownerName = (g.companyName || 'UnknownCompany').replace(/[^\w.-]/g, '_'); // Menggunakan companyName
    const fileName = `Laporan-GantryCrane-${ownerName}-${data.reportNumber || data.id}.docx`; // Menggunakan reportNumber atau ID

    return { docxBuffer, fileName };
};

module.exports = {
    createLaporanGantryCrane,
};