'use strict';

const Joi = require('joi');

/**
 * Skema bantuan untuk item inspeksi yang memiliki properti 'result' dan 'status'.
 * Ini akan digunakan kembali untuk semua item pemeriksaan visual dan fungsional.
 */
const inspectionItemSchema = Joi.object({
    result: Joi.string().allow('', null).optional(),
    status: Joi.boolean().allow(null).optional()
});

/**
 * Skema validasi utama untuk payload laporan Mobile Crane.
 * Setiap field didefinisikan secara eksplisit agar sesuai dengan data yang dikirim.
 */
const laporanMobileCranePayload = Joi.object({
    // Data Header
    inspectionType: Joi.string().allow('', null).optional(),
    equipmentType: Joi.string().allow('', null).optional(),
    examinationType: Joi.string().allow('', null).optional(),
    subInspectionType: Joi.string().allow('', null).optional(),

    // Data Umum
    generalData: Joi.object({
        generalDataOwnerName: Joi.string().allow('', null).optional(),
        generalDataOwnerAddress: Joi.string().allow('', null).optional(),
        generalDataUserSubcontractorPersonInCharge: Joi.string().allow('', null).optional(),
        generalDataUserAddress: Joi.string().allow('', null).optional(),
        generalDataUnitLocation: Joi.string().allow('', null).optional(),
        generalDataOperatorName: Joi.string().allow('', null).optional(),
        generalDataManufacturer: Joi.string().allow('', null).optional(),
        generalDataBrandType: Joi.string().allow('', null).optional(),
        generalDataLocationAndYearOfManufacture: Joi.string().allow('', null).optional(),
        generalDataSerialNumberUnitNumber: Joi.string().allow('', null).optional(),
        generalDataCapacityWorkingLoad: Joi.string().allow('', null).optional(),
        generalDataIntendedUse: Joi.string().allow('', null).optional(),
        generalDataUsagePermitNumber: Joi.string().allow('', null).optional(),
        generalDataOperatorCertificate: Joi.string().allow('', null).optional(),
        generalDataEquipmentHistory: Joi.string().allow('', null).optional(),
        generalDataInspectionDate: Joi.string().allow('', null).optional()
    }).optional(),

    // Data Teknis
    technicalData: Joi.object({
        technicalDataMaximumWorkingLoadCapacity: Joi.string().allow('', null).optional(),
        technicalDataBoomLength: Joi.string().allow('', null).optional(),
        technicalDataMaximumJibLength: Joi.string().allow('', null).optional(),
        technicalDataMaximumJibWorkingLoad: Joi.string().allow('', null).optional(),
        technicalDataMaxBoomJibLength: Joi.string().allow('', null).optional(),
        technicalDataCraneWeight: Joi.string().allow('', null).optional(),
        technicalDataMaxLiftingHeight: Joi.string().allow('', null).optional(),
        technicalDataBoomWorkingAngle: Joi.string().allow('', null).optional(),
        technicalDataEngineNumber: Joi.string().allow('', null).optional(),
        technicalDataType: Joi.string().allow('', null).optional(),
        technicalDataNumberOfCylinders: Joi.string().allow('', null).optional(),
        technicalDataNetPower: Joi.string().allow('', null).optional(),
        technicalDataBrandYearOfManufacture: Joi.string().allow('', null).optional(),
        technicalDataHookManufacturer: Joi.string().allow('', null).optional(),
        technicalDataMainHookType: Joi.string().allow('', null).optional(),
        technicalDataMainHookCapacity: Joi.string().allow('', null).optional(),
        technicalDataMainHookMaterial: Joi.string().allow('', null).optional(),
        technicalDataMainHookSerialNumber: Joi.string().allow('', null).optional(),
        technicalDataAuxiliaryHookType: Joi.string().allow('', null).optional(),
        technicalDataAuxiliaryHookCapacity: Joi.string().allow('', null).optional(),
        technicalDataAuxiliaryHookMaterial: Joi.string().allow('', null).optional(),
        technicalDataAuxiliaryHookSerialNumber: Joi.string().allow('', null).optional(),
        technicalDataWireRopeMainLoadHoistDrumDiameter: Joi.string().allow('', null).optional(),
        technicalDataWireRopeMainLoadHoistDrumType: Joi.string().allow('', null).optional(),
        technicalDataWireRopeMainLoadHoistDrumConstruction: Joi.string().allow('', null).optional(),
        technicalDataWireRopeMainLoadHoistDrumBreakingStrength: Joi.string().allow('', null).optional(),
        technicalDataWireRopeMainLoadHoistDrumLength: Joi.string().allow('', null).optional(),
        technicalDataWireRopeAuxiliaryLoadHoistDrumDiameter: Joi.string().allow('', null).optional(),
        technicalDataWireRopeAuxiliaryLoadHoistDrumType: Joi.string().allow('', null).optional(),
        technicalDataWireRopeAuxiliaryLoadHoistDrumConstruction: Joi.string().allow('', null).optional(),
        technicalDataWireRopeAuxiliaryLoadHoistDrumLength: Joi.string().allow('', null).optional(),
        technicalDataWireRopeAuxiliaryLoadHoistDrumBreakingStrength: Joi.string().allow('', null).optional(),
        technicalDataWireRopeBoomHoistDrumDiameter: Joi.string().allow('', null).optional(),
        technicalDataWireRopeBoomHoistDrumType: Joi.string().allow('', null).optional(),
        technicalDataWireRopeBoomHoistDrumConstruction: Joi.string().allow('', null).optional(),
        technicalDataWireRopeBoomHoistDrumLength: Joi.string().allow('', null).optional(),
        technicalDataWireRopeBoomHoistDrumBreakingStrength: Joi.string().allow('', null).optional()
    }).optional(),

    // Data Pemeriksaan dan Pengujian (semua field didefinisikan secara eksplisit)
    inspectionAndTesting: Joi.object({
        visualFoundationAndBoltsCorrosionResult: inspectionItemSchema.optional(),
        visualFoundationAndBoltsCracksResult: inspectionItemSchema.optional(),
        visualFoundationAndBoltsDeformationResult: inspectionItemSchema.optional(),
        visualFoundationAndBoltsTightnessResult: inspectionItemSchema.optional(),
        visualFrameColumnsOnFoundationCorrosionResult: inspectionItemSchema.optional(),
        visualFrameColumnsOnFoundationCracksResult: inspectionItemSchema.optional(),
        visualFrameColumnsOnFoundationDeformationResult: inspectionItemSchema.optional(),
        visualFrameColumnsOnFoundationFasteningResult: inspectionItemSchema.optional(),
        visualFrameColumnsOnFoundationTransverseReinforcementResult: inspectionItemSchema.optional(),
        visualFrameColumnsOnFoundationDiagonalReinforcementResult: inspectionItemSchema.optional(),
        visualLadderCorrosionResult: inspectionItemSchema.optional(),
        visualLadderCracksResult: inspectionItemSchema.optional(),
        visualLadderDeformationResult: inspectionItemSchema.optional(),
        visualLadderFasteningResult: inspectionItemSchema.optional(),
        visualWorkingPlatformCorrosionResult: inspectionItemSchema.optional(),
        visualWorkingPlatformCracksResult: inspectionItemSchema.optional(),
        visualWorkingPlatformDeformationResult: inspectionItemSchema.optional(),
        visualWorkingPlatformFasteningResult: inspectionItemSchema.optional(),
        visualOutriggersOutriggerArmHousingResult: inspectionItemSchema.optional(),
        visualOutriggersOutriggerArmsResult: inspectionItemSchema.optional(),
        visualOutriggersJackResult: inspectionItemSchema.optional(),
        visualOutriggersOutriggerPadsResult: inspectionItemSchema.optional(),
        visualOutriggersHousingConnectionToChassisResult: inspectionItemSchema.optional(),
        visualOutriggersOutriggerSafetyLocksResult: inspectionItemSchema.optional(),
        visualTurntableSlewingRollerBearingResult: inspectionItemSchema.optional(),
        visualTurntableBrakeHousingResult: inspectionItemSchema.optional(),
        visualTurntableBrakeLiningsAndShoesResult: inspectionItemSchema.optional(),
        visualTurntableDrumSurfaceResult: inspectionItemSchema.optional(),
        visualTurntablePressureCylinderResult: inspectionItemSchema.optional(),
        visualTurntableDrumAxleResult: inspectionItemSchema.optional(),
        visualTurntableLeversPinsBoltsResult: inspectionItemSchema.optional(),
        visualTurntableGuardResult: inspectionItemSchema.optional(),
        visualLatticeBoomMainBoomResult: inspectionItemSchema.optional(),
        visualLatticeBoomBoomSectionResult: inspectionItemSchema.optional(),
        visualLatticeBoomTopPulleyResult: inspectionItemSchema.optional(),
        visualLatticeBoomPulleyGuardResult: inspectionItemSchema.optional(),
        visualLatticeBoomWireRopeGuardResult: inspectionItemSchema.optional(),
        visualLatticeBoomPulleyGrooveLipResult: inspectionItemSchema.optional(),
        visualLatticeBoomPivotPinResult: inspectionItemSchema.optional(),
        visualLatticeBoomWireRopeGuidePulleyResult: inspectionItemSchema.optional(),
        visualSteeringMainClutchResult: inspectionItemSchema.optional(),
        visualTransmissionResult: inspectionItemSchema.optional(),
        visualSteeringFrontWheelResult: inspectionItemSchema.optional(),
        visualSteeringMiddleWheelResult: inspectionItemSchema.optional(),
        visualSteeringRearWheelResult: inspectionItemSchema.optional(),
        visualBrakeServiceBrakeResult: inspectionItemSchema.optional(),
        visualBrakeParkingBrakeResult: inspectionItemSchema.optional(),
        visualBrakeBrakeHousingResult: inspectionItemSchema.optional(),
        visualBrakeBrakeLiningsAndShoesResult: inspectionItemSchema.optional(),
        visualBrakeDrumSurfaceResult: inspectionItemSchema.optional(),
        visualBrakeLeversPinsBoltsResult: inspectionItemSchema.optional(),
        visualBrakeGuardResult: inspectionItemSchema.optional(),
        visualTravelDrumClutchHousingResult: inspectionItemSchema.optional(),
        visualTravelDrumClutchLiningResult: inspectionItemSchema.optional(),
        visualTravelDrumClutchDrumSurfaceResult: inspectionItemSchema.optional(),
        visualTravelDrumLeversPinsBoltsResult: inspectionItemSchema.optional(),
        visualTravelDrumGuardResult: inspectionItemSchema.optional(),
        visualMainWinchDrumMountingResult: inspectionItemSchema.optional(),
        visualMainWinchWindingDrumSurfaceResult: inspectionItemSchema.optional(),
        visualMainWinchBrakeLiningsAndShoesResult: inspectionItemSchema.optional(),
        visualMainWinchBrakeDrumSurfaceResult: inspectionItemSchema.optional(),
        visualMainWinchBrakeHousingResult: inspectionItemSchema.optional(),
        visualMainWinchClutchLiningsAndShoesResult: inspectionItemSchema.optional(),
        visualMainWinchClutchDrumSurfaceResult: inspectionItemSchema.optional(),
        visualMainWinchGrooveResult: inspectionItemSchema.optional(),
        visualMainWinchGrooveLipResult: inspectionItemSchema.optional(),
        visualMainWinchFlangesResult: inspectionItemSchema.optional(),
        visualMainWinchBrakeActuatorLeversPinsAndBoltsResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchDrumMountingResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchWindingDrumSurfaceResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchBrakeLiningsAndShoesResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchBrakeDrumSurfaceResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchBrakeHousingResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchClutchLiningsAndShoesResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchClutchDrumSurfaceResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchGrooveResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchGrooveLipResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchFlangesResult: inspectionItemSchema.optional(),
        visualAuxiliaryWinchBrakeActuatorLeversPinsAndBoltsResult: inspectionItemSchema.optional(),
        visualHoistGearBlockLubricationResult: inspectionItemSchema.optional(),
        visualHoistGearBlockOilSealResult: inspectionItemSchema.optional(),
        visualMainPulleyPulleyGrooveResult: inspectionItemSchema.optional(),
        visualMainPulleyPulleyGrooveLipResult: inspectionItemSchema.optional(),
        visualMainPulleyPulleyPinResult: inspectionItemSchema.optional(),
        visualMainPulleyBearingResult: inspectionItemSchema.optional(),
        visualMainPulleyPulleyGuardResult: inspectionItemSchema.optional(),
        visualMainPulleyWireRopeGuardResult: inspectionItemSchema.optional(),
        visualMainHookSwivelNutAndBearingResult: inspectionItemSchema.optional(),
        visualMainHookTrunnionResult: inspectionItemSchema.optional(),
        visualMainHookSafetyLatchResult: inspectionItemSchema.optional(),
        visualAuxiliaryHookFreeFallWeightResult: inspectionItemSchema.optional(),
        visualAuxiliaryHookSwivelNutAndBearingResult: inspectionItemSchema.optional(),
        visualAuxiliaryHookSafetyLatchResult: inspectionItemSchema.optional(),
        visualMainWireRopeCorrosionResult: inspectionItemSchema.optional(),
        visualMainWireRopeWearResult: inspectionItemSchema.optional(),
        visualMainWireRopeBreakageResult: inspectionItemSchema.optional(),
        visualMainWireRopeDeformationResult: inspectionItemSchema.optional(),
        visualAuxiliaryWireRopeCorrosionResult: inspectionItemSchema.optional(),
        visualAuxiliaryWireRopeWearResult: inspectionItemSchema.optional(),
        visualAuxiliaryWireRopeBreakageResult: inspectionItemSchema.optional(),
        visualAuxiliaryWireRopeDeformationResult: inspectionItemSchema.optional(),
        visualLimitSwitchLongTravelResult: inspectionItemSchema.optional(),
        visualLimitSwitchCrossTravelResult: inspectionItemSchema.optional(),
        visualLimitSwitchHoistingResult: inspectionItemSchema.optional(),
        visualInternalCombustionEngineCoolingSystemResult: inspectionItemSchema.optional(),
        visualInternalCombustionEngineLubricationSystemResult: inspectionItemSchema.optional(),
        visualInternalCombustionEngineEngineMountingResult: inspectionItemSchema.optional(),
        visualInternalCombustionEngineSafetyGuardEquipmentResult: inspectionItemSchema.optional(),
        visualInternalCombustionEngineExhaustSystemResult: inspectionItemSchema.optional(),
        visualInternalCombustionEngineFuelSystemResult: inspectionItemSchema.optional(),
        visualInternalCombustionEnginePowerTransmissionSystemResult: inspectionItemSchema.optional(),
        visualInternalCombustionEngineBatteryResult: inspectionItemSchema.optional(),
        visualInternalCombustionEngineStarterMotorResult: inspectionItemSchema.optional(),
        visualInternalCombustionEngineWiringInstallationResult: inspectionItemSchema.optional(),
        visualInternalCombustionEngineTurbochargerResult: inspectionItemSchema.optional(),
        visualHydraulicPumpResult: inspectionItemSchema.optional(),
        visualHydraulicLinesResult: inspectionItemSchema.optional(),
        visualHydraulicFilterResult: inspectionItemSchema.optional(),
        visualHydraulicTankResult: inspectionItemSchema.optional(),
        visualHydraulicMainWinchMotorResult: inspectionItemSchema.optional(),
        visualHydraulicAuxiliaryWinchMotorResult: inspectionItemSchema.optional(),
        visualHydraulicBoomWinchMotorResult: inspectionItemSchema.optional(),
        visualHydraulicSwingMotorResult: inspectionItemSchema.optional(),
        visualControlValveReliefValveResult: inspectionItemSchema.optional(),
        visualControlValveMainWinchValveResult: inspectionItemSchema.optional(),
        visualControlValveAuxiliaryWinchValveResult: inspectionItemSchema.optional(),
        visualControlValveBoomWinchValveResult: inspectionItemSchema.optional(),
        visualControlValveBoomMovementValveResult: inspectionItemSchema.optional(),
        visualControlValveSteeringCylinderValveResult: inspectionItemSchema.optional(),
        visualControlValveAxleOscillationValveResult: inspectionItemSchema.optional(),
        visualControlValveOutriggerMovementValveResult: inspectionItemSchema.optional(),
        visualHydraulicCylinderBoomMovementCylinderResult: inspectionItemSchema.optional(),
        visualHydraulicCylinderOutriggerCylinderResult: inspectionItemSchema.optional(),
        visualHydraulicCylinderSteeringWheelCylinderResult: inspectionItemSchema.optional(),
        visualHydraulicCylinderAxleOscillationCylinderResult: inspectionItemSchema.optional(),
        visualHydraulicCylinderTelescopicCylinderResult: inspectionItemSchema.optional(),
        visualPneumaticCompressorResult: inspectionItemSchema.optional(),
        visualPneumaticTankAndSafetyValveResult: inspectionItemSchema.optional(),
        visualPneumaticPressurizedAirLinesResult: inspectionItemSchema.optional(),
        visualPneumaticAirFilterResult: inspectionItemSchema.optional(),
        visualPneumaticControlValveResult: inspectionItemSchema.optional(),
        visualOperatorCabinSafetyLadderResult: inspectionItemSchema.optional(),
        visualOperatorCabinDoorResult: inspectionItemSchema.optional(),
        visualOperatorCabinWindowResult: inspectionItemSchema.optional(),
        visualOperatorCabinFanAcResult: inspectionItemSchema.optional(),
        visualOperatorCabinControlLeversButtonsResult: inspectionItemSchema.optional(),
        visualOperatorCabinPendantControlResult: inspectionItemSchema.optional(),
        visualOperatorCabinLightingResult: inspectionItemSchema.optional(),
        visualOperatorCabinHornSignalAlarmResult: inspectionItemSchema.optional(),
        visualOperatorCabinFuseResult: inspectionItemSchema.optional(),
        visualOperatorCabinCommunicationDeviceResult: inspectionItemSchema.optional(),
        visualOperatorCabinFireExtinguisherResult: inspectionItemSchema.optional(),
        visualOperatorCabinOperatingSignsResult: inspectionItemSchema.optional(),
        visualOperatorCabinIgnitionKeyMasterSwitchResult: inspectionItemSchema.optional(),
        visualOperatorCabinButtonsHandlesLeversResult: inspectionItemSchema.optional(),
        visualElectricalComponentsPanelConductorConnectorResult: inspectionItemSchema.optional(),
        visualElectricalComponentsConductorProtectionResult: inspectionItemSchema.optional(),
        visualElectricalComponentsMotorInstallationSafetySystemResult: inspectionItemSchema.optional(),
        visualElectricalComponentsGroundingSystemResult: inspectionItemSchema.optional(),
        visualElectricalComponentsInstallationResult: inspectionItemSchema.optional(),
        visualSafetyDevicesLadderHandrailResult: inspectionItemSchema.optional(),
        visualSafetyDevicesEngineOilLubricantPressureResult: inspectionItemSchema.optional(),
        visualSafetyDevicesHydraulicOilPressureResult: inspectionItemSchema.optional(),
        visualSafetyDevicesAirPressureResult: inspectionItemSchema.optional(),
        visualSafetyDevicesAmperemeterResult: inspectionItemSchema.optional(),
        visualSafetyDevicesVoltageResult: inspectionItemSchema.optional(),
        visualSafetyDevicesEngineTemperatureResult: inspectionItemSchema.optional(),
        visualSafetyDevicesTransmissionTemperatureResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterOilTemperaturePressureResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterSpeedometerIndicatorResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterRotaryLampResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterMainHoistRopeUpDownLimitResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterAuxiliaryHoistRopeUpDownLimitResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterSwingMotionLimitResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterLevelIndicatorResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterLoadWeightIndicatorResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterLoadChartResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterAnemometerWindSpeedResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterBoomAngleIndicatorResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterAirPressureIndicatorResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterHydraulicPressureIndicatorResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterSafetyValvesResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterMainWindingDrumSafetyLockResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterAuxiliaryWindingDrumSafetyLockResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterTelescopicMotionLimitResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterLightningArresterResult: inspectionItemSchema.optional(),
        visualSafetyDevicesConverterLiftingHeightIndicatorResult: inspectionItemSchema.optional(),
        
        ndtWireRopeMainLoadSpecDiameter: Joi.string().allow('', null).optional(),
        ndtWireRopeMainLoadActualDiameter: Joi.string().allow('', null).optional(),
        ndtWireRopeMainLoadConstruction: Joi.string().allow('', null).optional(),
        ndtWireRopeMainLoadType: Joi.string().allow('', null).optional(),
        ndtWireRopeMainLoadLength: Joi.string().allow('', null).optional(),
        ndtWireRopeMainLoadAge: Joi.string().allow('', null).optional(),
        ndtWireRopeMainLoadResult: inspectionItemSchema.optional(),
        ndtWireRopeAuxiliaryLoadSpecDiameter: Joi.string().allow('', null).optional(),
        ndtWireRopeAuxiliaryLoadActualDiameter: Joi.string().allow('', null).optional(),
        ndtWireRopeAuxiliaryLoadConstruction: Joi.string().allow('', null).optional(),
        ndtWireRopeAuxiliaryLoadType: Joi.string().allow('', null).optional(),
        ndtWireRopeAuxiliaryLoadLength: Joi.string().allow('', null).optional(),
        ndtWireRopeAuxiliaryLoadAge: Joi.string().allow('', null).optional(),
        ndtWireRopeAuxiliaryLoadResult: inspectionItemSchema.optional(),
        ndtWireRopeBoomHoistSpecDiameter: Joi.string().allow('', null).optional(),
        ndtWireRopeBoomHoistActualDiameter: Joi.string().allow('', null).optional(),
        ndtWireRopeBoomHoistConstruction: Joi.string().allow('', null).optional(),
        ndtWireRopeBoomHoistType: Joi.string().allow('', null).optional(),
        ndtWireRopeBoomHoistLength: Joi.string().allow('', null).optional(),
        ndtWireRopeBoomHoistAge: Joi.string().allow('', null).optional(),
        ndtWireRopeBoomHoistResult: inspectionItemSchema.optional(),

        ndtBoomType: Joi.string().allow('', null).optional(),
        ndtBoomNdtType: Joi.string().allow('', null).optional(),
        ndtBoomInspection1Part: Joi.string().allow('', null).optional(),
        ndtBoomInspection1Location: Joi.string().allow('', null).optional(),
        ndtBoomInspection1Result: inspectionItemSchema.optional(),
        ndtBoomInspection2Part: Joi.string().allow('', null).optional(),
        ndtBoomInspection2Location: Joi.string().allow('', null).optional(),
        ndtBoomInspection2Result: inspectionItemSchema.optional(),
        ndtBoomInspection3Part: Joi.string().allow('', null).optional(),
        ndtBoomInspection3Location: Joi.string().allow('', null).optional(),
        ndtBoomInspection3Result: inspectionItemSchema.optional(),

        ndtMainHookNdtType: Joi.string().allow('', null).optional(),
        ndtMainHookSpecificationA: Joi.string().allow('', null).optional(),
        ndtMainHookSpecificationB: Joi.string().allow('', null).optional(),
        ndtMainHookSpecificationC: Joi.string().allow('', null).optional(),
        ndtMainHookSpecificationD: Joi.string().allow('', null).optional(),
        ndtMainHookSpecificationE: Joi.string().allow('', null).optional(),
        ndtMainHookSpecificationF: Joi.string().allow('', null).optional(),
        ndtMainHookSpecificationG: Joi.string().allow('', null).optional(),
        ndtMainHookSpecificationH: Joi.string().allow('', null).optional(),
        ndtMainHookSpecificationResult: inspectionItemSchema.optional(),
        ndtMainHookMeasurementResultsA: Joi.string().allow('', null).optional(),
        ndtMainHookMeasurementResultsB: Joi.string().allow('', null).optional(),
        ndtMainHookMeasurementResultsC: Joi.string().allow('', null).optional(),
        ndtMainHookMeasurementResultsD: Joi.string().allow('', null).optional(),
        ndtMainHookMeasurementResultsE: Joi.string().allow('', null).optional(),
        ndtMainHookMeasurementResultsF: Joi.string().allow('', null).optional(),
        ndtMainHookMeasurementResultsG: Joi.string().allow('', null).optional(),
        ndtMainHookMeasurementResultsH: Joi.string().allow('', null).optional(),
        ndtMainHookMeasurementResultsResult: inspectionItemSchema.optional(),
        ndtMainHookToleranceMeasureA: Joi.string().allow('', null).optional(),
        ndtMainHookToleranceMeasureB: Joi.string().allow('', null).optional(),
        ndtMainHookToleranceMeasureC: Joi.string().allow('', null).optional(),
        ndtMainHookToleranceMeasureD: Joi.string().allow('', null).optional(),
        ndtMainHookToleranceMeasureE: Joi.string().allow('', null).optional(),
        ndtMainHookToleranceMeasureF: Joi.string().allow('', null).optional(),
        ndtMainHookToleranceMeasureG: Joi.string().allow('', null).optional(),
        ndtMainHookToleranceMeasureH: Joi.string().allow('', null).optional(),
        ndtMainHookToleranceMeasureResult: inspectionItemSchema.optional(),

        ndtAuxiliaryHookNdtType: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookSpecificationA: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookSpecificationB: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookSpecificationC: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookSpecificationD: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookSpecificationE: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookSpecificationF: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookSpecificationG: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookSpecificationH: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookSpecificationResult: inspectionItemSchema.optional(),
        ndtAuxiliaryHookMeasurementResultsA: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookMeasurementResultsB: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookMeasurementResultsC: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookMeasurementResultsD: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookMeasurementResultsE: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookMeasurementResultsF: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookMeasurementResultsG: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookMeasurementResultsH: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookMeasurementResultsResult: inspectionItemSchema.optional(),
        ndtAuxiliaryHookToleranceMeasureA: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookToleranceMeasureB: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookToleranceMeasureC: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookToleranceMeasureD: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookToleranceMeasureE: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookToleranceMeasureF: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookToleranceMeasureG: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookToleranceMeasureH: Joi.string().allow('', null).optional(),
        ndtAuxiliaryHookToleranceMeasureResult: inspectionItemSchema.optional(),
        
        ndtMainDrumNdtType: Joi.string().allow('', null).optional(),
        ndtMainDrumSpecificationA: Joi.string().allow('', null).optional(),
        ndtMainDrumSpecificationB: Joi.string().allow('', null).optional(),
        ndtMainDrumSpecificationC: Joi.string().allow('', null).optional(),
        ndtMainDrumSpecificationD: Joi.string().allow('', null).optional(),
        ndtMainDrumSpecificationE: Joi.string().allow('', null).optional(),
        ndtMainDrumSpecificationF: Joi.string().allow('', null).optional(),
        ndtMainDrumSpecificationG: Joi.string().allow('', null).optional(),
        ndtMainDrumSpecificationResult: inspectionItemSchema.optional(),
        ndtMainDrumMeasurementResultsA: Joi.string().allow('', null).optional(),
        ndtMainDrumMeasurementResultsB: Joi.string().allow('', null).optional(),
        ndtMainDrumMeasurementResultsC: Joi.string().allow('', null).optional(),
        ndtMainDrumMeasurementResultsD: Joi.string().allow('', null).optional(),
        ndtMainDrumMeasurementResultsE: Joi.string().allow('', null).optional(),
        ndtMainDrumMeasurementResultsF: Joi.string().allow('', null).optional(),
        ndtMainDrumMeasurementResultsG: Joi.string().allow('', null).optional(),
        ndtMainDrumMeasurementResultsResult: inspectionItemSchema.optional(),

        ndtAuxiliaryDrumNdtType: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumSpecificationA: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumSpecificationB: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumSpecificationC: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumSpecificationD: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumSpecificationE: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumSpecificationF: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumSpecificationG: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumSpecificationResult: inspectionItemSchema.optional(),
        ndtAuxiliaryDrumMeasurementResultsA: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumMeasurementResultsB: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumMeasurementResultsC: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumMeasurementResultsD: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumMeasurementResultsE: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumMeasurementResultsF: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumMeasurementResultsG: Joi.string().allow('', null).optional(),
        ndtAuxiliaryDrumMeasurementResultsResult: inspectionItemSchema.optional(),

        ndtMainPulleySpecificationA: Joi.string().allow('', null).optional(),
        ndtMainPulleySpecificationB: Joi.string().allow('', null).optional(),
        ndtMainPulleySpecificationC: Joi.string().allow('', null).optional(),
        ndtMainPulleySpecificationD: Joi.string().allow('', null).optional(),
        ndtMainPulleySpecificationE: Joi.string().allow('', null).optional(),
        ndtMainPulleySpecificationResult: inspectionItemSchema.optional(),
        ndtMainPulleyMeasurementResultsA: Joi.string().allow('', null).optional(),
        ndtMainPulleyMeasurementResultsB: Joi.string().allow('', null).optional(),
        ndtMainPulleyMeasurementResultsC: Joi.string().allow('', null).optional(),
        ndtMainPulleyMeasurementResultsD: Joi.string().allow('', null).optional(),
        ndtMainPulleyMeasurementResultsE: Joi.string().allow('', null).optional(),
        ndtMainPulleyMeasurementResultsResult: inspectionItemSchema.optional(),

        ndtAuxiliaryPulleySpecificationA: Joi.string().allow('', null).optional(),
        ndtAuxiliaryPulleySpecificationB: Joi.string().allow('', null).optional(),
        ndtAuxiliaryPulleySpecificationC: Joi.string().allow('', null).optional(),
        ndtAuxiliaryPulleySpecificationD: Joi.string().allow('', null).optional(),
        ndtAuxiliaryPulleySpecificationE: Joi.string().allow('', null).optional(),
        ndtAuxiliaryPulleySpecificationResult: inspectionItemSchema.optional(),
        ndtAuxiliaryPulleyMeasurementResultsA: Joi.string().allow('', null).optional(),
        ndtAuxiliaryPulleyMeasurementResultsB: Joi.string().allow('', null).optional(),
        ndtAuxiliaryPulleyMeasurementResultsC: Joi.string().allow('', null).optional(),
        ndtAuxiliaryPulleyMeasurementResultsD: Joi.string().allow('', null).optional(),
        ndtAuxiliaryPulleyMeasurementResultsE: Joi.string().allow('', null).optional(),
        ndtAuxiliaryPulleyMeasurementResultsResult: inspectionItemSchema.optional(),

        testingFunctionHoistingLoweringResult: inspectionItemSchema.optional(),
        testingFunctionExtendedRectractedBoomResult: inspectionItemSchema.optional(),
        testingFunctionExtendedRectractedOutriggerResult: inspectionItemSchema.optional(),
        testingFunctionSwingSlewingResult: inspectionItemSchema.optional(),
        testingFunctionAntiTwoBlockResult: inspectionItemSchema.optional(),
        testingFunctionBoomStopResult: inspectionItemSchema.optional(),
        testingFunctionAnemometerWindSpeedResult: inspectionItemSchema.optional(),
        testingFunctionBrakeLockingDeviceResult: inspectionItemSchema.optional(),
        testingFunctionLoadMomentIndicatorResult: inspectionItemSchema.optional(),
        testingFunctionTurnSignalResult: inspectionItemSchema.optional(),
        testingFunctionDrivingLightsResult: inspectionItemSchema.optional(),
        testingFunctionLoadIndicatorLightResult: inspectionItemSchema.optional(),
        testingFunctionRotaryLampResult: inspectionItemSchema.optional(),
        testingFunctionHornResult: inspectionItemSchema.optional(),
        testingFunctionSwingAlarmResult: inspectionItemSchema.optional(),
        testingFunctionReverseAlarmResult: inspectionItemSchema.optional(),
        testingFunctionOverloadAlarmResult: inspectionItemSchema.optional(),

        testingDynamicMainHook1BoomLength: Joi.string().allow('', null).optional(),
        testingDynamicMainHook1Radius: Joi.string().allow('', null).optional(),
        testingDynamicMainHook1BoomAngle: Joi.string().allow('', null).optional(),
        testingDynamicMainHook1TestLoad: Joi.string().allow('', null).optional(),
        testingDynamicMainHook1SafeWorkingLoad: Joi.string().allow('', null).optional(),
        testingDynamicMainHook1Result: Joi.string().allow('', null).optional(),
        testingDynamicMainHook2BoomLength: Joi.string().allow('', null).optional(),
        testingDynamicMainHook2Radius: Joi.string().allow('', null).optional(),
        testingDynamicMainHook2BoomAngle: Joi.string().allow('', null).optional(),
        testingDynamicMainHook2TestLoad: Joi.string().allow('', null).optional(),
        testingDynamicMainHook2SafeWorkingLoad: Joi.string().allow('', null).optional(),
        testingDynamicMainHook2Result: Joi.string().allow('', null).optional(),

        testingDynamicAuxiliaryHook1BoomLength: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook1Radius: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook1BoomAngle: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook1TestLoad: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook1SafeWorkingLoad: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook1Result: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook2BoomLength: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook2Radius: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook2BoomAngle: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook2TestLoad: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook2SafeWorkingLoad: Joi.string().allow('', null).optional(),
        testingDynamicAuxiliaryHook2Result: Joi.string().allow('', null).optional(),
        
        testingStaticMainHook1BoomLength: Joi.string().allow('', null).optional(),
        testingStaticMainHook1Radius: Joi.string().allow('', null).optional(),
        testingStaticMainHook1BoomAngle: Joi.string().allow('', null).optional(),
        testingStaticMainHook1TestLoad: Joi.string().allow('', null).optional(),
        testingStaticMainHook1SafeWorkingLoad: Joi.string().allow('', null).optional(),
        testingStaticMainHook1Result: Joi.string().allow('', null).optional(),
        testingStaticMainHook2BoomLength: Joi.string().allow('', null).optional(),
        testingStaticMainHook2Radius: Joi.string().allow('', null).optional(),
        testingStaticMainHook2BoomAngle: Joi.string().allow('', null).optional(),
        testingStaticMainHook2TestLoad: Joi.string().allow('', null).optional(),
        testingStaticMainHook2SafeWorkingLoad: Joi.string().allow('', null).optional(),
        testingStaticMainHook2Result: Joi.string().allow('', null).optional(),

        testingStaticAuxiliaryHook1BoomLength: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook1Radius: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook1BoomAngle: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook1TestLoad: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook1SafeWorkingLoad: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook1Result: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook2BoomLength: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook2Radius: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook2BoomAngle: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook2TestLoad: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook2SafeWorkingLoad: Joi.string().allow('', null).optional(),
        testingStaticAuxiliaryHook2Result: Joi.string().allow('', null).optional()
    }).optional(),

    // Data Kesimpulan dan Saran
    conclusion: Joi.string().allow('', null).optional(),
    recommendation: Joi.string().allow('', null).optional()
});

module.exports = {
    laporanMobileCranePayload,
};
