'use strict';

const PizZip = require('pizzip');
const Docxtemplater = require('docxtemplater');
const { Storage } = require('@google-cloud/storage');
const config = require('../../../../../config');

// Inisialisasi koneksi ke Google Cloud Storage
let privateKey = config.FIRESTORE_PRIVATE_KEY.replace(/\\n/g, '\n');
const storage = new Storage({
    projectId: config.FIRESTORE_PROJECT_ID,
    credentials: {
        client_email: config.FIRESTORE_CLIENT_EMAIL,
        private_key: privateKey,
    },
});
const BUCKET_NAME = 'tamplate-audit-riksauji';

// =================================================================================
// FUNGSI BANTUAN (HELPERS)
// =================================================================================

const getCheckmark = (status) => (status === true ? '√' : '');
const getOppositeCheckmark = (status) => (status === false ? '√' : '');

// =================================================================================
// FUNGSI GENERATOR UTAMA
// =================================================================================

const createLaporanForklift = async (data) => {
    const templatePath = 'paa/forklift/LAPORAN FORKLIFT.docx'; // Sesuaikan dengan path di GCS

    let content;
    try {
        const [fileBuffer] = await storage.bucket(BUCKET_NAME).file(templatePath).download();
        content = fileBuffer;
    } catch (error) {
        console.error('Gagal mengunduh template Laporan Forklift:', error);
        throw new Error('Template dokumen Laporan Forklift tidak dapat diakses dari Cloud Storage.');
    }

    const zip = new PizZip(content);
    const doc = new Docxtemplater(zip, {
        paragraphLoop: true,
        linebreaks: true,
        nullGetter: () => "", // Ganti tag yang datanya tidak ada dengan string kosong
    });

    const g = data.generalData || {};
    const t = a.technicalData || {};
    const v = data.visualAndFunctionCheck || {};
    const att = data.attachments || {};
    const h = data.hydraulicComponents || {};
    const e = data.engineOnCheck || {};

    const renderData = {
        // Data Utama
        examinationType: data.examinationType,
        subInspectionType: data.subInspectionType,
        
        // Data Umum
        ownerNamwe: g.ownerName, // Sesuai typo di template
        ownerAddress: g.ownerAddress,
        userInCharge: g.userInCharge,
        subcontractorPersonInCharge: g.subcontractorPersonInCharge,
        unitLocation: g.unitLocation,
        operatorName: g.operatorName,
        equipmentType: g.equipmentType,
        manufacturer: g.manufacturer,
        brandType: g.brandType,
        locationAndYearOfManufacture: g.locationAndYearOfManufacture,
        serialNumberUnitNumber: g.serialNumberUnitNumber,
        capacityWorkingLoad: g.capacityWorkingLoad,
        intendedUse: g.intendedUse,
        certificateNumber: g.certificateNumber,
        equipmentHistory: g.equipmentHistory,
        inspectionDate: g.inspectionDate,

        // Data Teknik
        specificationSerialNumber: t.specification?.serialNumber,
        specificationCapacity: t.specification?.capacity,
        specificationAttachment: t.specification?.attachment,
        specificationForkDimensions: t.specification?.forkDimensions,
        specificationSpeedLifting: t.speed?.lifting,
        specificationSpeedLowering: t.speed?.lowering,
        specificationSpeedTravelling: t.speed?.travelling,
        primeMoverBrandType: t.primeMover?.brandType,
        primeMoverSerialNumber: t.primeMover?.serialNumber,
        primeMoverYearOfManufacture: t.primeMover?.yearOfManufacture,
        primeMoverRevolution: t.primeMover?.revolution,
        primeMoverPower: t.primeMover?.power,
        primeMoverNumberOfCylinders: t.primeMover?.numberOfCylinders,
        dimensionLength: t.dimension?.length,
        dimensionWidth: t.dimension?.width,
        dimensionHeight: t.dimension?.height,
        dimensionForkLiftingHeight: t.dimension?.forkLiftingHeight,
        tirePressureDriveWheel: t.tirePressure?.driveWheel,
        tirePressureSteeringWheel: t.tirePressure?.steeringWheel,
        driveWheelSize: t.driveWheel?.size,
        driveWheelType: t.driveWheel?.type,
        steeringWheelSize: t.steeringWheel?.size,
        steeringWheelType: t.steeringWheel?.type,
        travellingBrakeSize: t.travellingBrake?.size,
        travellingBrakeType: t.travellingBrake?.type,
        hydraulicPumpPressure: t.hydraulicPump?.pressure,
        hydraulicPumpType: t.hydraulicPump?.type,
        hydraulicPumpReliefValve: t.hydraulicPump?.reliefValve,

        // PEMERIKSAAN VISUAL DAN FUNGSI
        // Kerangka Utama / Chasis
        mainFrameReinforcingCorrosionMemenuhi: getCheckmark(v.mainFrameChassis?.reinforcingFrame?.corrosion?.status),
        mainFrameReinforcingCorrosionTidakMemenuhi: getOppositeCheckmark(v.mainFrameChassis?.reinforcingFrame?.corrosion?.status),
        mainFrameReinforcingCorrosionResult: v.mainFrameChassis?.reinforcingFrame?.corrosion?.result,
        mainFrameReinforcingCracksMemenuhi: getCheckmark(v.mainFrameChassis?.reinforcingFrame?.cracks?.status),
        mainFrameReinforcingCracksTidakMemenuhi: getOppositeCheckmark(v.mainFrameChassis?.reinforcingFrame?.cracks?.status),
        mainFrameReinforcingCracksResult: v.mainFrameChassis?.reinforcingFrame?.cracks?.result,
        mainFrameReinforcingDeformationMemenuhi: getCheckmark(v.mainFrameChassis?.reinforcingFrame?.deformation?.status),
        mainFrameReinforcingDeformationTidakMemenuhi: getOppositeCheckmark(v.mainFrameChassis?.reinforcingFrame?.deformation?.status),
        mainFrameReinforcingDeformationResult: v.mainFrameChassis?.reinforcingFrame?.deformation?.result,
        
        // Pemberat (C/W)
        counterweightCorrosionMemenuhi: getCheckmark(v.counterweight?.corrosion?.status),
        counterweightCorrosionTidakMemenuhi: getOppositeCheckmark(v.counterweight?.corrosion?.status),
        counterweightCorrosionResult: v.counterweight?.corrosion?.result,
        counterweightConditionMemenuhi: getCheckmark(v.counterweight?.condition?.status),
        counterweightConditionTidakMemenuhi: getOppositeCheckmark(v.counterweight?.condition?.status),
        counterweightConditionResult: v.counterweight?.condition?.result,

        // Perlengkapan Lain
        otherEquipmentFloorDeckMemenuhi: getCheckmark(v.otherEquipment?.floorDeck?.status),
        otherEquipmentFloorDeckTidakMemenuhi: getOppositeCheckmark(v.otherEquipment?.floorDeck?.status),
        otherEquipmentFloorDeckResult: v.otherEquipment?.floorDeck?.result,
        otherEquipmentStairsStepsMemenuhi: getCheckmark(v.otherEquipment?.stairsSteps?.status),
        otherEquipmentStairsStepsTidakMemenuhi: getOppositeCheckmark(v.otherEquipment?.stairsSteps?.status),
        otherEquipmentStairsStepsResult: v.otherEquipment?.stairsSteps?.result,
        otherEquipmentFasteningBoltsMemenuhi: getCheckmark(v.otherEquipment?.fasteningBolts?.status),
        otherEquipmentFasteningBoltsTidakMemenuhi: getOppositeCheckmark(v.otherEquipment?.fasteningBolts?.status),
        otherEquipmentFasteningBoltsResult: v.otherEquipment?.fasteningBolts?.result,
        otherEquipmentOperatorSeatMemenuhi: getCheckmark(v.otherEquipment?.operatorSeat?.status),
        otherEquipmentOperatorSeatTidakMemenuhi: getOppositeCheckmark(v.otherEquipment?.operatorSeat?.status),
        otherEquipmentOperatorSeatResult: v.otherEquipment?.operatorSeat?.result,

        // Penggerak Utama / Prime Mover - Sistem
        primeMoverSystemCoolingMemenuhi: getCheckmark(v.primeMover?.system?.cooling?.status),
        primeMoverSystemCoolingTidakMemenuhi: getOppositeCheckmark(v.primeMover?.system?.cooling?.status),
        primeMoverSystemCoolingResult: v.primeMover?.system?.cooling?.result,
        primeMoverSystemLubricationMemenuhi: getCheckmark(v.primeMover?.system?.lubrication?.status),
        primeMoverSystemLubricationTidakMemenuhi: getOppositeCheckmark(v.primeMover?.system?.lubrication?.status),
        primeMoverSystemLubricationResult: v.primeMover?.system?.lubrication?.result,
        primeMoverSystemFuelMemenuhi: getCheckmark(v.primeMover?.system?.fuel?.status),
        primeMoverSystemFuelTidakMemenuhi: getOppositeCheckmark(v.primeMover?.system?.fuel?.status),
        primeMoverSystemFuelResult: v.primeMover?.system?.fuel?.result,
        primeMoverSystemAirIntakeMemenuhi: getCheckmark(v.primeMover?.system?.airIntake?.status),
        primeMoverSystemAirIntakeTidakMemenuhi: getOppositeCheckmark(v.primeMover?.system?.airIntake?.status),
        primeMoverSystemAirIntakeResult: v.primeMover?.system?.airIntake?.result,
        primeMoverSystemExhaustGasMemenuhi: getCheckmark(v.primeMover?.system?.exhaustGas?.status),
        primeMoverSystemExhaustGasTidakMemenuhi: getOppositeCheckmark(v.primeMover?.system?.exhaustGas?.status),
        primeMoverSystemExhaustGasResult: v.primeMover?.system?.exhaustGas?.result,
        primeMoverSystemStarterMemenuhi: getCheckmark(v.primeMover?.system?.starter?.status),
        primeMoverSystemStarterTidakMemenuhi: getOppositeCheckmark(v.primeMover?.system?.starter?.status),
        primeMoverSystemStarterResult: v.primeMover?.system?.starter?.result,

        // Penggerak Utama / Prime Mover - Kelistrikan
        primeMoverElectricalBatteryMemenuhi: getCheckmark(v.primeMover?.electrical?.battery?.status),
        primeMoverElectricalBatteryTidakMemenuhi: getOppositeCheckmark(v.primeMover?.electrical?.battery?.status),
        primeMoverElectricalBatteryResult: v.primeMover?.electrical?.battery?.result,
        primeMoverElectricalStartingDynamoMemenuhi: getCheckmark(v.primeMover?.electrical?.startingDynamo?.status),
        primeMoverElectricalStartingDynamoTidakMemenuhi: getOppositeCheckmark(v.primeMover?.electrical?.startingDynamo?.status),
        primeMoverElectricalStartingDynamoResult: v.primeMover?.electrical?.startingDynamo?.result,
        primeMoverElectricalAlternatorMemenuhi: getCheckmark(v.primeMover?.electrical?.alternator?.status),
        primeMoverElectricalAlternatorTidakMemenuhi: getOppositeCheckmark(v.primeMover?.electrical?.alternator?.status),
        primeMoverElectricalAlternatorResult: v.primeMover?.electrical?.alternator?.result,
        primeMoverElectricalBatteryCableMemenuhi: getCheckmark(v.primeMover?.electrical?.batteryCable?.status),
        primeMoverElectricalBatteryCableTidakMemenuhi: getOppositeCheckmark(v.primeMover?.electrical?.batteryCable?.status),
        primeMoverElectricalBatteryCableResult: v.primeMover?.electrical?.batteryCable?.result,
        primeMoverElectricalInstallationCableMemenuhi: getCheckmark(v.primeMover?.electrical?.installationCable?.status),
        primeMoverElectricalInstallationCableTidakMemenuhi: getOppositeCheckmark(v.primeMover?.electrical?.installationCable?.status),
        primeMoverElectricalInstallationCableResult: v.primeMover?.electrical?.installationCable?.result,
        primeMoverElectricalLightingLampsMemenuhi: getCheckmark(v.primeMover?.electrical?.lightingLamps?.status),
        primeMoverElectricalLightingLampsTidakMemenuhi: getOppositeCheckmark(v.primeMover?.electrical?.lightingLamps?.status),
        primeMoverElectricalLightingLampsResult: v.primeMover?.electrical?.lightingLamps?.result,
        primeMoverElectricalSafetyLampsMemenuhi: getCheckmark(v.primeMover?.electrical?.safetySignalLamps?.status),
        primeMoverElectricalSafetyLampsTidakMemenuhi: getOppositeCheckmark(v.primeMover?.electrical?.safetySignalLamps?.status),
        primeMoverElectricalSafetyLampsResult: v.primeMover?.electrical?.safetySignalLamps?.result,
        primeMoverElectricalHornMemenuhi: getCheckmark(v.primeMover?.electrical?.horn?.status),
        primeMoverElectricalHornTidakMemenuhi: getOppositeCheckmark(v.primeMover?.electrical?.horn?.status),
        primeMoverElectricalHornResult: v.primeMover?.electrical?.horn?.result,
        primeMoverElectricalFuseMemenuhi: getCheckmark(v.primeMover?.electrical?.fuse?.status),
        primeMoverElectricalFuseTidakMemenuhi: getOppositeCheckmark(v.primeMover?.electrical?.fuse?.status),
        primeMoverElectricalFuseResult: v.primeMover?.electrical?.fuse?.result,

        // Dashboard
        dashboardTempIndicatorMemenuhi: getCheckmark(v.dashboard?.temperatureIndicator?.status),
        dashboardTempIndicatorTidakMemenuhi: getOppositeCheckmark(v.dashboard?.temperatureIndicator?.status),
        dashboardTempIndicatorResult: v.dashboard?.temperatureIndicator?.result,
        dashboardOilPressureMemenuhi: getCheckmark(v.dashboard?.engineOilPressure?.status),
        dashboardOilPressureTidakMemenuhi: getOppositeCheckmark(v.dashboard?.engineOilPressure?.status),
        dashboardOilPressureResult: v.dashboard?.engineOilPressure?.result,
        dashboardHydraulicPressureMemenuhi: getCheckmark(v.dashboard?.hydraulicPressure?.status),
        dashboardHydraulicPressureTidakMemenuhi: getOppositeCheckmark(v.dashboard?.hydraulicPressure?.status),
        dashboardHydraulicPressureResult: v.dashboard?.hydraulicPressure?.result,
        dashboardHourMeterMemenuhi: getCheckmark(v.dashboard?.hourMeter?.status),
        dashboardHourMeterTidakMemenuhi: getOppositeCheckmark(v.dashboard?.hourMeter?.status),
        dashboardHourMeterResult: v.dashboard?.hourMeter?.result,
        dashboardGlowPlugMemenuhi: getCheckmark(v.dashboard?.glowPlug?.status),
        dashboardGlowPlugTidakMemenuhi: getOppositeCheckmark(v.dashboard?.glowPlug?.status),
        dashboardGlowPlugResult: v.dashboard?.glowPlug?.result,
        dashboardFuelIndicatorMemenuhi: getCheckmark(v.dashboard?.fuelIndicator?.status),
        dashboardFuelIndicatorTidakMemenuhi: getOppositeCheckmark(v.dashboard?.fuelIndicator?.status),
        dashboardFuelIndicatorResult: v.dashboard?.fuelIndicator?.result,
        dashboardLoadIndicatorMemenuhi: getCheckmark(v.dashboard?.loadIndicator?.status),
        dashboardLoadIndicatorTidakMemenuhi: getOppositeCheckmark(v.dashboard?.loadIndicator?.status),
        dashboardLoadIndicatorResult: v.dashboard?.loadIndicator?.result,
        dashboardLoadChartMemenuhi: getCheckmark(v.dashboard?.loadChart?.status),
        dashboardLoadChartTidakMemenuhi: getOppositeCheckmark(v.dashboard?.loadChart?.status),
        dashboardLoadChartResult: v.dashboard?.loadChart?.result,
        
        // Komponen Bagian Bawah / PowerTrain
        powerTrainStarterDynamoMemenuhi: getCheckmark(v.powerTrain?.steeringSystem?.starterDynamo?.status),
        powerTrainStarterDynamoTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.steeringSystem?.starterDynamo?.status),
        powerTrainStarterDynamoResult: v.powerTrain?.steeringSystem?.starterDynamo?.result,
        powerTrainSteeringWheelMemenuhi: getCheckmark(v.powerTrain?.steeringSystem?.wheelSteering?.status),
        powerTrainSteeringWheelTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.steeringSystem?.wheelSteering?.status),
        powerTrainSteeringWheelResult: v.powerTrain?.steeringSystem?.wheelSteering?.result,
        powerTrainSteeringRodMemenuhi: getCheckmark(v.powerTrain?.steeringSystem?.steeringRod?.status),
        powerTrainSteeringRodTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.steeringSystem?.steeringRod?.status),
        powerTrainSteeringRodResult: v.powerTrain?.steeringSystem?.steeringRod?.result,
        powerTrainSteeringGearBoxMemenuhi: getCheckmark(v.powerTrain?.steeringSystem?.gearBox?.status),
        powerTrainSteeringGearBoxTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.steeringSystem?.gearBox?.status),
        powerTrainSteeringGearBoxResult: v.powerTrain?.steeringSystem?.gearBox?.result,
        powerTrainSteeringPitmanMemenuhi: getCheckmark(v.powerTrain?.steeringSystem?.pitmanArm?.status),
        powerTrainSteeringPitmanTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.steeringSystem?.pitmanArm?.status),
        powerTrainSteeringPitmanResult: v.powerTrain?.steeringSystem?.pitmanArm?.result,
        powerTrainSteeringDragLinkMemenuhi: getCheckmark(v.powerTrain?.steeringSystem?.dragLink?.status),
        powerTrainSteeringDragLinkTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.steeringSystem?.dragLink?.status),
        powerTrainSteeringDragLinkResult: v.powerTrain?.steeringSystem?.dragLink?.result,
        powerTrainSteeringTieRodMemenuhi: getCheckmark(v.powerTrain?.steeringSystem?.tieRod?.status),
        powerTrainSteeringTieRodTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.steeringSystem?.tieRod?.status),
        powerTrainSteeringTieRodResult: v.powerTrain?.steeringSystem?.tieRod?.result,
        powerTrainSteeringLubeMemenuhi: getCheckmark(v.powerTrain?.steeringSystem?.lubrication?.status),
        powerTrainSteeringLubeTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.steeringSystem?.lubrication?.status),
        powerTrainSteeringLubeResult: v.powerTrain?.steeringSystem?.lubrication?.result,
        powerTrainWheelsFrontMemenuhi: getCheckmark(v.powerTrain?.wheels?.frontDriveWheel?.status),
        powerTrainWheelsFrontTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.wheels?.frontDriveWheel?.status),
        powerTrainWheelsFrontResult: v.powerTrain?.wheels?.frontDriveWheel?.result,
        powerTrainWheelsRearMemenuhi: getCheckmark(v.powerTrain?.wheels?.rearSteeringWheel?.status),
        powerTrainWheelsRearTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.wheels?.rearSteeringWheel?.status),
        powerTrainWheelsRearResult: v.powerTrain?.wheels?.rearSteeringWheel?.result,
        powerTrainWheelsBoltsMemenuhi: getCheckmark(v.powerTrain?.wheels?.fasteningBolts?.status),
        powerTrainWheelsBoltsTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.wheels?.fasteningBolts?.status),
        powerTrainWheelsBoltsResult: v.powerTrain?.wheels?.fasteningBolts?.result,
        powerTrainWheelsDrumMemenuhi: getCheckmark(v.powerTrain?.wheels?.drumHub?.status),
        powerTrainWheelsDrumTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.wheels?.drumHub?.status),
        powerTrainWheelsDrumResult: v.powerTrain?.wheels?.drumHub?.result,
        powerTrainWheelsLubeMemenuhi: getCheckmark(v.powerTrain?.wheels?.lubrication?.status),
        powerTrainWheelsLubeTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.wheels?.lubrication?.status),
        powerTrainWheelsLubeResult: v.powerTrain?.wheels?.lubrication?.result,
        powerTrainWheelsMechanicalMemenuhi: getCheckmark(v.powerTrain?.wheels?.mechanicalParts?.status),
        powerTrainWheelsMechanicalTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.wheels?.mechanicalParts?.status),
        powerTrainWheelsMechanicalResult: v.powerTrain?.wheels?.mechanicalParts?.result,
        powerTrainClutchHousingMemenuhi: getCheckmark(v.powerTrain?.clutch?.clutchHousing?.status),
        powerTrainClutchHousingTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.clutch?.clutchHousing?.status),
        powerTrainClutchHousingResult: v.powerTrain?.clutch?.clutchHousing?.result,
        powerTrainClutchConditionMemenuhi: getCheckmark(v.powerTrain?.clutch?.clutchCondition?.status),
        powerTrainClutchConditionTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.clutch?.clutchCondition?.status),
        powerTrainClutchConditionResult: v.powerTrain?.clutch?.clutchCondition?.result,
        powerTrainClutchTransOilMemenuhi: getCheckmark(v.powerTrain?.clutch?.transmissionOil?.status),
        powerTrainClutchTransOilTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.clutch?.transmissionOil?.status),
        powerTrainClutchTransOilResult: v.powerTrain?.clutch?.transmissionOil?.result,
        powerTrainClutchTransLeakMemenuhi: getCheckmark(v.powerTrain?.clutch?.transmissionLeakage?.status),
        powerTrainClutchTransLeakTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.clutch?.transmissionLeakage?.status),
        powerTrainClutchTransLeakResult: v.powerTrain?.clutch?.transmissionLeakage?.result,
        powerTrainClutchShaftMemenuhi: getCheckmark(v.powerTrain?.clutch?.connectingShaft?.status),
        powerTrainClutchShaftTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.clutch?.connectingShaft?.status),
        powerTrainClutchShaftResult: v.powerTrain?.clutch?.connectingShaft?.result,
        powerTrainClutchMechanicalMemenuhi: getCheckmark(v.powerTrain?.clutch?.mechanicalParts?.status),
        powerTrainClutchMechanicalTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.clutch?.mechanicalParts?.status),
        powerTrainClutchMechanicalResult: v.powerTrain?.clutch?.mechanicalParts?.result,
        powerTrainDiffHousingMemenuhi: getCheckmark(v.powerTrain?.differential?.differentialHousing?.status),
        powerTrainDiffHousingTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.differential?.differentialHousing?.status),
        powerTrainDiffHousingResult: v.powerTrain?.differential?.differentialHousing?.result,
        powerTrainDiffConditionMemenuhi: getCheckmark(v.powerTrain?.differential?.differentialCondition?.status),
        powerTrainDiffConditionTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.differential?.differentialCondition?.status),
        powerTrainDiffConditionResult: v.powerTrain?.differential?.differentialCondition?.result,
        powerTrainDiffOilMemenuhi: getCheckmark(v.powerTrain?.differential?.differentialOil?.status),
        powerTrainDiffOilTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.differential?.differentialOil?.status),
        powerTrainDiffOilResult: v.powerTrain?.differential?.differentialOil?.result,
        powerTrainDiffLeakMemenuhi: getCheckmark(v.powerTrain?.differential?.differentialLeakage?.status),
        powerTrainDiffLeakTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.differential?.differentialLeakage?.status),
        powerTrainDiffLeakResult: v.powerTrain?.differential?.differentialLeakage?.result,
        powerTrainDiffShaftMemenuhi: getCheckmark(v.powerTrain?.differential?.connectingShaft?.status),
        powerTrainDiffShaftTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.differential?.connectingShaft?.status),
        powerTrainDiffShaftResult: v.powerTrain?.differential?.connectingShaft?.result,
        powerTrainBrakesMainMemenuhi: getCheckmark(v.powerTrain?.brakes?.mainBrake?.status),
        powerTrainBrakesMainTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.brakes?.mainBrake?.status),
        powerTrainBrakesMainResult: v.powerTrain?.brakes?.mainBrake?.result,
        powerTrainBrakesHandMemenuhi: getCheckmark(v.powerTrain?.brakes?.handBrake?.status),
        powerTrainBrakesHandTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.brakes?.handBrake?.status),
        powerTrainBrakesHandResult: v.powerTrain?.brakes?.handBrake?.result,
        powerTrainBrakesEmergencyMemenuhi: getCheckmark(v.powerTrain?.brakes?.emergencyBrake?.status),
        powerTrainBrakesEmergencyTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.brakes?.emergencyBrake?.status),
        powerTrainBrakesEmergencyResult: v.powerTrain?.brakes?.emergencyBrake?.result,
        powerTrainBrakesLeakMemenuhi: getCheckmark(v.powerTrain?.brakes?.leakage?.status),
        powerTrainBrakesLeakTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.brakes?.leakage?.status),
        powerTrainBrakesLeakResult: v.powerTrain?.brakes?.leakage?.result,
        powerTrainBrakesMechanicalMemenuhi: getCheckmark(v.powerTrain?.brakes?.mechanicalComponents?.status),
        powerTrainBrakesMechanicalTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.brakes?.mechanicalComponents?.status),
        powerTrainBrakesMechanicalResult: v.powerTrain?.brakes?.mechanicalComponents?.result,
        powerTrainTransHousingMemenuhi: getCheckmark(v.powerTrain?.transmission?.transmissionHousing?.status),
        powerTrainTransHousingTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.transmission?.transmissionHousing?.status),
        powerTrainTransHousingResult: v.powerTrain?.transmission?.transmissionHousing?.result,
        powerTrainTransOilMemenuhi: getCheckmark(v.powerTrain?.transmission?.transmissionOil?.status),
        powerTrainTransOilTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.transmission?.transmissionOil?.status),
        powerTrainTransOilResult: v.powerTrain?.transmission?.transmissionOil?.result,
        powerTrainTransLeakMemenuhi: getCheckmark(v.powerTrain?.transmission?.transmissionLeakage?.status),
        powerTrainTransLeakTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.transmission?.transmissionLeakage?.status),
        powerTrainTransLeakResult: v.powerTrain?.transmission?.transmissionLeakage?.result,
        powerTrainTransMechanicalMemenuhi: getCheckmark(v.powerTrain?.transmission?.mechanicalParts?.status),
        powerTrainTransMechanicalTidakMemenuhi: getOppositeCheckmark(v.powerTrain?.transmission?.mechanicalParts?.status),
        powerTrainTransMechanicalResult: v.powerTrain?.transmission?.mechanicalParts?.result,

        // Attachments
        attachmentMastWearMemenuhi: getCheckmark(att.mast?.wear?.status),
        attachmentMastWearTidakMemenuhi: getOppositeCheckmark(att.mast?.wear?.status),
        attachmentMastWearResult: att.mast?.wear?.result,
        attachmentMastCracksMemenuhi: getCheckmark(att.mast?.cracks?.status),
        attachmentMastCracksTidakMemenuhi: getOppositeCheckmark(att.mast?.cracks?.status),
        attachmentMastCracksResult: att.mast?.cracks?.result,
        attachmentMastDeformationMemenuhi: getCheckmark(att.mast?.deformation?.status),
        attachmentMastDeformationTidakMemenuhi: getOppositeCheckmark(att.mast?.deformation?.status),
        attachmentMastDeformationResult: att.mast?.deformation?.result,
        attachmentMastLubeMemenuhi: getCheckmark(att.mast?.lubrication?.status),
        attachmentMastLubeTidakMemenuhi: getOppositeCheckmark(att.mast?.lubrication?.status),
        attachmentMastLubeResult: att.mast?.lubrication?.result,
        attachmentMastShaftBearingMemenuhi: getCheckmark(att.mast?.shaftAndBearings?.status),
        attachmentMastShaftBearingTidakMemenuhi: getOppositeCheckmark(att.mast?.shaftAndBearings?.status),
        attachmentMastShaftBearingResult: att.mast?.shaftAndBearings?.result,
        attachmentLiftChainConditionMemenuhi: getCheckmark(att.liftChain?.chainCondition?.status),
        attachmentLiftChainConditionTidakMemenuhi: getOppositeCheckmark(att.liftChain?.chainCondition?.status),
        attachmentLiftChainConditionResult: att.liftChain?.chainCondition?.result,
        attachmentLiftChainDeformationMemenuhi: getCheckmark(att.liftChain?.deformation?.status),
        attachmentLiftChainDeformationTidakMemenuhi: getOppositeCheckmark(att.liftChain?.deformation?.status),
        attachmentLiftChainDeformationResult: att.liftChain?.deformation?.result,
        attachmentLiftChainLubeMemenuhi: getCheckmark(att.liftChain?.chainLubrication?.status),
        attachmentLiftChainLubeTidakMemenuhi: getOppositeCheckmark(att.liftChain?.chainLubrication?.status),
        attachmentLiftChainLubeResult: att.liftChain?.chainLubrication?.result,

        // Hydraulic Components
        hydraulicTankLeakageMemenuhi: getCheckmark(h.tank?.leakage?.status),
        hydraulicTankLeakageTidakMemenuhi: getOppositeCheckmark(h.tank?.leakage?.status),
        hydraulicTankLeakageResult: h.tank?.leakage?.result,
        hydraulicTankOilLevelMemenuhi: getCheckmark(h.tank?.oilLevel?.status),
        hydraulicTankOilLevelTidakMemenuhi: getOppositeCheckmark(h.tank?.oilLevel?.status),
        hydraulicTankOilLevelResult: h.tank?.oilLevel?.result,
        hydraulicTankOilConditionMemenuhi: getCheckmark(h.tank?.oilCondition?.status),
        hydraulicTankOilConditionTidakMemenuhi: getOppositeCheckmark(h.tank?.oilCondition?.status),
        hydraulicTankOilConditionResult: h.tank?.oilCondition?.result,
        hydraulicTankSuctionLineMemenuhi: getCheckmark(h.tank?.suctionLineCondition?.status),
        hydraulicTankSuctionLineTidakMemenuhi: getOppositeCheckmark(h.tank?.suctionLineCondition?.status),
        hydraulicTankSuctionLineResult: h.tank?.suctionLineCondition?.result,
        hydraulicTankReturnLineMemenuhi: getCheckmark(h.tank?.returnLineCondition?.status),
        hydraulicTankReturnLineTidakMemenuhi: getOppositeCheckmark(h.tank?.returnLineCondition?.status),
        hydraulicTankReturnLineResult: h.tank?.returnLineCondition?.result,
        hydraulicPumpLeakageMemenuhi: getCheckmark(h.pump?.leakage?.status),
        hydraulicPumpLeakageTidakMemenuhi: getOppositeCheckmark(h.pump?.leakage?.status),
        hydraulicPumpLeakageResult: h.pump?.leakage?.result,
        hydraulicPumpSuctionLineMemenuhi: getCheckmark(h.pump?.suctionLineCondition?.status),
        hydraulicPumpSuctionLineTidakMemenuhi: getOppositeCheckmark(h.pump?.suctionLineCondition?.status),
        hydraulicPumpSuctionLineResult: h.pump?.suctionLineCondition?.result,
        hydraulicPumpPressureLineMemenuhi: getCheckmark(h.pump?.pressureLineCondition?.status),
        hydraulicPumpPressureLineTidakMemenuhi: getOppositeCheckmark(h.pump?.pressureLineCondition?.status),
        hydraulicPumpPressureLineResult: h.pump?.pressureLineCondition?.result,
        hydraulicPumpFunctionMemenuhi: getCheckmark(h.pump?.function?.status),
        hydraulicPumpFunctionTidakMemenuhi: getOppositeCheckmark(h.pump?.function?.status),
        hydraulicPumpFunctionResult: h.pump?.function?.result,
        hydraulicPumpNoiseMemenuhi: getCheckmark(h.pump?.abnormalNoise?.status),
        hydraulicPumpNoiseTidakMemenuhi: getOppositeCheckmark(h.pump?.abnormalNoise?.status),
        hydraulicPumpNoiseResult: h.pump?.abnormalNoise?.result,
        hydraulicValveLeakageMemenuhi: getCheckmark(h.controlValve?.leakage?.status),
        hydraulicValveLeakageTidakMemenuhi: getOppositeCheckmark(h.controlValve?.leakage?.status),
        hydraulicValveLeakageResult: h.controlValve?.leakage?.result,
        hydraulicValveLineConditionMemenuhi: getCheckmark(h.controlValve?.lineCondition?.status),
        hydraulicValveLineConditionTidakMemenuhi: getOppositeCheckmark(h.controlValve?.lineCondition?.status),
        hydraulicValveLineConditionResult: h.controlValve?.lineCondition?.result,
        hydraulicValveReliefFunctionMemenuhi: getCheckmark(h.controlValve?.reliefValveFunction?.status),
        hydraulicValveReliefFunctionTidakMemenuhi: getOppositeCheckmark(h.controlValve?.reliefValveFunction?.status),
        hydraulicValveReliefFunctionResult: h.controlValve?.reliefValveFunction?.result,
        hydraulicValveNoiseMemenuhi: getCheckmark(h.controlValve?.abnormalNoise?.status),
        hydraulicValveNoiseTidakMemenuhi: getOppositeCheckmark(h.controlValve?.abnormalNoise?.status),
        hydraulicValveNoiseResult: h.controlValve?.abnormalNoise?.result,
        hydraulicValveLiftCylinderMemenuhi: getCheckmark(h.controlValve?.liftCylinderValveFunction?.status),
        hydraulicValveLiftCylinderTidakMemenuhi: getOppositeCheckmark(h.controlValve?.liftCylinderValveFunction?.status),
        hydraulicValveLiftCylinderResult: h.controlValve?.liftCylinderValveFunction?.result,
        hydraulicValveTiltCylinderMemenuhi: getCheckmark(h.controlValve?.tiltCylinderValveFunction?.status),
        hydraulicValveTiltCylinderTidakMemenuhi: getOppositeCheckmark(h.controlValve?.tiltCylinderValveFunction?.status),
        hydraulicValveTiltCylinderResult: h.controlValve?.tiltCylinderValveFunction?.result,
        hydraulicValveSteeringCylinderMemenuhi: getCheckmark(h.controlValve?.steeringCylinderValveFunction?.status),
        hydraulicValveSteeringCylinderTidakMemenuhi: getOppositeCheckmark(h.controlValve?.steeringCylinderValveFunction?.status),
        hydraulicValveSteeringCylinderResult: h.controlValve?.steeringCylinderValveFunction?.result,
        hydraulicActuatorLeakageMemenuhi: getCheckmark(h.actuator?.leakage?.status),
        hydraulicActuatorLeakageTidakMemenuhi: getOppositeCheckmark(h.actuator?.leakage?.status),
        hydraulicActuatorLeakageResult: h.actuator?.leakage?.result,
        hydraulicActuatorLineConditionMemenuhi: getCheckmark(h.actuator?.lineCondition?.status),
        hydraulicActuatorLineConditionTidakMemenuhi: getOppositeCheckmark(h.actuator?.lineCondition?.status),
        hydraulicActuatorLineConditionResult: h.actuator?.lineCondition?.result,
        hydraulicActuatorNoiseMemenuhi: getCheckmark(h.actuator?.abnormalNoise?.status),
        hydraulicActuatorNoiseTidakMemenuhi: getOppositeCheckmark(h.actuator?.abnormalNoise?.status),
        hydraulicActuatorNoiseResult: h.actuator?.abnormalNoise?.result,
        
        // Engine On Check
        engineOnStarterDynamoMemenuhi: getCheckmark(e.starterDynamo?.status),
        engineOnStarterDynamoTidakMemenuhi: getOppositeCheckmark(e.starterDynamo?.status),
        engineOnStarterDynamoResult: e.starterDynamo?.result,
        engineOnInstrumentMemenuhi: getCheckmark(e.instrumentFunction?.status),
        engineOnInstrumentTidakMemenuhi: getOppositeCheckmark(e.instrumentFunction?.status),
        engineOnInstrumentResult: e.instrumentFunction?.result,
        engineOnElectricalMemenuhi: getCheckmark(e.electricalFunction?.status),
        engineOnElectricalTidakMemenuhi: getOppositeCheckmark(e.electricalFunction?.status),
        engineOnElectricalResult: e.electricalFunction?.result,
        leakageEngineOilMemenuhi: getCheckmark(e.leakage?.engineOil?.status),
        leakageEngineOilTidakMemenuhi: getOppositeCheckmark(e.leakage?.engineOil?.status),
        leakageEngineOilResult: e.leakage?.engineOil?.result,
        leakageFuelMemenuhi: getCheckmark(e.leakage?.fuel?.status),
        leakageFuelTidakMemenuhi: getOppositeCheckmark(e.leakage?.fuel?.status),
        leakageFuelResult: e.leakage?.fuel?.result,
        leakageCoolantMemenuhi: getCheckmark(e.leakage?.coolant?.status),
        leakageCoolantTidakMemenuhi: getOppositeCheckmark(e.leakage?.coolant?.status),
        leakageCoolantResult: e.leakage?.coolant?.result,
        leakageHydraulicOilMemenuhi: getCheckmark(e.leakage?.hydraulicOil?.status),
        leakageHydraulicOilTidakMemenuhi: getOppositeCheckmark(e.leakage?.hydraulicOil?.status),
        leakageHydraulicOilResult: e.leakage?.hydraulicOil?.result,
        leakageTransmissionOilMemenuhi: getCheckmark(e.leakage?.transmissionOil?.status),
        leakageTransmissionOilTidakMemenuhi: getOppositeCheckmark(e.leakage?.transmissionOil?.status),
        leakageTransmissionOilResult: e.leakage?.transmissionOil?.result,
        leakageFinalDriveOilMemenuhi: getCheckmark(e.leakage?.finalDriveOil?.status),
        leakageFinalDriveOilTidakMemenuhi: getOppositeCheckmark(e.leakage?.finalDriveOil?.status),
        leakageFinalDriveOilResult: e.leakage?.finalDriveOil?.result,
        leakageBrakeFluidMemenuhi: getCheckmark(e.leakage?.brakeFluid?.status),
        leakageBrakeFluidTidakMemenuhi: getOppositeCheckmark(e.leakage?.brakeFluid?.status),
        leakageBrakeFluidResult: e.leakage?.brakeFluid?.result,
        engineOnClutchMemenuhi: getCheckmark(e.clutchFunction?.status),
        engineOnClutchTidakMemenuhi: getOppositeCheckmark(e.clutchFunction?.status),
        engineOnClutchResult: e.clutchFunction?.result,
        engineOnTransmissionMemenuhi: getCheckmark(e.transmissionFunction?.status),
        engineOnTransmissionTidakMemenuhi: getOppositeCheckmark(e.transmissionFunction?.status),
        engineOnTransmissionResult: e.transmissionFunction?.result,
        engineOnBrakeMemenuhi: getCheckmark(e.brakeFunction?.status),
        engineOnBrakeTidakMemenuhi: getOppositeCheckmark(e.brakeFunction?.status),
        engineOnBrakeResult: e.brakeFunction?.result,
        engineOnHornAlarmMemenuhi: getCheckmark(e.hornAndAlarmFunction?.status),
        engineOnHornAlarmTidakMemenuhi: getOppositeCheckmark(e.hornAndAlarmFunction?.status),
        engineOnHornAlarmResult: e.hornAndAlarmFunction?.result,
        engineOnLampsMemenuhi: getCheckmark(e.lampsFunction?.status),
        engineOnLampsTidakMemenuhi: getOppositeCheckmark(e.lampsFunction?.status),
        engineOnLampsResult: e.lampsFunction?.result,
        engineOnHydraulicMotorMemenuhi: getCheckmark(e.hydraulicMotorFunction?.status),
        engineOnHydraulicMotorTidakMemenuhi: getOppositeCheckmark(e.hydraulicMotorFunction?.status),
        engineOnHydraulicMotorResult: e.hydraulicMotorFunction?.result,
        engineOnSteeringCylinderMemenuhi: getCheckmark(e.steeringCylinderFunction?.status),
        engineOnSteeringCylinderTidakMemenuhi: getOppositeCheckmark(e.steeringCylinderFunction?.status),
        engineOnSteeringCylinderResult: e.steeringCylinderFunction?.result,
        engineOnLiftingCylinderMemenuhi: getCheckmark(e.liftingCylinderFunction?.status),
        engineOnLiftingCylinderTidakMemenuhi: getOppositeCheckmark(e.liftingCylinderFunction?.status),
        engineOnLiftingCylinderResult: e.liftingCylinderFunction?.result,
        engineOnTiltingCylinderMemenuhi: getCheckmark(e.tiltingCylinderFunction?.status),
        engineOnTiltingCylinderTidakMemenuhi: getOppositeCheckmark(e.tiltingCylinderFunction?.status),
        engineOnTiltingCylinderResult: e.tiltingCylinderFunction?.result,
        engineOnExhaustGasMemenuhi: getCheckmark(e.exhaustGasCondition?.status),
        engineOnExhaustGasTidakMemenuhi: getOppositeCheckmark(e.exhaustGasCondition?.status),
        engineOnExhaustGasResult: e.exhaustGasCondition?.result,
        engineOnControlLeversMemenuhi: getCheckmark(e.controlLeversFunction?.status),
        engineOnControlLeversTidakMemenuhi: getOppositeCheckmark(e.controlLeversFunction?.status),
        engineOnControlLeversResult: e.controlLeversFunction?.result,
        noiseEngineMemenuhi: getCheckmark(e.abnormalNoise?.fromEngine?.status),
        noiseEngineTidakMemenuhi: getOppositeCheckmark(e.abnormalNoise?.fromEngine?.status),
        noiseEngineResult: e.abnormalNoise?.fromEngine?.result,
        noiseTurbochargerMemenuhi: getCheckmark(e.abnormalNoise?.fromTurbocharger?.status),
        noiseTurbochargerTidakMemenuhi: getOppositeCheckmark(e.abnormalNoise?.fromTurbocharger?.status),
        noiseTurbochargerResult: e.abnormalNoise?.fromTurbocharger?.result,
        noiseTransmissionMemenuhi: getCheckmark(e.abnormalNoise?.fromTransmission?.status),
        noiseTransmissionTidakMemenuhi: getOppositeCheckmark(e.abnormalNoise?.fromTransmission?.status),
        noiseTransmissionResult: e.abnormalNoise?.fromTransmission?.result,
        noiseHydraulicPumpMemenuhi: getCheckmark(e.abnormalNoise?.fromHydraulicPump?.status),
        noiseHydraulicPumpTidakMemenuhi: getOppositeCheckmark(e.abnormalNoise?.fromHydraulicPump?.status),
        noiseHydraulicPumpResult: e.abnormalNoise?.fromHydraulicPump?.result,
        noiseProtectiveCoverMemenuhi: getCheckmark(e.abnormalNoise?.fromProtectiveCover?.status),
        noiseProtectiveCoverTidakMemenuhi: getOppositeCheckmark(e.abnormalNoise?.fromProtectiveCover?.status),
        noiseProtectiveCoverResult: e.abnormalNoise?.fromProtectiveCover?.result,

        // Data Tabel (Array)
        chainInspection: data.chainInspection,
        nonDestructiveTestInspectedPart: data.nonDestructiveTest?.inspectedParts,
        NonDestructiveTestNdtType: data.nonDestructiveTest?.ndtType,
        loadTestResult: data.loadTest,

        // Kesimpulan & Saran
        conclusion: data.conclusion,
        recomendation: data.recommendations,
    };

    try {
        doc.render(renderData);
    } catch (error) {
        console.error("GAGAL RENDER DOKUMEN:", error.message);
        // Throw error yang lebih detail untuk debugging
        throw new Error(`Render Gagal: ${error.message}. Properti: ${error.properties?.details || 'N/A'}`);
    }

    const docxBuffer = doc.getZip().generate({ type: 'nodebuffer', compression: 'DEFLATE' });
    const ownerName = g.ownerName?.replace(/\s+/g, '-') || 'UnknownOwner';
    const fileName = `Laporan-Forklift-${ownerName}-${data.id}.docx`;

    return { docxBuffer, fileName };
};

module.exports = {
    createLaporanForklift,
};