'use strict';

const Joi = require('joi');

// Skema untuk setiap item inspeksi, sekarang sepenuhnya opsional
const inspectionItemSchema = Joi.object({
    result: Joi.string().allow('').required(),
    status: Joi.boolean().allow(true, false).required()
}).required();

// Skema payload utama, di mana semua field dan objek bersifat opsional
const laporanElevatorPayload = Joi.object({
    inspectionType: Joi.string().allow('').required(),
    examinationType: Joi.string().allow('').required(),
    createdAt: Joi.string().allow('').required(),
    extraId: Joi.number().allow('').required(),
    equipmentType: Joi.string().allow('').required(),

    generalData: Joi.object({
        ownerName: Joi.string().allow('').required(),
        ownerAddress: Joi.string().allow('').required(),
        nameUsageLocation: Joi.string().allow('').required(),
        addressUsageLocation: Joi.string().allow('').required(),
        manufacturerOrInstaller: Joi.string().allow('').required(),
        elevatorType: Joi.string().allow('').required(),
        brandOrType: Joi.string().allow('').required(),
        countryAndYear: Joi.string().allow('').required(),
        serialNumber: Joi.string().allow('').required(),
        capacity: Joi.string().allow('').required(),
        speed: Joi.string().allow('').required(),
        floorsServed: Joi.string().allow('').required(),
        permitNumber: Joi.string().allow('').required(),
        inspectionDate: Joi.string().allow('').required()
    }).required(),

    technicalDocumentInspection: Joi.object({
        designDrawing: Joi.boolean().allow(true, false).required(),
        technicalCalculation: Joi.boolean().allow(true, false).required(),
        materialCertificate: Joi.boolean().allow(true, false).required(),
        controlPanelDiagram: Joi.boolean().allow(true, false).required(),
        asBuiltDrawing: Joi.boolean().allow(true, false).required(),
        componentCertificates: Joi.boolean().allow(true, false).required(),
        safeWorkProcedure: Joi.boolean().allow(true, false).required()
    }).required(),

    inspectionAndTesting: Joi.object({
        machineRoomAndMachinery: Joi.object({
            machineMounting: inspectionItemSchema,
            mechanicalBrake: inspectionItemSchema,
            electricalBrake: inspectionItemSchema,
            machineRoomConstruction: inspectionItemSchema,
            machineRoomClearance: inspectionItemSchema,
            machineRoomImplementation: inspectionItemSchema,
            ventilation: inspectionItemSchema,
            machineRoomDoor: inspectionItemSchema,
            mainPowerPanelPosition: inspectionItemSchema,
            rotatingPartsGuard: inspectionItemSchema,
            ropeHoleGuard: inspectionItemSchema,
            machineRoomAccessLadder: inspectionItemSchema,
            floorLevelDifference: inspectionItemSchema,
            fireExtinguisher: inspectionItemSchema,
            machineRoomless: Joi.object({
                panelPlacement: inspectionItemSchema,
                lightingWorkArea: inspectionItemSchema,
                lightingBetweenWorkArea: inspectionItemSchema,
                manualBrakeRelease: inspectionItemSchema,
                fireExtinguisherPlacement: inspectionItemSchema,
            }).required(),
            emergencyStopSwitch: inspectionItemSchema,
        }).required(),
        suspensionRopesAndBelts: Joi.object({
            condition: inspectionItemSchema,
            chainUsage: inspectionItemSchema,
            safetyFactor: inspectionItemSchema,
            ropeWithCounterweight: inspectionItemSchema,
            ropeWithoutCounterweight: inspectionItemSchema,
            belt: inspectionItemSchema,
            slackRopeDevice: inspectionItemSchema,
        }).required(),
        drumsAndSheaves: Joi.object({
            drumGrooves: inspectionItemSchema,
            passengerDrumDiameter: inspectionItemSchema,
            governorDrumDiameter: inspectionItemSchema,
        }).required(),
        hoistwayAndPit: Joi.object({
            construction: inspectionItemSchema,
            walls: inspectionItemSchema,
            inclinedElevatorTrackBed: inspectionItemSchema,
            cleanliness: inspectionItemSchema,
            lighting: inspectionItemSchema,
            emergencyDoorNonStop: inspectionItemSchema,
            emergencyDoorSize: inspectionItemSchema,
            emergencyDoorSafetySwitch: inspectionItemSchema,
            emergencyDoorBridge: inspectionItemSchema,
            carTopClearance: inspectionItemSchema,
            pitClearance: inspectionItemSchema,
            pitLadder: inspectionItemSchema,
            pitBelowWorkingArea: inspectionItemSchema,
            pitAccessSwitch: inspectionItemSchema,
            pitScreen: inspectionItemSchema,
            hoistwayDoorLeaf: inspectionItemSchema,
            hoistwayDoorInterlock: inspectionItemSchema,
            floorLeveling: inspectionItemSchema,
            hoistwaySeparatorBeam: inspectionItemSchema,
            inclinedElevatorStairs: inspectionItemSchema,
        }).required(),
        car: Joi.object({
            frame: inspectionItemSchema,
            body: inspectionItemSchema,
            wallHeight: inspectionItemSchema,
            floorArea: inspectionItemSchema,
            carAreaExpansion: inspectionItemSchema,
            carDoor: inspectionItemSchema,
            carDoorSpecs: Joi.object({
                size: inspectionItemSchema,
                lockAndSwitch: inspectionItemSchema,
                sillClearance: inspectionItemSchema,
            }).required(),
            carToBeamClearance: inspectionItemSchema,
            alarmBell: inspectionItemSchema,
            backupPowerARD: inspectionItemSchema,
            intercom: inspectionItemSchema,
            ventilation: inspectionItemSchema,
            emergencyLighting: inspectionItemSchema,
            operatingPanel: inspectionItemSchema,
            carPositionIndicator: inspectionItemSchema,
            carSignage: Joi.object({
                manufacturerName: inspectionItemSchema,
                loadCapacity: inspectionItemSchema,
                noSmokingSign: inspectionItemSchema,
                overloadIndicator: inspectionItemSchema,
                doorOpenCloseButtons: inspectionItemSchema,
                floorButtons: inspectionItemSchema,
                alarmButton: inspectionItemSchema,
                twoWayIntercom: inspectionItemSchema,
            }).required(),
            carRoofStrength: inspectionItemSchema,
            carTopEmergencyExit: inspectionItemSchema,
            carSideEmergencyExit: inspectionItemSchema,
            carTopGuardRail: inspectionItemSchema,
            guardRailHeight300to850: inspectionItemSchema,
            guardRailHeightOver850: inspectionItemSchema,
            carTopLighting: inspectionItemSchema,
            manualOperationButtons: inspectionItemSchema,
            carInterior: inspectionItemSchema,
        }).required(),
        governorAndSafetyBrake: Joi.object({
            governorRopeClamp: inspectionItemSchema,
            governorSwitch: inspectionItemSchema,
            safetyBrakeSpeed: inspectionItemSchema,
            safetyBrakeType: inspectionItemSchema,
            safetyBrakeMechanism: inspectionItemSchema,
            progressiveSafetyBrake: inspectionItemSchema,
            instantaneousSafetyBrake: inspectionItemSchema,
            safetyBrakeOperation: inspectionItemSchema,
            electricalCutoutSwitch: inspectionItemSchema,
            limitSwitch: inspectionItemSchema,
            overloadDevice: inspectionItemSchema,
        }).required(),
        counterweightGuideRailsAndBuffers: Joi.object({
            counterweightMaterial: inspectionItemSchema,
            counterweightGuardScreen: inspectionItemSchema,
            guideRailConstruction: inspectionItemSchema,
            bufferType: inspectionItemSchema,
            bufferFunction: inspectionItemSchema,
            bufferSafetySwitch: inspectionItemSchema,
        }).required(),
        electricalInstallation: Joi.object({
            installationStandard: inspectionItemSchema,
            electricalPanel: inspectionItemSchema,
            backupPowerARD: inspectionItemSchema,
            groundingCable: inspectionItemSchema,
            fireAlarmConnection: inspectionItemSchema,
            fireServiceElevator: Joi.object({
                backupPower: inspectionItemSchema,
                specialOperation: inspectionItemSchema,
                fireSwitch: inspectionItemSchema,
                label: inspectionItemSchema,
                electricalFireResistance: inspectionItemSchema,
                hoistwayWallFireResistance: inspectionItemSchema,
                carSize: inspectionItemSchema,
                doorSize: inspectionItemSchema,
                travelTime: inspectionItemSchema,
                evacuationFloor: inspectionItemSchema,
            }).required(),
            accessibilityElevator: Joi.object({
                operatingPanel: inspectionItemSchema,
                panelHeight: inspectionItemSchema,
                doorOpenTime: inspectionItemSchema,
                doorWidth: inspectionItemSchema,
                audioInformation: inspectionItemSchema,
                label: inspectionItemSchema,
            }).required(),
            seismicSensor: Joi.object({
                availability: inspectionItemSchema,
                function: inspectionItemSchema,
            }).required(),
        }).required(),
    }).required(),
    
    conclusion: Joi.string().allow('').required(),
    recomendations: Joi.string().allow('').required()
});

module.exports = {
    laporanElevatorPayload,
};